const fs=require('fs');const path=require('path');const crypto=require('crypto');const config=require('../config');const locks=require('../utils/file-lock');
const {validatePatch,error}=require('../schemas/patch-schema');const {parseViewerObjectId}=require('../utils/viewer-id-parser');const {inspectSourceObject,patchFormProperties}=require('./form-patch-service');const {sha256File,assertHash}=require('./integrity-service');const {makeCandidateName,copyProject,removeCandidate}=require('./project-copy-service');
const formContext=require('./form-context-service');
const file=path.join(config.appRoot,'data/changesets.json');
function load(){if(!fs.existsSync(file))return[];const v=JSON.parse(fs.readFileSync(file,'utf8'));return Array.isArray(v)?v:[]}
function save(v){const t=`${file}.tmp`;fs.writeFileSync(t,JSON.stringify(v,null,2)+'\n');fs.renameSync(t,file)}
function audit(event){const f=path.join(config.appRoot,'data/audit/changeset-events.jsonl');fs.mkdirSync(path.dirname(f),{recursive:true});fs.appendFileSync(f,JSON.stringify({timestamp:new Date().toISOString(),...event})+'\n')}
function id(){const d=new Date(),p=n=>String(n).padStart(2,'0');return`cs_${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}_${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}_${crypto.randomBytes(3).toString('hex')}`}
function get(changeSetId){const value=load().find(x=>x.changeSetId===changeSetId);if(!value)throw error('CHANGESET_NOT_FOUND','Change Set을 찾을 수 없습니다.',404);return value}
function mutate(changeSetId,fn){const all=load(),i=all.findIndex(x=>x.changeSetId===changeSetId);if(i<0)throw error('CHANGESET_NOT_FOUND','Change Set을 찾을 수 없습니다.',404);fn(all[i]);all[i].updatedAt=new Date().toISOString();save(all);return all[i]}
function requireDraft(cs){if(cs.status!=='DRAFT')throw error('CHANGESET_NOT_DRAFT','DRAFT 상태에서만 수정할 수 있습니다.',409)}
function create(body){const context=formContext.resolve(body);const draft=/^[A-Za-z0-9_-]{1,80}$/.test(body.layoutDraftId||'')?body.layoutDraftId:null,all=load(),existing=draft&&all.find(x=>x.layoutDraftId===draft&&x.projectName===body.projectName&&x.formName===body.formName&&x.status==='DRAFT');if(existing)return existing;const now=new Date().toISOString(),cs={changeSetId:id(),layoutDraftId:draft,projectName:context.projectName,formName:context.formName,origin:context.origin,status:'DRAFT',patches:[],createdAt:now,updatedAt:now,candidateId:null};all.push(cs);save(all);audit({event:'CHANGESET_CREATED',changeSetId:cs.changeSetId,status:cs.status});return cs}
function addPatch(changeSetId,body){const patch=validatePatch(body);return mutate(changeSetId,cs=>{requireDraft(cs);const same=cs.patches.find(x=>x.sourceObjectId===patch.sourceObjectId&&x.sourceProperty===patch.sourceProperty&&x.scope===patch.scope);if(same){same.after=patch.after;same.updatedAt=new Date().toISOString();audit({event:'PATCH_UPDATED',changeSetId,patchId:same.patchId,sourceObjectId:same.sourceObjectId,property:same.sourceProperty,before:same.before,after:same.after});if(Object.is(same.before,same.after))cs.patches=cs.patches.filter(x=>x.patchId!==same.patchId)}else{cs.patches.push(patch);audit({event:'PATCH_ADDED',changeSetId,patchId:patch.patchId,sourceObjectId:patch.sourceObjectId,property:patch.sourceProperty,before:patch.before,after:patch.after})}})}
function updatePatch(changeSetId,patchId,body){return mutate(changeSetId,cs=>{requireDraft(cs);const i=cs.patches.findIndex(x=>x.patchId===patchId);if(i<0)throw error('PATCH_NOT_FOUND','Patch를 찾을 수 없습니다.',404);const next=validatePatch({...cs.patches[i],...body,patchId,createdAt:cs.patches[i].createdAt});if(next.sourceObjectId!==cs.patches[i].sourceObjectId||next.sourceProperty!==cs.patches[i].sourceProperty)throw error('PATCH_CONFLICT','Patch 대상 키는 변경할 수 없습니다.');cs.patches[i]=next;audit({event:'PATCH_UPDATED',changeSetId,patchId,after:next.after})})}
function deletePatch(changeSetId,patchId){return mutate(changeSetId,cs=>{requireDraft(cs);const n=cs.patches.length;cs.patches=cs.patches.filter(x=>x.patchId!==patchId);if(cs.patches.length===n)throw error('PATCH_NOT_FOUND','Patch를 찾을 수 없습니다.',404);audit({event:'PATCH_DELETED',changeSetId,patchId})})}
function clearPatches(changeSetId){return mutate(changeSetId,cs=>{requireDraft(cs);cs.patches=[];audit({event:'PATCHES_CLEARED',changeSetId})})}
function sourceObject(query){const context=formContext.resolve(query),history=require('./structural-history-service'),dynamicQuery={...query,layoutDraftId:query.layoutDraftId||formContext.defaultDraft(context)};try{let state=history.get(dynamicQuery),fallback=false;if(state.kind!=='DYNAMIC_CANDIDATE'&&!query.layoutDraftId){state=history.findDynamic(query.projectName,query.formName)||state;fallback=state.kind==='DYNAMIC_CANDIDATE'}if(state.kind==='DYNAMIC_CANDIDATE'){if(fallback){const formPath=path.join(config.projectsRoot,state.projectName,state.formName,'form.ubjf'),parsed=parseViewerObjectId(query.viewerObjectId);if(!parsed)throw error('DYNAMIC_TEMPLATE_RESOLUTION_FAILED','Runtime identity 형식이 올바르지 않습니다.');const source=inspectSourceObject({formPath,sourceObjectId:parsed.sourceObjectId,bandId:parsed.bandId,runtimeText:query.runtimeText||''});return{...source,sourceKind:parsed.rowIndex>0?'RUNTIME_INSTANCE':'SOURCE_TEMPLATE',templateSourceId:parsed.sourceObjectId,notice:parsed.rowIndex>0?'반복 데이터의 원본 서식을 편집합니다.':null,properties:source.properties.filter(x=>parsed.rowIndex===0||x!=='text')}}return require('./dynamic-logical-table-service').sourceObject(dynamicQuery)}}catch(e){if(/^DYNAMIC_/.test(e.code||''))throw e;}const parsed=parseViewerObjectId(query.viewerObjectId)||((context.origin==='IMPORTED'&&/^(?:IMPLB|IMPCL|IMPIMG)\d{4}$/.test(query.viewerObjectId||''))?{sourceObjectId:query.viewerObjectId,bandId:'FREEFORM',rowIndex:0}:null);if(!parsed)throw error('UNSUPPORTED_VIEWER_ID','지원하지 않는 Viewer ID입니다.');const form=path.join(config.projectsRoot,query.projectName,query.formName,'form.ubjf');return inspectSourceObject({formPath:form,sourceObjectId:parsed.sourceObjectId,bandId:context.origin==='IMPORTED'?'':parsed.bandId,runtimeText:query.runtimeText||''})}
function createCandidate(changeSetId){const initial=get(changeSetId);requireDraft(initial);if(!initial.patches.length)throw error('CHANGESET_EMPTY','Change Set이 비어 있습니다.');const context=formContext.resolve(initial),key=`${initial.projectName}/${initial.formName}`;if(!locks.acquire(key))throw error('LOCKED','동일 원본 작업이 진행 중입니다.',409);let name=null;const started=Date.now(),sourceRoot=path.join(config.projectsRoot,initial.projectName),sourceForm=path.join(sourceRoot,initial.formName,'form.ubjf'),sourceInfo=path.join(sourceRoot,initial.formName,'info.xml'),formHash=sha256File(sourceForm),infoHash=sha256File(sourceInfo);mutate(changeSetId,cs=>{cs.status='CREATING_CANDIDATE'});audit({event:'CANDIDATE_CREATION_STARTED',changeSetId,patchCount:initial.patches.length});try{name=makeCandidateName(initial.projectName,context.origin==='IMPORTED'?'mvp12':'mvp4');const copyStarted=Date.now(),root=copyProject(initial.projectName,name),copyMs=Date.now()-copyStarted,candidateForm=path.join(root,initial.formName,'form.ubjf'),patchStarted=Date.now(),result=patchFormProperties({sourceFormPath:sourceForm,candidateFormPath:candidateForm,patches:initial.patches}),patchMs=Date.now()-patchStarted;assertHash(sourceForm,formHash);assertHash(sourceInfo,infoHash);const candidateId=`cand_${crypto.randomBytes(8).toString('hex')}`,previewUrl=`/mysuit/UView5/index.jsp?projectName=${name}&formName=${initial.formName}`,record={candidateId,status:'ACTIVE',projectName:initial.projectName,formName:initial.formName,candidateProjectName:name,changeSetId,originalFormSha256:formHash,originalInfoSha256:infoHash,candidateFormSha256:result.candidateSha256,createdAt:new Date().toISOString(),previewUrl,patches:initial.patches,changedObjects:new Set(initial.patches.map(x=>x.sourceObjectId)).size,structuralDiff:result.structuralDiff};const candidates=JSON.parse(fs.readFileSync(config.dataFile,'utf8'));candidates.push(record);const temp=`${config.dataFile}.tmp`;fs.writeFileSync(temp,JSON.stringify(candidates,null,2)+'\n');fs.renameSync(temp,config.dataFile);mutate(changeSetId,cs=>{cs.status='CANDIDATE_ACTIVE';cs.candidateId=candidateId;cs.candidateProjectName=name;cs.previewUrl=previewUrl});audit({event:'CANDIDATE_CREATION_SUCCEEDED',changeSetId,candidateId,candidateProjectName:name,patchCount:initial.patches.length});return{success:true,...record,performance:{copyMs,patchMs,totalCreateMs:Date.now()-started}}}catch(e){if(name)try{removeCandidate(name)}catch(_){};mutate(changeSetId,cs=>{cs.status='FAILED';cs.errorCode=e.code||'MULTI_PATCH_VALIDATION_FAILED'});audit({event:'CANDIDATE_CREATION_FAILED',changeSetId,errorCode:e.code||'MULTI_PATCH_VALIDATION_FAILED'});assertHash(sourceForm,formHash);throw e}finally{locks.release(key)}}
function discard(changeSetId){const cs=get(changeSetId);if(cs.candidateId)throw error('CANDIDATE_ALREADY_ACTIVE','활성 후보를 먼저 폐기해야 합니다.',409);return mutate(changeSetId,value=>{value.status='DISCARDED';audit({event:'CHANGESET_DISCARDED',changeSetId})})}
function findDraft(scope){return load().find(x=>x.layoutDraftId===scope.layoutDraftId&&x.projectName===scope.projectName&&x.formName===scope.formName&&x.status==='DRAFT')||null}
function replaceDraftPatches(scope,patches){const cs=findDraft(scope);if(!cs){if(!(patches||[]).length)return null;throw error('CHANGESET_NOT_FOUND','History 대상 Change Set을 찾을 수 없습니다.',404)}return mutate(cs.changeSetId,value=>{requireDraft(value);value.patches=JSON.parse(JSON.stringify(patches||[]))})}
module.exports={load,get,create,addPatch,updatePatch,deletePatch,clearPatches,sourceObject,createCandidate,discard,findDraft,replaceDraftPatches};
