(function(){
  'use strict';
  const $=id=>document.getElementById(id),MAX_DOCUMENT=10*1024*1024,MAX_JSON=1024*1024,MAX_DIM=5*1024*1024,KNOWN_SHA='aed71814397bf8bea2bfa24cb417dfb5cb6e20634bbfcc3b58a95999bef34144';
  let documentFile=null,documentKnown=false,jsonFileName=null,jsonSource='DIRECT',dimFile=null,dimRaw='',dimValid=false,requiredAssets=[],assetFiles=[],assetsValid=true,busy=false,state='IDLE';
  const setError=(id,message='')=>{$(id).textContent=message},isHwpx=()=>/\.hwpx$/i.test(documentFile?.name||''),isImage=()=>/\.(png|jpe?g)$/i.test(documentFile?.name||''),formatBytes=n=>n<1024*1024?`${(n/1024).toFixed(1)} KB`:`${(n/1024/1024).toFixed(2)} MB`;
  function validateDocument(file){if(!file)throw new Error('문서를 선택해 주세요.');if(/\.hwp$/i.test(file.name))throw new Error('HWP 파일은 현재 지원하지 않습니다. HWPX 형식으로 저장한 후 다시 업로드해 주세요.');if(!/\.(hwpx|png|jpe?g)$/i.test(file.name))throw new Error('지원하지 않는 파일 형식입니다. PNG, JPG, JPEG, HWPX 파일을 선택해 주세요.');if(!file.size)throw new Error('빈 파일은 업로드할 수 없습니다.');if(file.size>MAX_DOCUMENT)throw new Error('문서 크기는 10MB 이하여야 합니다.');}
  async function digest(file){const hash=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')}
  function imageSize(file){return new Promise(resolve=>{const image=new Image(),url=URL.createObjectURL(file);image.onload=()=>{resolve(`${image.naturalWidth} × ${image.naturalHeight}`);URL.revokeObjectURL(url)};image.onerror=()=>{resolve('이미지 크기 확인 불가');URL.revokeObjectURL(url)};image.src=url})}
  function renderDocument(details){$('selected-files').hidden=!documentFile;$('document-drop').hidden=!!documentFile;$('hwpx-note').hidden=!isHwpx();$('image-note').hidden=!isImage();if(!documentFile){$('document-meta').replaceChildren();return}const icon=document.createElement('span'),copy=document.createElement('div'),name=document.createElement('strong'),meta=document.createElement('small'),status=document.createElement('span'),remove=document.createElement('button');icon.className='file-symbol';icon.textContent=isHwpx()?'H':'▧';copy.className='file-copy';name.textContent=documentFile.name;meta.textContent=`${isHwpx()?'HWPX 문서':'이미지'} · ${formatBytes(documentFile.size)}${details?` · ${details}`:''}`;copy.append(name,meta);status.className='file-state';status.textContent='✓ 준비 완료';remove.type='button';remove.className='icon-button';remove.setAttribute('aria-label','문서 파일 삭제');remove.textContent='×';remove.onclick=clearDocument;$('document-meta').replaceChildren(icon,copy,status,remove)}
  async function setDocument(file){try{validateDocument(file);const duplicate=documentFile&&file.name===documentFile.name&&file.size===documentFile.size;if(duplicate)return;documentFile=file;documentKnown=isHwpx()||(await digest(file))===KNOWN_SHA;if(isHwpx()&&dimFile)clearDim(false);setError('document-error');renderDocument(isHwpx()?'바로 변환 가능':await imageSize(file));state='FILE_SELECTED'}catch(error){documentFile=null;documentKnown=false;renderDocument();setError('document-error',error.message);state='ERROR'}update()}
  function clearDocument(){documentFile=null;documentKnown=false;$('document-file').value='';renderDocument();setError('document-error');state='IDLE';update()}
  function validateJson(){const raw=$('json-input').value.trim();if(!raw){setError('json-error');$('summary-json').textContent='없음';return true}if(new Blob([raw]).size>MAX_JSON){setError('json-error','JSON 크기는 1MB 이하여야 합니다.');return false}try{JSON.parse(raw);setError('json-error');$('summary-json').textContent=jsonSource==='FILE'?(jsonFileName||'파일 등록'):'직접 입력';return true}catch(_){setError('json-error','JSON 형식이 올바르지 않습니다.');return false}}
  function update(){const jsonOk=validateJson(),sourceOk=!!documentFile&&(isHwpx()||(documentKnown&&!dimFile)||(isImage()&&dimValid&&assetsValid));$('create-form').disabled=busy||!sourceOk||!jsonOk;$('summary-document').textContent=documentFile?documentFile.name:'선택 전';$('advanced').hidden=isHwpx();if(busy)state='PROCESSING';else if(documentFile&&sourceOk&&jsonOk)state='READY';else if(documentFile)state='FILE_SELECTED';else if(state!=='ERROR')state='IDLE';if(isHwpx())$('policy-note').textContent='문서가 준비되었습니다. 바로 서식 생성을 시작할 수 있습니다.';else if(isImage()&&!documentKnown&&!dimValid)$('policy-note').textContent='이 이미지에는 DIM 분석 파일이 필요합니다. 고급 옵션에서 추가해 주세요.';else if(dimFile&&!dimValid)$('policy-note').textContent='올바른 DIM 분석 파일을 선택해 주세요.';else if(dimValid&&!assetsValid)$('policy-note').textContent='분석 파일에 필요한 이미지 파일을 함께 선택해 주세요.';else if(sourceOk)$('policy-note').textContent='문서가 준비되었습니다. 서식 생성을 시작할 수 있습니다.';else $('policy-note').textContent='문서 파일을 선택하면 서식 생성을 시작할 수 있습니다.'}
  function fileBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=()=>reject(new Error('파일을 읽을 수 없습니다.'));reader.readAsDataURL(file)})}
  async function setDim(file){dimFile=file||null;dimRaw='';dimValid=false;requiredAssets=[];clearAssets(false);setError('dim-error');$('dim-meta').hidden=true;$('asset-panel').hidden=true;if(!file)return update();if(!/\.json$/i.test(file.name)){setError('dim-error','DIM 파일 형식이 올바르지 않습니다.');return update()}if(!file.size){setError('dim-error','빈 DIM 파일은 업로드할 수 없습니다.');return update()}if(file.size>MAX_DIM){setError('dim-error','DIM 파일 크기는 5MB 이하여야 합니다.');return update()}try{dimRaw=await file.text();const parsed=JSON.parse(dimRaw),response=await fetch('/api/ai-builder/import/validate-dim',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({dim:{raw:dimRaw,fileName:file.name}})}),data=await response.json();if(!response.ok)throw new Error(data.message);requiredAssets=Array.isArray(parsed.assets)?parsed.assets:[];assetsValid=!requiredAssets.length;dimValid=true;$('dim-meta').hidden=false;$('dim-name').textContent=file.name;$('dim-details').textContent=`${formatBytes(file.size)} · v${data.version}`;$('asset-panel').hidden=!requiredAssets.length;if(requiredAssets.length)$('asset-guide').textContent=`함께 필요한 이미지 ${requiredAssets.length}개: ${requiredAssets.map(x=>x.relativePath).join(', ')}`;}catch(error){setError('dim-error',error.message||'DIM 분석 파일을 확인할 수 없습니다.')}update()}
  async function setAssets(files){assetFiles=[...files];assetsValid=false;setError('asset-error');$('asset-meta').hidden=true;if(!assetFiles.length)return update();try{const byName=new Map(assetFiles.map(file=>[file.name,file]));if(byName.size!==assetFiles.length)throw new Error('중복된 이미지 파일명이 있습니다.');for(const asset of requiredAssets){const file=byName.get(asset.relativePath);if(!file)throw new Error(`필요한 이미지를 선택해 주세요: ${asset.relativePath}`);if(file.size!==asset.size||await digest(file)!==asset.sha256)throw new Error(`이미지 파일이 분석 결과와 일치하지 않습니다: ${asset.relativePath}`);byName.delete(asset.relativePath)}if(byName.size)throw new Error(`분석 결과에 없는 이미지입니다: ${[...byName.keys()][0]}`);assetsValid=true;$('asset-meta').hidden=false;$('asset-name').textContent=assetFiles.map(x=>x.name).join(', ');$('asset-details').textContent=`${assetFiles.length}개 · ${formatBytes(assetFiles.reduce((n,x)=>n+x.size,0))}`;}catch(error){setError('asset-error',error.message)}update()}
  function clearAssets(refresh=true){assetFiles=[];assetsValid=!requiredAssets.length;$('asset-files').value='';$('asset-meta').hidden=true;setError('asset-error');if(refresh)update()}
  function clearDim(refresh=true){dimFile=null;dimRaw='';dimValid=false;requiredAssets=[];clearAssets(false);$('dim-file').value='';$('dim-meta').hidden=true;$('asset-panel').hidden=true;setError('dim-error');if(refresh)update()}
  function showProgress(step,copy){const ids=['progress-check','progress-analyze','progress-create','progress-ready'],index=ids.indexOf(step);ids.forEach((id,i)=>{$(id).className=i<index?'done':i===index?'active':'';if(i<index)$(id).querySelector('span').textContent='✓'});$('job-copy').textContent=copy}
  function showFormError(message){$('job-state').hidden=true;$('form-error-wrap').hidden=false;$('form-error').textContent=message||'파일을 확인한 후 다시 시도해 주세요.';state='ERROR'}
  $('document-file').onchange=e=>setDocument(e.target.files[0]);const drop=$('document-drop');for(const event of['dragenter','dragover'])drop.addEventListener(event,e=>{e.preventDefault();drop.classList.add('drag')});for(const event of['dragleave','drop'])drop.addEventListener(event,e=>{e.preventDefault();drop.classList.remove('drag')});drop.addEventListener('drop',e=>setDocument(e.dataTransfer.files[0]));drop.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('document-file').click()}});
  function renderJsonFile(file){const root=$('json-meta');root.hidden=!file;if(!file){root.replaceChildren();$('json-file-name').textContent='선택된 파일 없음';return}const icon=document.createElement('span'),copy=document.createElement('div'),name=document.createElement('strong'),details=document.createElement('small'),status=document.createElement('span'),remove=document.createElement('button');icon.className='file-type-icon';icon.textContent='{ }';name.textContent=file.name;details.textContent=formatBytes(file.size);copy.className='file-copy';copy.append(name,details);status.className='file-state';status.textContent='✓ 확인 완료';remove.type='button';remove.textContent='×';remove.setAttribute('aria-label','JSON 파일 삭제');remove.onclick=()=>{$('json-file').value='';$('json-input').value='';jsonFileName=null;jsonSource='DIRECT';renderJsonFile(null);update()};root.replaceChildren(icon,copy,status,remove);$('json-file-name').textContent=''}
  $('json-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!/\.json$/i.test(file.name)){setError('json-error','JSON 파일만 업로드할 수 있습니다.');return}if(file.size>MAX_JSON){setError('json-error','JSON 크기는 1MB 이하여야 합니다.');return}try{$('json-input').value=await file.text();jsonFileName=file.name;jsonSource='FILE';if(!validateJson())return;renderJsonFile(file)}catch(_){setError('json-error','JSON 파일을 읽을 수 없습니다.')}update()};
  $('json-input').addEventListener('input',()=>{if(jsonSource==='FILE'){jsonSource='DIRECT';jsonFileName=null;renderJsonFile(null);$('json-file-name').textContent='직접 입력 데이터'}update()});$('json-toggle').onclick=()=>{const panel=$('json-direct'),open=!panel.hidden;panel.hidden=open;$('json-toggle').textContent=open?'직접 입력':'직접 입력 닫기';$('json-toggle').setAttribute('aria-expanded',String(!open));if(!open)$('json-input').focus()};$('dim-file').onchange=e=>setDim(e.target.files[0]);$('dim-remove').onclick=()=>clearDim();$('asset-files').onchange=e=>setAssets(e.target.files);$('asset-remove').onclick=()=>clearAssets();
  $('help-button').onclick=()=>document.querySelector('.info-panel').scrollIntoView({behavior:'smooth'});$('error-close').onclick=()=>{$('form-error-wrap').hidden=true;setError('form-error')};
  $('import-form').onsubmit=async e=>{e.preventDefault();update();if(busy||$('create-form').disabled)return;busy=true;update();$('form-error-wrap').hidden=true;$('job-state').hidden=false;showProgress('progress-check','문서를 확인하고 있습니다.');try{const document={name:documentFile.name,type:documentFile.type,base64:await fileBase64(documentFile)},assets=[];for(const file of assetFiles)assets.push({name:file.name,type:file.type,base64:await fileBase64(file)});showProgress('progress-analyze','문서 구조를 분석하고 있습니다.');const raw=$('json-input').value.trim(),payload={document,dim:dimValid?{raw:dimRaw,fileName:dimFile.name}:null,assets,json:raw?{raw,fileName:jsonSource==='FILE'?jsonFileName:null}:null};await new Promise(resolve=>setTimeout(resolve,120));showProgress('progress-create','서식을 생성하고 있습니다.');const response=await fetch('/api/ai-builder/import',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok||!data.success)throw new Error(data.message);showProgress('progress-ready','편집 화면을 준비하고 있습니다.');state='SUCCESS';location.assign(data.builderUrl)}catch(error){busy=false;showFormError(error.message);update()}};
  update();window.aiBuilderImport={setDocument,setDim,setAssets,validateJson,get busy(){return busy},get state(){return state}};
})();
