(function(){
  const $=id=>document.getElementById(id),iframe=$('viewer'),params=new URLSearchParams(location.search),requestedProject=params.get('projectName')||'',projectName=/^(?:sample|(?:import_mvp(?:1[0-3]|2[0-2])|import_user_test)_\d{8}_\d{6}_[a-f0-9]{6}|ai_builder_mvp043(?:1)?_(?:certification_)?[A-Za-z0-9_-]+)$/.test(requestedProject)?requestedProject:'sample',formName=projectName==='sample'?'sample':'SampleReport_FreeForm',origin=projectName==='sample'?'ORIGINAL':'IMPORTED',originalUrl=`/mysuit/UView5/index.jsp?projectName=${encodeURIComponent(projectName)}&formName=${encodeURIComponent(formName)}`;
  window.__formContext={projectName,formName,origin};iframe.src=originalUrl;
  const defs={text:{source:'text',type:'text'},fontSize:{source:'fontSize',type:'number'},fontWeight:{source:'fontWeight',type:'string'},textAlign:{source:'textAlign',type:'string'},visible:{source:'visible',type:'boolean'},left:{source:'x',type:'number'},top:{source:'y',type:'number'},width:{source:'width',type:'number'},height:{source:'height',type:'number'},scaleType:{source:'scaleType',type:'number'},data:{source:'data',type:'ref'}};
  const names={text:'문구',fontSize:'글꼴 크기',fontWeight:'굵기',textAlign:'가로 정렬',visible:'표시 여부',left:'X 위치',top:'Y 위치',width:'너비',height:'높이',scaleType:'이미지 맞춤',data:'이미지'};
  const requestedDraft=new URLSearchParams(location.search).get('layoutDraftId');
  const defaultDraft=origin==='IMPORTED'?`import_${projectName}_${formName}_default`.slice(0,80):'layout_sample_default';
  const state={review:false,view:'original',inspector:null,selection:null,source:null,changeSet:null,candidate:null,highlight:false,unsupported:0,layoutDraftId:/^[A-Za-z0-9_-]{1,80}$/.test(requestedDraft||'')?requestedDraft:defaultDraft,renderPatches:[],renderPatchesReady:false,formContext:window.__formContext};
  function status(message,bad=false){$('status').textContent=message;$('status').style.color=bad?'#b42318':'#08745f'}
  async function api(url,options={}){const r=await fetch(url,{headers:{'content-type':'application/json'},...options}),d=await r.json();if(!r.ok)throw new Error(`${d.code}: ${d.message}`);return d}
  const safe=v=>String(v??'').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g,'').slice(0,200);
  function textParts(v){v=String(v??'');const leading=v.match(/^\s*/)?.[0]||'',trailing=v.match(/\s*$/)?.[0]||'';return{leading,trailing,core:v.slice(leading.length,v.length-trailing.length)}}
  async function newChangeSet(){const d=await api('/api/change-sets',{method:'POST',body:JSON.stringify({layoutDraftId:state.layoutDraftId,projectName,formName})});state.changeSet=d.changeSet;renderPatches();applyPreview();status(`Change Set ${state.changeSet.changeSetId} 준비됨`)}
  let attachedWindow=null,attachTimer=null,attaching=false;
  function scheduleAttach(){clearTimeout(attachTimer);attachTimer=setTimeout(attach,100)}
  let stableSignature='',stableRounds=0;
  function attach(){if(!state.renderPatchesReady){scheduleAttach();return}const win=iframe.contentWindow,canvas=win?.canvasModule?.getCanvas?.(0),upper=win?.document?.querySelector?.('canvas.upper-canvas'),objects=canvas?.getObjects?.()||[],signature=objects.map(o=>`${o.id||''}:${o.className||''}:${o.left}:${o.top}`).join('|');if(!canvas||objects.length===0||!upper||upper.getBoundingClientRect().width<=0){stableSignature='';stableRounds=0;scheduleAttach();return}if(signature!==stableSignature){stableSignature=signature;stableRounds=1;scheduleAttach();return}if(++stableRounds<2){scheduleAttach();return}if(state.inspector&&attachedWindow===win)return;if(attaching)return;attaching=true;try{state.inspector?.detach();state.inspector=MvpViewerInspector.attach(iframe,selectObject,()=>state.review&&window.MvpWorkspaceMode?.directEdit?.()!==false);attachedWindow=win;win.removeEventListener('keydown',handlePositionKey);win.addEventListener('keydown',handlePositionKey);applyHighlights();applyPreview();configureMoveMode();applyRenderPositions(true);$('viewer-state').textContent=`${state.view==='candidate'?'후보':'원본'} · 객체 ${state.inspector.objectCount}개`;requestAnimationFrame(()=>iframe.classList.remove('viewer-loading'));window.dispatchEvent(new CustomEvent('mysuit-editor-attached',{detail:{...state.formContext,objectCount:state.inspector.objectCount}}))}catch(_){scheduleAttach()}finally{attaching=false}}
  iframe.addEventListener('load',()=>{clearTimeout(attachTimer);state.inspector=null;attachedWindow=null;iframe.classList.add('viewer-loading');$('viewer-state').textContent=`${state.view==='candidate'?'후보':'원본'} 로딩 중`;attach();if(state.view==='candidate'&&state.candidate)setTimeout(verifyCandidate,700)});
  async function selectObject(render){state.selection=render;for(const [key]of Object.entries(defs))$(`prop-${key}`).disabled=true;$('viewer-id').textContent=render.viewerObjectId;$('source-id').textContent=render.sourceObjectId;$('band-id').textContent=render.bandId||'FREEFORM';$('row-index').textContent=render.rowIndex;$('class-name').textContent=render.className;updatePositionPanel(positionBefore(render),{left:render.left,top:render.top});try{const q=new URLSearchParams({layoutDraftId:state.layoutDraftId,projectName,formName,viewerObjectId:render.viewerObjectId,runtimeText:render.currentText,renderInstanceKey:render.renderInstanceKey});const d=await api(`/api/source-object?${q}`);state.source=d.source;$('source-class').textContent=d.source.sourceClassName;$('position-confidence').textContent=d.source.positionConfidence;fillEditor();$('selection-help').textContent=`드래그 이동 가능 · 속성 수정: ${d.source.properties.map(x=>names[x]).join(', ')}`;$('selection-help').className='selected-notice';$('add-changes').disabled=false;$('reset-object').disabled=false;status('속성 수정과 위치 이동이 활성화됐습니다.');window.dispatchEvent(new CustomEvent('mysuit-object-selection-resolved',{detail:{render,source:d.source}}))}catch(e){state.source=null;state.unsupported++;$('source-class').textContent='동적/복합 객체';$('position-confidence').textContent=render.mappingConfidence==='render-instance-only'?'render-instance-only':'미검증';$('selection-help').textContent=`위치 이동 가능 · 원본 속성 편집 미지원 (${e.message})`;$('selection-help').className='selected-notice';$('add-changes').disabled=true;$('reset-object').disabled=true;status('이 객체는 렌더 위치만 이동할 수 있습니다.');renderPatches()}}
  function fillEditor(){const s=state.source,r=state.selection,values={...r,...s.values};for(const patch of state.changeSet?.patches||[])if(patch.sourceObjectId===r.sourceObjectId)values[patch.viewerProperty]=patch.after;for(const [key,def]of Object.entries(defs)){const el=$(`prop-${key}`),supported=s.properties.includes(key);el.disabled=!supported;let value=values[key];if(key==='text'){const p=textParts(value);s.textAffixes=p;value=p.core}if(def.type==='boolean')el.checked=value!==false;else el.value=value??''}applyPreview()}
  function readValue(key){const el=$(`prop-${key}`),def=defs[key];if(def.type==='boolean')return el.checked;if(def.type==='number')return Number(el.value);if(def.type==='ref')return el.value;let value=safe(el.value);if(key==='text'){value=value.trim();const a=state.source.textAffixes||{leading:'',trailing:''};return`${a.leading}${value}${a.trailing}`}return value}
  function patchBody(key){const before=state.source.values[key],after=readValue(key),s=state.selection;return{pageIndex:0,viewerObjectId:s.viewerObjectId,sourceObjectId:s.sourceObjectId,bandId:state.source.bandId,rowIndex:s.rowIndex,className:state.source.sourceClassName,scope:'SOURCE_OBJECT_ALL_INSTANCES',operation:'updateProperty',viewerProperty:key,sourceProperty:defs[key].source,before,after,runtimeText:s.currentText}}
  function previewPatches(){if(state.changeSet?.status!=='DRAFT')return[];const patches=[...(state.changeSet?.patches||[])];if(state.source&&state.selection&&state.view==='original')for(const key of state.source.properties){const draft=patchBody(key),index=patches.findIndex(p=>p.sourceObjectId===draft.sourceObjectId&&p.viewerProperty===key);if(index>=0)patches[index]={...patches[index],after:draft.after};else if(!Object.is(draft.before,draft.after))patches.push(draft)}return patches}
  function restoreRenderPositions(){for(const patch of state.renderPatches)state.inspector?.setPosition(patch.viewerObjectId,patch.before,true,patch)}
  function applyPreview(){if(state.view==='original')state.inspector?.setPreviews(state.review?previewPatches():[]);if(state.review)applyRenderPositions();else restoreRenderPositions()}
  let autoSaveQueue=Promise.resolve();
  const autoSaveTimers=new Map();
  function autoSave(key){
    if(!state.source||!state.selection||state.changeSet?.status!=='DRAFT'||!state.source.properties.includes(key))return;
    const body=patchBody(key),changeSetId=state.changeSet.changeSetId;
    autoSaveQueue=autoSaveQueue.then(async()=>{
      const existing=state.changeSet?.patches?.find(p=>p.sourceObjectId===body.sourceObjectId&&p.viewerProperty===key);
      let d;
      if(Object.is(body.before,body.after)){
        if(!existing)return;
        d=await api(`/api/change-sets/${changeSetId}/patches/${existing.patchId}`,{method:'DELETE'});
      }else d=await api(`/api/change-sets/${changeSetId}/patches`,{method:'POST',body:JSON.stringify(body)});
      state.changeSet=d.changeSet;renderPatches();status(`${names[key]} 변경이 자동 저장되었습니다.`);
    }).catch(e=>status(e.message,true));
  }
  function scheduleAutoSave(key,delay=350){clearTimeout(autoSaveTimers.get(key));autoSaveTimers.set(key,setTimeout(()=>{autoSaveTimers.delete(key);autoSave(key)},delay))}
  function flushAutoSave(key){clearTimeout(autoSaveTimers.get(key));autoSaveTimers.delete(key);autoSave(key)}
  for(const key of Object.keys(defs)){
    const el=$(`prop-${key}`),def=defs[key];
    if(def.type==='text'||def.type==='number')el.addEventListener('input',()=>{applyPreview();if(key!=='text')scheduleAutoSave(key)});
    else el.addEventListener('change',applyPreview);
    if(def.type==='text'||def.type==='number')el.addEventListener('blur',()=>flushAutoSave(key));
    else el.addEventListener('change',()=>autoSave(key));
    if(key==='text')el.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();el.blur()}else if(event.key==='Escape'){event.preventDefault();const saved=state.changeSet?.patches?.find(p=>p.sourceObjectId===state.selection?.sourceObjectId&&p.viewerProperty==='text'),value=saved?.after??state.source?.values?.text??'';el.value=textParts(value).core;applyPreview();el.blur()}});
  }
  $('add-changes').onclick=async()=>{try{let count=0;for(const key of state.source.properties){const body=patchBody(key);if(!Object.is(body.before,body.after)){const d=await api(`/api/change-sets/${state.changeSet.changeSetId}/patches`,{method:'POST',body:JSON.stringify(body)});state.changeSet=d.changeSet;count++}}renderPatches();status(count?`${count}개 속성을 변경 목록에 반영했습니다.`:'변경된 속성이 없습니다.')}catch(e){status(e.message,true)}};
  $('reset-object').onclick=()=>{if(!state.source)return;const saved=state.changeSet?.patches||[],values={...state.source.values};for(const patch of saved)if(patch.sourceObjectId===state.selection.sourceObjectId)values[patch.viewerProperty]=patch.after;for(const key of state.source.properties){const el=$(`prop-${key}`),value=values[key];if(defs[key].type==='boolean')el.checked=value!==false;else if(key==='text')el.value=textParts(value).core;else el.value=value??''}applyPreview();status('입력값을 변경 목록의 현재 값으로 되돌렸습니다.')};
  function fmt(v){return typeof v==='boolean'?(v?'표시':'숨김'):String(v)}
  function renderPatches(){const patches=state.changeSet?.patches||[],objects=new Set(patches.map(x=>x.sourceObjectId));$('object-count').textContent=objects.size;$('patch-count').textContent=patches.length;$('nav-patch-count').textContent=patches.length;$('unsupported-count').textContent=state.unsupported;$('create-candidate').disabled=!patches.length||state.changeSet?.status!=='DRAFT';$('clear-changes').disabled=!patches.length||state.changeSet?.status!=='DRAFT';$('highlight-toggle').disabled=!patches.length;const root=$('patch-list');root.innerHTML='';if(!patches.length)root.innerHTML='<p class="empty">아직 변경이 없습니다.</p>';patches.forEach((p,i)=>{const el=document.createElement('article');el.className='patch';const h=document.createElement('div');h.className='patch-head';const title=document.createElement('strong');title.textContent=`${i+1}. ${p.sourceObjectId} · ${names[p.viewerProperty]}`;const buttons=document.createElement('span'),edit=document.createElement('button'),del=document.createElement('button');edit.textContent='수정';del.textContent='삭제';edit.onclick=()=>editPatch(p);del.onclick=()=>deletePatch(p.patchId);buttons.append(edit,del);h.append(title,buttons);const values=document.createElement('div');values.className='patch-values';const before=document.createElement('code'),arrow=document.createElement('span'),after=document.createElement('code');before.textContent=fmt(p.before);arrow.textContent='→';after.textContent=fmt(p.after);values.append(before,arrow,after);el.append(h,values);root.append(el)});renderCompare();applyHighlights()}
  async function deletePatch(id){try{const d=await api(`/api/change-sets/${state.changeSet.changeSetId}/patches/${id}`,{method:'DELETE'});state.changeSet=d.changeSet;if(state.source)fillEditor();renderPatches();status('Patch를 삭제했습니다.')}catch(e){status(e.message,true)}}
  async function editPatch(p){const input=prompt(`${names[p.viewerProperty]} 새 값`,String(p.after));if(input===null)return;let after=input;if(defs[p.viewerProperty].type==='number')after=Number(input);if(defs[p.viewerProperty].type==='boolean')after=/^(true|표시|1)$/i.test(input);try{const d=await api(`/api/change-sets/${state.changeSet.changeSetId}/patches/${p.patchId}`,{method:'PUT',body:JSON.stringify({after})});state.changeSet=d.changeSet;if(state.source)fillEditor();renderPatches();status('Patch를 수정했습니다.')}catch(e){status(e.message,true)}}
  $('clear-changes').onclick=async()=>{try{const d=await api(`/api/change-sets/${state.changeSet.changeSetId}/patches`,{method:'DELETE'});state.changeSet=d.changeSet;state.highlight=false;if(state.source)fillEditor();renderPatches();status('모든 변경을 취소했습니다.')}catch(e){status(e.message,true)}};
  function renderCompare(){const root=$('compare-list');root.innerHTML='';(state.changeSet?.patches||[]).forEach((p,i)=>{const el=document.createElement('div');el.className='compare-item';for(const text of [`${i+1}. ${p.sourceObjectId}`,names[p.viewerProperty],fmt(p.before),'→',fmt(p.after)]){const node=document.createElement('code');node.textContent=text;el.append(node)}root.append(el)})}
  $('create-candidate').onclick=async()=>{status('모든 Patch를 검증하고 후보를 생성 중입니다.');$('create-candidate').disabled=true;try{const d=await api(`/api/change-sets/${state.changeSet.changeSetId}/candidate`,{method:'POST',body:'{}'});state.candidate=d;state.changeSet=(await api(`/api/change-sets/${state.changeSet.changeSetId}`)).changeSet;$('candidate-tab').disabled=false;$('candidate-info').hidden=false;$('candidate-name').textContent=d.candidateProjectName;$('candidate-status').textContent=d.status;$('delete-candidate').disabled=false;status(`${d.patches.length}개 Patch 원자 적용 완료 (${d.performance.totalCreateMs}ms)`);openCandidate()}catch(e){status(e.message,true);renderPatches()}};
  function setView(view,url){state.view=view;$('viewer').hidden=view==='changes';$('compare-panel').hidden=view!=='changes';if(url)iframe.src=url;for(const id of ['original','candidate','changes'])$(`${id}-tab`).classList.toggle('active',id===view)}
  function openCandidate(){if(state.candidate)setView('candidate',state.candidate.previewUrl)}$('candidate-tab').onclick=openCandidate;$('original-tab').onclick=()=>setView('original',originalUrl);$('changes-tab').onclick=()=>setView('changes');
  function verifyCandidate(){try{const objects=state.inspector?.objectCount||0;status(objects?`후보 렌더 완료 · 객체 ${objects}개 · Patch ${state.changeSet.patches.length}건`:'후보 렌더 확인 대기 중')}catch(_){status('후보 렌더 확인 실패',true)}}
  $('delete-candidate').onclick=async()=>{try{await api(`/api/candidates/${state.candidate.candidateId}`,{method:'DELETE'});$('candidate-status').textContent='DELETED';status('후보를 폐기했습니다. 새 Change Set을 준비합니다.');state.candidate=null;state.changeSet=null;$('candidate-tab').disabled=true;$('candidate-info').hidden=true;setView('original',originalUrl);await newChangeSet()}catch(e){status(e.message,true)}};
  async function saveDirectProperty(key,value){
    if(!state.source||!state.selection||state.changeSet?.status!=='DRAFT')throw new Error('원본 객체 조회가 완료된 뒤 다시 시도하세요.');
    if(!state.source.properties.includes(key))throw new Error(`${names[key]||key} 속성은 이 객체에서 지원되지 않습니다.`);
    const el=$(`prop-${key}`),previous=defs[key].type==='boolean'?el.checked:el.value;
    if(defs[key].type==='boolean')el.checked=Boolean(value);else el.value=String(value);
    applyPreview();
    try{
      const body=patchBody(key),existing=state.changeSet.patches.find(p=>p.sourceObjectId===body.sourceObjectId&&p.viewerProperty===key);let d;
      if(Object.is(body.before,body.after)){if(!existing)return;d=await api(`/api/change-sets/${state.changeSet.changeSetId}/patches/${existing.patchId}`,{method:'DELETE'})}
      else d=await api(`/api/change-sets/${state.changeSet.changeSetId}/patches`,{method:'POST',body:JSON.stringify(body)});
      state.changeSet=d.changeSet;renderPatches();fillEditor();status(`${names[key]} 직접 편집 저장 완료`)
    }catch(e){if(defs[key].type==='boolean')el.checked=previous;else el.value=previous;applyPreview();status(e.message,true);throw e}
  }
  async function resetSelectedChanges(){
    if(!state.selection)return;
    for(const patch of [...(state.changeSet?.patches||[])].filter(p=>p.sourceObjectId===state.selection.sourceObjectId)){const d=await api(`/api/change-sets/${state.changeSet.changeSetId}/patches/${patch.patchId}`,{method:'DELETE'});state.changeSet=d.changeSet}
    const position=positionPatch(state.selection);if(position)await resetRenderPatch(position);if(state.source)fillEditor();renderPatches();status('선택 객체의 모든 변경을 초기화했습니다.')
  }
  const directBridge={
    property:(key,value)=>saveDirectProperty(key,value),
    resize:async({before,after})=>{try{if(Math.round(before.width)!==Math.round(after.width))await saveDirectProperty('width',Math.round(after.width));if(Math.round(before.height)!==Math.round(after.height))await saveDirectProperty('height',Math.round(after.height))}catch(_){}},
    action:async action=>{try{if(action==='resetSize'){await saveDirectProperty('width',state.source.values.width);await saveDirectProperty('height',state.source.values.height)}else if(action==='resetPosition'){const patch=positionPatch();if(patch)await resetRenderPatch(patch);else status('저장된 위치 변경이 없습니다.')}else if(action==='hide')await saveDirectProperty('visible',false);else if(action==='resetAll')await resetSelectedChanges()}catch(e){status(e.message,true)}}
  };
  window.mvpDirectBridge=directBridge;
  new MutationObserver(()=>document.querySelectorAll('#patch-list .patch').forEach(card=>{if(card.textContent.includes('표시 여부')&&card.textContent.includes('숨김')){const buttons=card.querySelectorAll('button'),button=buttons[buttons.length-1];if(button&&button.textContent!=='다시 표시')button.textContent='다시 표시'}})).observe($('patch-list'),{childList:true,subtree:true});
  const renderQuery=()=>new URLSearchParams({layoutDraftId:state.layoutDraftId,projectName,formName});
  function positionPatch(render=state.selection){if(!render)return null;return state.renderPatches.find(p=>p.renderInstanceKey===render.renderInstanceKey)||null}
  function positionBefore(render=state.selection){const patch=positionPatch(render);return patch?.before||{left:Number(render?.left),top:Number(render?.top)}}
  const signed=value=>`${value>=0?'+':''}${Math.round(value)}`;
  function updatePositionPanel(before,current){if(!before||!current)return;$('position-before-x').textContent=Math.round(before.left);$('position-before-y').textContent=Math.round(before.top);$('position-current-x').textContent=Math.round(current.left);$('position-current-y').textContent=Math.round(current.top);$('position-delta-x').textContent=signed(current.left-before.left);$('position-delta-y').textContent=signed(current.top-before.top)}
  async function loadRenderPatches(){try{const d=await api(`/api/render-patches?${renderQuery()}`);state.renderPatches=d.patches;renderPositionPatches();if(state.review)applyRenderPositions(true)}finally{state.renderPatchesReady=true;attach()}}
  function recordRenderResult(result){api('/api/render-patches/events',{method:'POST',body:JSON.stringify({event:`RENDER_PATCH_${result.status}`,patchId:result.patch.patchId,reason:result.reason})}).catch(()=>{})}
  function applyRenderPositions(record=false){if(!state.review){restoreRenderPositions();return[]}const results=state.inspector?.setRenderPositions(state.renderPatches)||[];if(record)results.forEach(recordRenderResult);const skipped=results.filter(x=>x.status==='SKIPPED');if(skipped.length)status(`저장된 위치 변경 ${skipped.length}건을 현재 문서에서 찾지 못했습니다.`,true);return results}
  function renderPositionPatches(){const root=$('render-patch-list');root.innerHTML='';$('clear-render-patches').disabled=!state.renderPatches.length;if(!state.renderPatches.length){root.innerHTML='<p class="empty">저장된 위치 변경이 없습니다.</p>';return}for(const patch of state.renderPatches){const el=document.createElement('article');el.className='render-patch';el.dataset.renderInstanceKey=patch.renderInstanceKey;const title=document.createElement('strong');title.textContent=`[렌더 위치 #${patch.renderIndex}] ${patch.viewerObjectId}`;const value=document.createElement('span');value.textContent=`(${Math.round(patch.before.left)}, ${Math.round(patch.before.top)}) → (${Math.round(patch.after.left)}, ${Math.round(patch.after.top)})`;const button=document.createElement('button');button.textContent='위치 초기화';button.onclick=()=>resetRenderPatch(patch);el.append(title,value,button);root.append(el)}}
  function positionBody(object,before,after){const renderIndex=iframe.contentWindow.canvasModule.getCanvas(0).getObjects().indexOf(object),parsed=MvpViewerInspector.parseViewerObjectId(object.id),bandKey=parsed.bandId||'FREEFORM',snapshot=state.selection?.renderInstanceKey===`p0|c0|src:${parsed.sourceObjectId}|band:${bandKey}|row:${parsed.rowIndex}|idx:${renderIndex}`?state.selection.originalFingerprint:{left:Number(before.left),top:Number(before.top),width:Number(object.width),height:Number(object.height)};return{layoutDraftId:state.layoutDraftId,projectName,formName,pageIndex:0,canvasIndex:0,renderIndex,renderInstanceKey:`p0|c0|src:${parsed.sourceObjectId}|band:${bandKey}|row:${parsed.rowIndex}|idx:${renderIndex}`,viewerObjectId:object.id,sourceObjectId:parsed.sourceObjectId,bandId:parsed.bandId,rowIndex:parsed.rowIndex,className:object.className,originalFingerprint:snapshot,before:{left:Number(before.left),top:Number(before.top)},after:{left:Number(after.left),top:Number(after.top)}}}
  async function saveRenderedPosition(object,before,after){if(before.left===after.left&&before.top===after.top)return;const body=positionBody(object,before,after);try{const d=await api('/api/render-patches/position',{method:'PUT',body:JSON.stringify(body)});const index=state.renderPatches.findIndex(p=>p.patchId===d.patch.patchId);if(index>=0)state.renderPatches[index]=d.patch;else state.renderPatches.push(d.patch);renderPositionPatches();updatePositionPanel(d.patch.before,d.patch.after);status('위치 변경 저장 완료')}catch(e){state.inspector?.setPosition(object.id,before,false,{...body,after});updatePositionPanel(positionBefore(),before);status(`${e.message} · 드래그 전 위치로 복구했습니다.`,true)}}
  const moveCallbacks={start:({object,left,top})=>updatePositionPanel(positionBefore({viewerObjectId:object.id,left,top}),{left,top}),moving:({object,left,top})=>updatePositionPanel(positionBefore({viewerObjectId:object.id,left,top}),{left,top}),end:({object,before,after})=>saveRenderedPosition(object,before,after)};
  function configureMoveMode(){state.inspector?.setMoveMode(state.review&&window.MvpWorkspaceMode?.directEdit?.()!==false,moveCallbacks)}
  // Leaving direct-edit turns off Viewer editing interaction and drops the UI selection; edits stay rendered.
  window.addEventListener('mvp:workspace-mode',event=>{configureMoveMode();if(event.detail.leavingDirectEdit)window.dispatchEvent(new CustomEvent('mvp:clear-object-selection'))});
  async function resetRenderPatch(patch){try{const d=await api(`/api/render-patches/${patch.patchId}?${renderQuery()}`,{method:'DELETE'});state.inspector?.setPosition(patch.viewerObjectId,patch.before,true,patch);state.renderPatches=state.renderPatches.filter(p=>p.patchId!==patch.patchId);renderPositionPatches();if(positionPatch(state.selection)?.patchId===patch.patchId)updatePositionPanel(patch.before,patch.before);status('위치를 원본 렌더 위치로 복구했습니다.')}catch(e){state.inspector?.setPosition(patch.viewerObjectId,patch.after,false,patch);status(e.message,true)}}
  $('clear-render-patches').onclick=async()=>{const previous=[...state.renderPatches];try{await api(`/api/render-patches?${renderQuery()}`,{method:'DELETE'});for(const patch of previous)state.inspector?.setPosition(patch.viewerObjectId,patch.before,true,patch);state.renderPatches=[];renderPositionPatches();if(state.selection){const before=positionBefore();updatePositionPanel(before,before)}status('모든 위치 변경을 초기화했습니다.')}catch(e){for(const patch of previous)state.inspector?.setPosition(patch.viewerObjectId,patch.after,false,patch);status(e.message,true)}};
  let keyMove=null,keyTimer=null;function handlePositionKey(event){if(!state.review||!(window.MvpWorkspaceMode?.directEdit?.()!==false)||['INPUT','TEXTAREA','SELECT'].includes(event.target?.tagName)||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();const step=event.shiftKey?10:1,dx=event.key==='ArrowLeft'?-step:event.key==='ArrowRight'?step:0,dy=event.key==='ArrowUp'?-step:event.key==='ArrowDown'?step:0,result=state.inspector?.nudge(dx,dy);if(!result)return;if(!keyMove||keyMove.object.id!==result.object.id)keyMove={object:result.object,before:result.before,after:result.after};else keyMove.after=result.after;updatePositionPanel(positionBefore({viewerObjectId:result.object.id,...result.before}),result.after);clearTimeout(keyTimer);keyTimer=setTimeout(()=>{const pending=keyMove;keyMove=null;saveRenderedPosition(pending.object,pending.before,pending.after)},250)}document.addEventListener('keydown',handlePositionKey);
  $('highlight-toggle').onclick=()=>{state.highlight=!state.highlight;$('highlight-toggle').classList.toggle('on',state.highlight);applyHighlights()};function applyHighlights(){state.inspector?.setChangedHighlights((state.changeSet?.patches||[]).map(x=>x.sourceObjectId),state.highlight)}
  window.addEventListener('mvp:clear-object-selection',()=>{state.inspector?.clearSelection?.();state.selection=null;state.source=null;for(const id of ['viewer-id','source-id','band-id','row-index','class-name','source-class','position-confidence'])$(id).textContent='—';for(const key of Object.keys(defs))$(`prop-${key}`).disabled=true;$('add-changes').disabled=true;$('reset-object').disabled=true;$('selection-help').textContent='행·열·표 중 하나를 선택했습니다.';$('selection-help').className='';});
  window.mvpHistoryBridge={refresh:async()=>{if(state.changeSet)state.changeSet=(await api(`/api/change-sets/${state.changeSet.changeSetId}`)).changeSet;const d=await api(`/api/render-patches?${renderQuery()}`);state.renderPatches=d.patches;if(state.source)fillEditor();renderPatches();renderPositionPatches();applyPreview();await Promise.all([window.__mvp51?.loadOps?.(),window.__mvp52rows?.loadOps?.(),window.__mvp53?.sync?.(),window.__mvp12?.loadOps?.()]);window.__mvp57?.render?.();return{changeSetId:state.changeSet?.changeSetId,sourcePatches:state.changeSet?.patches?.length||0,renderPatches:state.renderPatches.length,structureOperations:window.__mvp12?.operations?.length||window.__mvp51?.operations?.length||0}},getState:()=>({layoutDraftId:state.layoutDraftId,changeSetId:state.changeSet?.changeSetId,sourcePatches:[...(state.changeSet?.patches||[])],renderPatches:[...state.renderPatches]})};
  async function syncReviewMode(){configureMoveMode();applyPreview();await Promise.all([window.__mvp51?.loadOps?.(),window.__mvp52rows?.loadOps?.(),window.__mvp53?.sync?.()]);if(!state.review)iframe.contentDocument?.querySelectorAll?.('.mvp51-overlay,.mvp51-handle,.mvp52-row-overlay,.mvp52-row-handle,.mvp53-overlay,.mvp53-grip,.mvp53-width-handle,.mvp53-placeholder').forEach(x=>x.remove());window.__mvp57?.render?.();$('viewer-state').textContent=state.review?`편집 중 · 저장된 변경 ${state.renderPatches.length+(state.changeSet?.patches?.length||0)}건 적용`:'원본 Viewer · 편집 내용 미적용'}
  $('review-toggle').onclick=async()=>{state.review=!state.review;$('review-toggle').setAttribute('aria-pressed',state.review);$('review-toggle').textContent=state.review?'편집 끝내기':'편집 시작';if(state.inspector)await syncReviewMode();else attach()};
  Promise.all([newChangeSet(),loadRenderPatches()]).catch(e=>status(e.message,true));
})();
