(function(root,factory){root.DirectEditor=factory()})(typeof window!=='undefined'?window:globalThis,function(){
  const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
  function attach({win,canvas,onProperty,onAction,onSelect,blocked=()=>false}){
    const doc=win.document,style=doc.createElement('style');style.dataset.mvpDirectEditor='true';style.textContent=`
      .mvp44-ui{position:fixed;z-index:2147483000;font-family:Arial,sans-serif;box-sizing:border-box}
      #mvp44-inline{border:2px solid #0878d1;background:#fff;padding:3px 6px;outline:none;box-shadow:0 3px 12px #0003}
      #mvp44-toolbar[hidden],#mvp44-menu[hidden],#mvp44-inline[hidden]{display:none!important}
      #mvp44-toolbar{display:flex;gap:4px;align-items:center;background:#fff;color:#1C2733;padding:4px;border:1px solid #E4E9E6;border-radius:8px;box-shadow:0 6px 16px rgba(16,24,40,.12)}
      #mvp44-toolbar button,#mvp44-toolbar select{font-size:12px;height:28px;border:1px solid transparent;border-radius:6px;background:#fff;color:#1C2733;padding:2px 8px}
      #mvp44-toolbar button:hover{background:#F3FAF6}
      #mvp44-toolbar button.active{background:#E8F5EE;border-color:#B9DFCB;color:#087F52}
      #mvp44-menu{display:grid;min-width:150px;background:#fff;border:1px solid #aab6c5;border-radius:6px;padding:4px;box-shadow:0 5px 18px #0004}
      #mvp44-menu button{border:0;background:#fff;text-align:left;padding:7px;font-size:12px}#mvp44-menu button:hover{background:#e8f2ff}
    `;doc.head.appendChild(style);
    let selected=null,identity=null,inline=null,menu=null,enabled=false;
    const toolbar=doc.createElement('div');toolbar.id='mvp44-toolbar';toolbar.className='mvp44-ui';toolbar.hidden=true;toolbar.innerHTML='<select data-prop="fontSize">'+[8,9,10,11,12,14,16,18,20,24,28,32,36,40,48].map(x=>`<option value="${x}">${x}px</option>`).join('')+'</select><button data-prop="bold" title="굵게"><b>B</b></button><button data-align="left">왼쪽</button><button data-align="center">가운데</button><button data-align="right">오른쪽</button>';doc.body.appendChild(toolbar);
    toolbar.addEventListener('pointerdown',e=>e.stopPropagation());toolbar.addEventListener('mousedown',e=>e.stopPropagation());
    function geometry(object){const el=doc.querySelector('canvas.upper-canvas'),r=el?.getBoundingClientRect();if(!r)return null;const v=canvas.viewportTransform||[1,0,0,1,0,0],sx=r.width/el.width,sy=r.height/el.height;return{left:r.left+object.left*v[0]*sx,top:r.top+object.top*v[3]*sy,width:Math.max(24,object.width*(object.scaleX||1)*v[0]*sx),height:Math.max(20,object.height*(object.scaleY||1)*v[3]*sy),viewport:r}};
    function placeToolbar(){if(!selected||toolbar.hidden)return;const g=geometry(selected);if(!g)return;const width=toolbar.offsetWidth||310,height=toolbar.offsetHeight||38,minTop=g.viewport.top+4,maxTop=Math.min(win.innerHeight-height-4,g.viewport.bottom-height-4);let left=clamp(g.left,g.viewport.left+4,Math.min(win.innerWidth-width-4,g.viewport.right-width-4)),top=g.top-height-6;if(top<minTop)top=g.top+g.height+6;toolbar.style.left=`${left}px`;toolbar.style.top=`${clamp(top,minTop,maxTop)}px`}
    function sync(){if(!selected)return;toolbar.querySelector('[data-prop=fontSize]').value=String(Math.round(selected.fontSize||12));toolbar.querySelector('[data-prop=bold]').classList.toggle('active',selected.fontWeight==='bold'||Number(selected.fontWeight)>=600);toolbar.querySelectorAll('[data-align]').forEach(b=>b.classList.toggle('active',b.dataset.align===(selected.textAlign||'left')));placeToolbar()}
    function select(object,key){selected=object;identity=key;toolbar.dataset.renderInstanceKey=key||'';toolbar.title=key?`Render Instance Key: ${key}`:'';toolbar.hidden=!object||object.className==='UBImage';closeMenu();sync()}
    async function commit(prop,value){if(!selected)return;await onProperty(prop,value,selected,identity);sync()}
    toolbar.querySelector('[data-prop=fontSize]').onchange=e=>commit('fontSize',Number(e.target.value));toolbar.querySelector('[data-prop=bold]').onclick=()=>commit('fontWeight',selected.fontWeight==='bold'||Number(selected.fontWeight)>=600?'normal':'bold');toolbar.querySelectorAll('[data-align]').forEach(b=>b.onclick=()=>commit('textAlign',b.dataset.align));
    function closeInline(cancel=true){if(!inline)return;if(cancel)inline.remove();inline=null}
    function startInline(object=selected,key=identity){if(!object)return;select(object,key);closeInline();const g=geometry(object);if(!g)return;const input=doc.createElement('input');inline=input;input.id='mvp44-inline';input.className='mvp44-ui';input.value=String(object.text||'').trim();input.style.left=`${g.left}px`;input.style.top=`${g.top}px`;input.style.width=`${g.width}px`;input.style.height=`${Math.max(g.height,30)}px`;input.style.fontSize=`${Math.max(10,object.fontSize||12)}px`;input.style.textAlign=object.textAlign||'left';doc.body.appendChild(input);input.focus();input.select();input.onkeydown=async e=>{if(e.key==='Escape'){e.preventDefault();closeInline();return}if(e.key==='Enter'){e.preventDefault();const value=input.value;input.disabled=true;try{await commit('text',value);closeInline(false);input.remove()}catch(_){input.disabled=false;input.focus()}}};input.onblur=()=>setTimeout(()=>{if(inline===input)closeInline()},0)}
    function closeMenu(){menu?.remove();menu=null}
    function openMenu(event,object,key){select(object,key);closeMenu();menu=doc.createElement('div');menu.id='mvp44-menu';menu.className='mvp44-ui';for(const [label,action]of [['문구 편집','editText'],['크기 초기화','resetSize'],['위치 초기화','resetPosition'],['숨기기','hide'],['모든 변경 초기화','resetAll']]){const b=doc.createElement('button');b.textContent=label;b.dataset.action=action;b.onclick=async()=>{closeMenu();if(action==='editText')startInline(object,key);else await onAction(action,object,key)};menu.appendChild(b)}doc.body.appendChild(menu);menu.style.left=`${clamp(event.clientX,4,win.innerWidth-160)}px`;menu.style.top=`${clamp(event.clientY,4,win.innerHeight-menu.offsetHeight-4)}px`}
    const dbl=e=>{if(!enabled)return;const object=canvas.findTarget?.(e);if(object&&!blocked(object)){e.preventDefault();const key=onSelect(object);startInline(object,key)}};
    const context=e=>{if(!enabled)return;const object=canvas.findTarget?.(e);if(object&&!blocked(object)){e.preventDefault();e.stopPropagation();const key=onSelect(object);openMenu(e,object,key)}};
    const upper=doc.querySelector('canvas.upper-canvas');upper?.addEventListener('dblclick',dbl,true);upper?.addEventListener('contextmenu',context,true);win.addEventListener('resize',placeToolbar);doc.addEventListener('scroll',placeToolbar,true);doc.addEventListener('mousedown',e=>{if(menu&&!menu.contains(e.target))closeMenu()},true);
    function clear(){selected=null;identity=null;toolbar.hidden=true;toolbar.dataset.renderInstanceKey='';closeInline();closeMenu()}
    return{select,sync,startInline,openMenu,clear,setEnabled(value){enabled=Boolean(value);if(!enabled)clear();else if(selected){toolbar.hidden=selected.className==='UBImage';sync()}},detach(){upper?.removeEventListener('dblclick',dbl,true);upper?.removeEventListener('contextmenu',context,true);toolbar.remove();style.remove();closeInline();closeMenu();win.removeEventListener('resize',placeToolbar);doc.removeEventListener('scroll',placeToolbar,true)}}
  }
  return{attach};
});
