const test=require('node:test'),assert=require('node:assert/strict');
const analyzer=require('../src/server/ai-builder/json-schema-analyzer');
const resolver=require('../src/server/ai-builder/table-target-resolver');
const matcher=require('../src/server/ai-builder/array-binding-matcher');
const mapper=require('../src/server/ai-builder/array-dataset-mapper');
function table(id,labels){return{id,className:'UBTable',x:10,y:20,width:300,height:50,rowCount:2,columnCount:labels.length,table:[labels.map((text,i)=>({x:i*100,y:0,width:100,height:25,cell:{id:`${id}h${i}`,className:'Cell',text:encodeURIComponent(text)}})),labels.map((_,i)=>({x:i*100,y:25,width:100,height:25,cell:{id:`${id}d${i}`,className:'Cell',text:''}}))]}}
const payload={customerName:'ABC상사',items:[{itemName:'상품A',qty:2,unitPrice:10000,amount:20000},{itemName:'상품B',qty:null,unitPrice:15000,amount:45000}],totalAmount:65000};
test('ai_builder_mvp04_array_analyzer extracts object scalar fields deterministically',()=>{const one=analyzer.analyze(payload),two=analyzer.analyze(JSON.stringify(payload)),array=one.arrays[0];assert.deepEqual(one.arrays,two.arrays);assert.equal(array.arrayPath,'$.items');assert.equal(array.itemType,'object');assert.equal(array.itemCount,2);assert.deepEqual(array.itemFields.map(x=>x.path),['$.items[].amount','$.items[].itemName','$.items[].qty','$.items[].unitPrice']);assert.equal(array.itemFields.find(x=>x.key==='qty').type,'number')});
test('ai_builder_mvp04_array_analyzer fail-closes unsupported and empty shapes',()=>{assert.equal(analyzer.analyze({x:[]}).arrays[0].status,'EMPTY_ARRAY_SCHEMA_UNKNOWN');assert.equal(analyzer.analyze({x:[1,2]}).arrays[0].status,'UNSUPPORTED_ARRAY_SHAPE');assert.equal(analyzer.analyze({x:[{nested:[]}]}).arrays[0].status,'UNSUPPORTED_ARRAY_SHAPE');assert.equal(analyzer.analyze({x:[[1]]}).arrays[0].status,'UNSUPPORTED_ARRAY_SHAPE')});
test('ai_builder_mvp04_table_resolver detects stable first-row header',()=>{const parsed={pages:[{items:[table('TB001',['품명','수량','단가','금액']),table('NOHEADER',['',''])]}]},result=resolver.resolve(parsed);assert.equal(result.tables.length,1);assert.equal(result.tables[0].tableId,'TB001');assert.equal(result.tables[0].headerRowIndex,0);assert.deepEqual(result.tables[0].headerCells.map(x=>x.label),['품명','수량','단가','금액'])});
test('ai_builder_mvp04_matcher maps aliases and prevents low-confidence AUTO',()=>{const arrays=analyzer.analyze(payload).arrays,tables=resolver.resolve({pages:[{items:[table('TB001',['품명','수량','단가','금액']),table('TB002',['A','B','C','D'])]}]}).tables,result=matcher.match(tables,arrays),good=result.proposals.find(x=>x.tableId==='TB001');assert.equal(good.status,'AUTO');assert.deepEqual(good.columns.map(x=>x.jsonPath),['$.items[].itemName','$.items[].qty','$.items[].unitPrice','$.items[].amount']);assert.equal(good.columns.filter(x=>x.status==='AUTO').length,4);assert.ok(!result.proposals.some(x=>x.tableId==='TB002'&&x.status==='AUTO'))});
test('ai_builder_mvp04_mapper builds dynamic rows without flattening',()=>{const array=analyzer.analyze(payload).arrays[0],result=mapper.build(array,payload,['ai_items']);assert.equal(result.dataset.id,'ai_items_2');assert.equal(result.dataset.rows.length,2);assert.equal(result.dataset.rows[1].qty,'');assert.deepEqual(mapper.build(array,payload,['ai_items']),result)});
