const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const analyzer=require('../src/server/ai-builder/json-schema-analyzer');
const resolver=require('../src/server/ai-builder/binding-target-resolver');
const matcher=require('../src/server/ai-builder/scalar-binding-matcher');
const mapper=require('../src/server/ai-builder/json-dataset-mapper');

test('JSON analyzer supports scalar, nested, null and deferred arrays deterministically',()=>{const raw='{"z":null,"active":true,"applicant":{"name":"홍길동"},"items":[{"qty":2}]}',one=analyzer.analyze(raw),two=analyzer.analyze('{"items":[{"qty":2}],"applicant":{"name":"홍길동"},"active":true,"z":null}');assert.deepEqual(one.nodes,two.nodes);assert.equal(one.nodes.find(x=>x.path==='$.applicant.name').sampleValue,'홍길동');assert.equal(one.nodes.find(x=>x.path==='$.active').type,'boolean');assert.equal(one.nodes.find(x=>x.path==='$.z').type,'null');assert.equal(one.nodes.find(x=>x.path==='$.items[].qty').status,'DEFERRED_ARRAY');assert.equal(one.scalarLeaves.some(x=>x.path.includes('items')),false)});
test('JSON analyzer rejects invalid and oversized input',()=>{assert.throws(()=>analyzer.analyze('{bad'),e=>e.code==='JSON_SCHEMA_ANALYSIS_FAILED');assert.throws(()=>analyzer.analyze(JSON.stringify({x:'x'.repeat(analyzer.MAX_BYTES)})),e=>e.code==='JSON_SCHEMA_ANALYSIS_FAILED')});
test('label and key normalization is deterministic',()=>{assert.equal(matcher.normalizeLabel(' 성 명 : '),'성명');assert.equal(matcher.normalizeLabel('신청 금액(원)'),'신청금액');assert.deepEqual(matcher.tokenize('mobilePhone'),['mobile','phone'])});
test('resolver uses stable table cell identity and detects current binding',()=>{const parsed={pages:[{items:[{id:'T1',className:'UBTable',table:[[{cell:{id:'H1',className:'Cell',text:encodeURIComponent('주소'),x:0,y:0,width:50,height:20}}],[{cell:{id:'V1',className:'Cell',text:'old',x:0,y:20,width:50,height:20,dataType:'1',dataSet:'old',column:'address'}}]]}]}]},out=resolver.resolve(parsed);assert.equal(out.targets.length,1);assert.deepEqual(out.targets[0].currentBinding,{dataType:'1',dataSet:'old',column:'address'});assert.equal(out.targets[0].targetId,'V1');assert.equal(out.targets[0].resolutionMethod,'TABLE_HEADER_FIRST_VALUE_CELL')});
test('resolver fails closed for ambiguous standalone values',()=>{const label={id:'L',className:'UBLabel',text:encodeURIComponent('주소'),x:0,y:0,width:30,height:20},a={id:'A',className:'UBLabel',text:'a',x:40,y:0,width:20,height:20},b={id:'B',className:'UBLabel',text:'b',x:70,y:0,width:20,height:20},out=resolver.resolve({pages:[{items:[label,a,b]}]});assert.equal(out.targets.some(x=>x.label==='주소'),false);assert.equal(out.unresolved.some(x=>x.label==='주소'),true)});
test('matcher handles exact, bilingual aliases, review and unbound without duplicate targets',()=>{const schema=analyzer.analyze({applicantName:'홍길동',mobilePhone:'010',address:'서울',unknownCode:'X'}),targets=[{targetId:'1',label:'이름'},{targetId:'2',label:'핸드폰 번호'},{targetId:'3',label:'주소'},{targetId:'4',label:'의미불명'}],out=matcher.match(targets,schema);assert.equal(out[0].selectedPath,'$.applicantName');assert.equal(out[0].status,'AUTO');assert.equal(out[1].selectedPath,'$.mobilePhone');assert.equal(out[1].status,'AUTO');assert.equal(out[2].selectedPath,'$.address');assert.equal(out[2].status,'AUTO');assert.equal(out[3].status,'UNBOUND');assert.throws(()=>matcher.match([{targetId:'x',label:'주소'},{targetId:'x',label:'이름'}],schema),e=>e.code==='DUPLICATE_BINDING_TARGET')});
test('dataset mapper creates safe nested columns and deterministic collision suffixes',()=>{const schema=analyzer.analyze({applicant:{name:'홍길동'},'applicant.name':'겹침'}),one=mapper.build(schema,['ai_input']),two=mapper.build(schema,['ai_input']);assert.deepEqual(one,two);assert.equal(one.dataset.id,'ai_input_2');assert.deepEqual(one.dataset.rows[0],{applicant__name:'홍길동',applicant__name_2:'겹침'});assert.equal(one.mapping.find(x=>x.jsonPath==='$.applicant.name').column,'applicant__name')});
