const test=require('node:test'),assert=require('node:assert/strict');
const {applySource}=require('../src/server/ai-builder/unified-materializer');
const {parseViewerObjectId}=require('../src/server/utils/viewer-id-parser');

function fixture(){const cell=(id,text,band,binding={})=>({id,className:'Cell',band,text:encodeURIComponent(text),width:210,height:24,fontSize:10,textAlign:'left',visible:true,...binding}),wrap=(cell,x)=>({x,y:0,width:210,height:24,cell:{...cell,x,y:0}});const hb={id:'AIHB0001',className:'UBDataHeaderBand',bandItems:['HT0001']},db={id:'AIDB0001',className:'UBDataBand',bandItems:['DT0001'],dataSet:'ai_items'},h1=cell('HC0001','품명',hb.id),h2=cell('HC0002','수량',hb.id),d1=cell('DC0001','{ai_items.itemName}',db.id,{dataType:'1',dataSet:'ai_items',column:'itemName'}),d2=cell('DC0002','{ai_items.qty}',db.id,{dataType:'1',dataSet:'ai_items',column:'qty'});return{root:{datasets:[{id:'ai_items',columns:[{dataField:'itemName'},{dataField:'qty'}]}]},pages:[{items:[hb,db,{id:'HT0001',className:'UBTable',band:hb.id,x:10,width:420,columnCount:2,rowCount:1,table:[[wrap(h1,0),wrap(h2,210)]]},{id:'DT0001',className:'UBTable',band:db.id,x:10,width:420,columnCount:2,rowCount:1,table:[[wrap(d1,0),wrap(d2,210)]]}]}]}}
test('ai_builder_mvp042 runtime identity resolves stable source/band/row metadata',()=>{assert.deepEqual(parseViewerObjectId('DC0001_AIDB0001_ROW2'),{viewerObjectId:'DC0001_AIDB0001_ROW2',sourceObjectId:'DC0001',bandId:'AIDB0001',rowIndex:2,mappingConfidence:'verified-for-sample'})});
test('ai_builder_mvp042 header text edit preserves detail dataset binding',()=>{const parsed=fixture();applySource(parsed,[{sourceObjectId:'HC0001',operation:'updateText',viewerProperty:'text',before:'품명',after:'상품명'}]);assert.equal(decodeURIComponent(parsed.pages[0].items[2].table[0][0].cell.text),'상품명');const detail=parsed.pages[0].items[3].table[0][0].cell;assert.deepEqual({dataType:detail.dataType,dataSet:detail.dataSet,column:detail.column},{dataType:'1',dataSet:'ai_items',column:'itemName'})});
test('ai_builder_mvp042 width edit synchronizes header/detail and following x geometry',()=>{const parsed=fixture();applySource(parsed,[{sourceObjectId:'DC0001',operation:'updateProperty',viewerProperty:'width',before:210,after:250}]);const [header,detail]=parsed.pages[0].items.slice(2);for(const table of [header,detail]){assert.equal(table.table[0][0].width,250);assert.equal(table.table[0][0].cell.width,250);assert.equal(table.table[0][1].x,250);assert.equal(table.width,460)}assert.equal(detail.table[0][0].cell.column,'itemName')});
test('ai_builder_mvp042 detail style changes template only and keeps binding expression',()=>{const parsed=fixture();applySource(parsed,[{sourceObjectId:'DC0001',operation:'updateProperty',viewerProperty:'fontSize',before:10,after:11},{sourceObjectId:'DC0001',operation:'updateProperty',viewerProperty:'textAlign',before:'left',after:'center'}]);const detail=parsed.pages[0].items[3].table[0][0].cell;assert.equal(detail.fontSize,11);assert.equal(detail.textAlign,'center');assert.equal(decodeURIComponent(detail.text),'{ai_items.itemName}');assert.equal(detail.column,'itemName')});
test('ai_builder_mvp042 ambiguous/missing pair fails closed',()=>{const parsed=fixture();parsed.pages[0].items.splice(2,1);assert.throws(()=>applySource(parsed,[{sourceObjectId:'DC0001',operation:'updateProperty',viewerProperty:'width',before:210,after:250}]),e=>e.code==='DYNAMIC_COLUMN_PAIRING_FAILED')});
