const test=require('node:test'),assert=require('node:assert/strict');
const {server}=require('../src/server/index'),structure=require('../src/server/services/structure-operation-service'),history=require('../src/server/services/history-service');
const draft='mvp59_api_unit',scope={layoutDraftId:draft,projectName:'sample',formName:'sample'};let base;
async function request(path,options={}){const response=await fetch(base+path,{headers:{'content-type':'application/json'},...options}),body=await response.json();return{status:response.status,body}}
test.before(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base=`http://127.0.0.1:${server.address().port}`});
test.beforeEach(()=>{try{structure.clear(scope)}catch(_){}try{history.clear(scope)}catch(_){}});
test.after(async()=>{try{structure.clear(scope)}catch(_){}try{history.clear(scope)}catch(_){}await new Promise(resolve=>server.close(resolve))});
test('capability and registry APIs return canonical metadata',async()=>{const q=new URLSearchParams({draftId:draft,projectName:'sample',formName:'sample',targetType:'LOGICAL_COLUMN',targetKey:'tbl:financial-7col|col:2'}),cap=await request(`/api/capabilities?${q}`),reg=await request('/api/operation-registry');assert.equal(cap.status,200);assert.equal(cap.body.capabilities.resizeColumn.allowed,true);assert.equal(reg.body.operations.find(x=>x.operation==='resizeColumn').maturity,'STABLE')});
test('validation API standardizes failure and does not append history',async()=>{const payload={draftId:draft,projectName:'sample',formName:'sample',targetType:'LOGICAL_COLUMN',target:{logicalColumnKey:'tbl:financial-7col|col:2'},operation:'resizeColumn',payload:{width:73}},r=await request('/api/operations/validate',{method:'POST',body:JSON.stringify(payload)});assert.equal(r.status,409);assert.equal(r.body.code,'TABLE_WIDTH_OVERFLOW');assert.equal(history.get(scope).events.length,0)});
test('legacy direct UX endpoint is server-revalidated before history',async()=>{const before=history.get(scope),r=await request('/api/structure-operations',{method:'PUT',body:JSON.stringify({...scope,logicalTableKey:'tbl:financial-7col',operation:'resizeColumn',columnIndex:2,afterWidth:73})}),after=history.get(scope);assert.equal(r.status,409);assert.equal(r.body.code,'TABLE_WIDTH_OVERFLOW');assert.equal(after.events.length,before.events.length);assert.equal(structure.list(scope).length,0)});
test('validated execute revalidates, mutates once, records history, and restores',async()=>{const target={logicalColumnKey:'tbl:financial-7col|col:6'},payload={draftId:draft,projectName:'sample',formName:'sample',targetType:'LOGICAL_COLUMN',target,operation:'hideColumn',payload:{}},r=await request('/api/operations/execute',{method:'POST',body:JSON.stringify(payload)});assert.equal(r.status,200);assert.equal(r.body.validation.valid,true);assert.equal(structure.list(scope).length,1);assert.equal(history.get(scope).events.length,1);const restored=await request('/api/operations/execute',{method:'POST',body:JSON.stringify({...payload,operation:'restoreColumn'})});assert.equal(restored.status,200);assert.equal(structure.list(scope).length,0);assert.equal(history.get(scope).events.length,2)});
