const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('fs'),os=require('os'),path=require('path'),crypto=require('crypto');
const {validateDim}=require('../src/server/import/dim-validator');
const {readForm}=require('../src/server/services/form-patch-service');
const {createIdContext}=require('../src/server/import/import-label-generator');
const {createImportedTable,validateImportedTable}=require('../src/server/import/import-table-generator');
const project=require('../src/server/import/import-project-service');
const PNG=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wHwAF/gL+XwJXAAAAAElFTkSuQmCC','base64');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function table(cells,rows=2,cols=4){return{id:'merged',type:'table',x:10,y:20,width:cols*50,height:rows*25,columns:Array.from({length:cols},(_,i)=>({id:`c${i}`,width:50})),rows:Array.from({length:rows},(_,r)=>({height:25,cells:cells.filter(c=>(c.row??r)===r)}))}}
function dim(cells,rows,cols){return{version:'1.3',page:{width:794,height:1123},assets:[],elements:[table(cells,rows,cols)]}}
function cells(rows=2,cols=4){return Array.from({length:rows},(_,r)=>Array.from({length:cols},(_,c)=>({row:r,col:c,text:`${r}:${c}`}))).flat()}
function prototype(){return project.analyzeTablePrototype(readForm(project.tablePrototypePaths().form))}
test('DIM 1.3 validates horizontal, vertical and compound master-only merges',()=>{for(const spec of [{row:0,col:0,rowSpan:1,colSpan:4},{row:0,col:0,rowSpan:2,colSpan:1},{row:0,col:0,rowSpan:2,colSpan:3}]){const all=cells().filter(c=>!(c.row<spec.rowSpan&&c.col<spec.colSpan));all.unshift({...spec,text:'master'});const out=validateDim(dim(all));assert.deepEqual(out.elements[0].rows[0].cells[0],{...spec,text:'master'})}});
test('DIM 1.3 merge validator uses stable error codes',()=>{const cases=[['DIM_TABLE_CELL_SPAN_INVALID',[{row:0,col:0,rowSpan:0,colSpan:1,text:'x'}]],['DIM_TABLE_CELL_SPAN_OUT_OF_RANGE',[{row:0,col:3,rowSpan:1,colSpan:2,text:'x'}]],['DIM_TABLE_DUPLICATE_CELL_COORDINATE',[{row:0,col:0,text:'a'},{row:0,col:0,text:'b'}]],['DIM_TABLE_COVERED_CELL_CONFLICT',[{row:0,col:0,rowSpan:1,colSpan:2,text:'a'},{row:0,col:1,text:'b'}]],['DIM_TABLE_CELL_SPAN_OVERLAP',[{row:0,col:1,text:'a'},{row:0,col:0,colSpan:2,text:'b'}]]];for(const[code,value]of cases)assert.throws(()=>validateDim(dim(value)),e=>e.code===code)});
test('generator emits MS/MC physical wrappers and exact compound geometry',()=>{const all=cells().filter(c=>!(c.row<2&&c.col<3));all.unshift({row:0,col:0,rowSpan:2,colSpan:3,text:'master',style:{bold:true,backgroundColor:'#404040'}});const element=validateDim(dim(all)).elements[0],out=createImportedTable({prototype:prototype(),element,idContext:createIdContext(),dimVersion:'1.3'});assert.equal(out.table[0][0].status,'MS');assert.equal(out.table[0][0].width,150);assert.equal(out.table[0][0].height,50);assert.equal(out.table.flat().filter(w=>w.status==='MC').length,5);assert.equal(out.table[0][0].cell.backgroundColor,0x404040);assert.equal(validateImportedTable(out),true)});
test('image manifest validates geometry, mime, missing ref and duplicate id',()=>{const asset={id:'asset1',fileName:'pixel.png',mimeType:'image/png',sha256:sha(PNG),size:PNG.length,relativePath:'pixel.png'},base={version:'1.3',page:{width:794,height:1123},assets:[asset],elements:[{id:'image1',type:'image',x:10,y:10,width:20,height:20,source:{kind:'asset',ref:'asset1'}}]};assert.equal(validateDim(base).elements[0].fit,'contain');for(const [code,mutate] of [['DIM_IMAGE_GEOMETRY_INVALID',x=>x.elements[0].width=0],['DIM_IMAGE_ASSET_NOT_FOUND',x=>x.elements[0].source.ref='missing'],['DIM_IMAGE_MIME_UNSUPPORTED',x=>x.assets[0].mimeType='image/webp'],['DIM_IMAGE_ASSET_INVALID',x=>x.assets.push({...x.assets[0]})]]){const x=structuredClone(base);mutate(x);assert.throws(()=>validateDim(x),e=>e.code===code)}});
test('project atomically publishes image asset and creates parseable UBImage',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'dim13-'));fs.writeFileSync(path.join(root,'pixel.png'),PNG);const input={version:'1.3',page:{width:794,height:1123},assets:[{id:'asset1',fileName:'pixel.png',mimeType:'image/png',sha256:sha(PNG),size:PNG.length,relativePath:'pixel.png'}],elements:[{id:'image1',type:'image',x:10,y:10,width:20,height:20,source:{kind:'asset',ref:'asset1'}}]};const result=project.createImportedProject(input,{assetRoot:root});try{const parsed=readForm(result.formPath),image=parsed.pages[0].items[0];assert.equal(image.className,'UBImage');assert.deepEqual(Buffer.from(decodeURIComponent(image.data),'base64'),PNG);assert.equal(result.assets.length,1);assert.ok(fs.existsSync(path.join(result.root,result.formName,result.assets[0].storedPath)))}finally{project.removeImportedProject(result.projectName);fs.rmSync(root,{recursive:true})}});
test('missing asset and forced publish failure leave no partial project',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'dim13-')),asset={id:'asset1',fileName:'pixel.png',mimeType:'image/png',sha256:sha(PNG),size:PNG.length,relativePath:'pixel.png'},input={version:'1.3',page:{width:794,height:1123},assets:[asset],elements:[{id:'image1',type:'image',x:10,y:10,width:20,height:20,source:{kind:'asset',ref:'asset1'}}]};assert.throws(()=>project.createImportedProject(input,{assetRoot:root}),e=>e.code==='DIM_IMAGE_ASSET_NOT_FOUND');fs.writeFileSync(path.join(root,'pixel.png'),PNG);const name=project.makeImportProjectName(new Date(),'1.3');assert.throws(()=>project.createImportedProject(input,{assetRoot:root,projectName:name,forceFailureAt:'asset-publish'}),e=>e.code==='DIM_IMAGE_PUBLISH_FAILED');assert.equal(fs.existsSync(project.safeProjectPath(name)),false);assert.equal(fs.existsSync(`${project.safeProjectPath(name)}.creating`),false);fs.rmSync(root,{recursive:true})});
