const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {chromium}=require('/home/tjd618/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const base='http://127.0.0.1:3100',project=path.resolve(__dirname,'../../..'),work=path.join(project,'mysuit-mvp-work'),logs=path.join(work,'logs'),shots=path.join(work,'screenshots');
const discovery=JSON.parse(fs.readFileSync(path.join(logs,'mvp50-table-discovery.json'))),model=JSON.parse(fs.readFileSync(path.join(logs,'mvp50-logical-table-model.json'))),main=model.tables[0];fs.mkdirSync(shots,{recursive:true});
const cellMeta=new Map;for(const t of discovery.tables)for(const r of t.rows)for(const c of r.cells)cellMeta.set(c.sourceCellId,{table:t,row:r,cell:c});
async function ready(page){await page.goto(`${base}/?layoutDraftId=layout_sample_mvp50`);await page.waitForFunction(()=>!document.querySelector('#viewer').classList.contains('viewer-loading'));const frame=page.frames().find(f=>f.url().includes('/UView5/index.jsp'));await frame.waitForFunction(()=>canvasModule.getCanvas(0).getObjects().length===180);return frame}
async function runtime(frame){return frame.evaluate(()=>canvasModule.getCanvas(0).getObjects().map((o,renderIndex)=>{const m=/^([A-Za-z][A-Za-z0-9]*)_([A-Za-z][A-Za-z0-9_]{0,119})_ROW(\d+)$/.exec(o.id||'');return{pageIndex:0,canvasIndex:0,renderIndex,renderInstanceKey:m?`p0|c0|src:${m[1]}|band:${m[2]}|row:${Number(m[3])}|idx:${renderIndex}`:null,viewerObjectId:o.id,sourceObjectId:m?.[1]||null,bandId:m?.[2]||null,rowIndex:m?Number(m[3]):null,className:o.className,text:o.text,left:Number(o.left),top:Number(o.top),width:Number(o.width)*(o.scaleX||1),height:Number(o.height)*(o.scaleY||1)}}))}
function build(objects){const mapped=objects.filter(o=>cellMeta.has(o.sourceObjectId)).map(o=>({...o,sourceTableId:cellMeta.get(o.sourceObjectId).table.sourceTableId,sourceBandId:cellMeta.get(o.sourceObjectId).table.bandId,logicalColumnIndex:cellMeta.get(o.sourceObjectId).cell.columnIndex,logicalCellKey:main.cells.find(c=>c.sourceCellId===o.sourceObjectId)?.logicalCellKey||`tbl:${cellMeta.get(o.sourceObjectId).table.sourceTableId}|row:${cellMeta.get(o.sourceObjectId).cell.rowIndex}|col:${cellMeta.get(o.sourceObjectId).cell.columnIndex}|src:${o.sourceObjectId}`}));const mainMapped=mapped.filter(o=>main.sourceTableIds.includes(o.sourceTableId));const columns=main.columns.map(c=>({...c,objects:mainMapped.filter(o=>o.logicalColumnIndex===c.columnIndex).map(o=>o.renderInstanceKey)}));const rows=Object.values(mainMapped.reduce((a,o)=>{const key=`tbl:financial-7col|band:${o.bandId}|rendered-row:${o.rowIndex}`;(a[key]??={rowKey:key,bandId:o.bandId,rowIndex:o.rowIndex,objects:[]}).objects.push(o.renderInstanceKey);return a},{}));return{mapped,columns,rows,signature:crypto.createHash('sha256').update(JSON.stringify({tables:model.tables.map(t=>t.tableKey),columns:columns.map(c=>[c.columnKey,c.objects]),rows:rows.map(r=>[r.rowKey,r.objects]),cells:mainMapped.map(o=>[o.logicalCellKey,o.renderInstanceKey])})).digest('hex')}}
async function outline(frame,keys,color){await frame.evaluate(({keys,color})=>{const c=canvasModule.getCanvas(0),set=new Set(keys),objects=c.getObjects().filter((o,i)=>{const m=/^([A-Za-z][A-Za-z0-9]*)_([A-Za-z][A-Za-z0-9_]{0,119})_ROW(\d+)$/.exec(o.id||'');return m&&set.has(`p0|c0|src:${m[1]}|band:${m[2]}|row:${Number(m[3])}|idx:${i}`)}),ctx=c.contextTop;c.clearContext(ctx);ctx.save();ctx.strokeStyle=color;ctx.lineWidth=5;ctx.setLineDash([10,5]);for(const o of objects){const r=o.getBoundingRect();ctx.strokeRect(r.left-3,r.top-3,r.width+6,r.height+6)}ctx.restore()},{keys,color})}
(async()=>{let browser;try{browser=await chromium.launch({executablePath:'/home/tjd618/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1680,height:1150}}),page=await context.newPage(),frame=await ready(page),objects=await runtime(frame),built=build(objects);
 main.columns.forEach((column,index)=>column.renderInstances=built.columns[index].objects);main.cells.forEach(cell=>cell.renderInstances=built.mapped.filter(o=>o.sourceObjectId===cell.sourceCellId).map(o=>o.renderInstanceKey));fs.writeFileSync(path.join(logs,'mvp50-logical-table-model.json'),JSON.stringify(model,null,2)+'\n');
 fs.writeFileSync(path.join(logs,'mvp50-table-object-mapping.json'),JSON.stringify({objectCount:objects.length,mappedCount:built.mapped.length,renderType:'C',objects:built.mapped},null,2)+'\n');fs.writeFileSync(path.join(logs,'mvp50-column-groups.json'),JSON.stringify(built.columns,null,2)+'\n');fs.writeFileSync(path.join(logs,'mvp50-row-groups.json'),JSON.stringify(built.rows,null,2)+'\n');
 const tableKeys=built.mapped.filter(o=>main.sourceTableIds.includes(o.sourceTableId)).map(o=>o.renderInstanceKey);await outline(frame,tableKeys,'#ff4d00');await page.screenshot({path:path.join(shots,'mvp50-table-detected.png'),fullPage:true});await page.screenshot({path:path.join(shots,'mvp50-table-selected.png'),fullPage:true});await outline(frame,built.columns[2].objects,'#00a6d6');await page.screenshot({path:path.join(shots,'mvp50-column-selected.png'),fullPage:true});const detailRow=built.rows.find(r=>r.objects.length>=7);await outline(frame,detailRow.objects,'#7b2cff');await page.screenshot({path:path.join(shots,'mvp50-row-selected.png'),fullPage:true});
 const samples=[{kind:'initial',signature:built.signature}];for(let i=0;i<5;i++){await page.reload();const f=await readyAfterReload(page);samples.push({kind:'refresh',index:i+1,signature:build(await runtime(f)).signature})}for(let i=0;i<5;i++){const p=await context.newPage(),f=await ready(p);samples.push({kind:'new-context-page',index:i+1,signature:build(await runtime(f)).signature});await p.close()}const stable=samples.every(x=>x.signature===built.signature);fs.writeFileSync(path.join(logs,'mvp50-structure-stability.json'),JSON.stringify({stable,samples,tableCount:model.tables.length,columnCount:main.columns.length,logicalCellCount:main.cells.length,mappedCellInstances:built.mapped.length},null,2)+'\n');if(!stable||built.columns.some(c=>!c.objects.length)||!detailRow)throw new Error('structure assertions failed');console.log(JSON.stringify({success:true,stable,mapped:built.mapped.length,columns:built.columns.map(c=>c.objects.length),rows:built.rows.length,signature:built.signature},null,2));
 }finally{if(browser)await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
async function readyAfterReload(page){await page.waitForFunction(()=>!document.querySelector('#viewer').classList.contains('viewer-loading'));const frame=page.frames().find(f=>f.url().includes('/UView5/index.jsp'));await frame.waitForFunction(()=>canvasModule.getCanvas(0).getObjects().length===180);return frame}
