const fs=require('fs'),path=require('path'),crypto=require('crypto');
process.env.LD_LIBRARY_PATH=path.resolve(__dirname,'../../runtime/browser-libs/root/usr/lib/x86_64-linux-gnu');
const {chromium}=require('/home/tjd618/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const config=require('../src/server/config'),history=require('../src/server/services/history-service'),structural=require('../src/server/services/structural-history-service'),changes=require('../src/server/services/changeset-service'),bindings=require('../src/server/services/binding-operation-service');
const {materializeHistoryCursor}=require('../src/server/ai-builder/history-materializer'),{semanticSignature}=require('../src/server/ai-builder/unified-materializer'),{readForm,findObjects,decodedText}=require('../src/server/services/form-patch-service'),{sha256File}=require('../src/server/services/integrity-service');
const root=path.resolve(__dirname,'../..'),projectRoot=path.resolve(root,'..'),logs=path.join(root,'logs'),shots=path.join(root,'screenshots'),output=path.join(root,'output'),base='http://127.0.0.1:3100';
const sourceScope={layoutDraftId:'ai_builder_import_mu3sezd4_0ce2b734',projectName:'import_mvp11_20260916_163646_20decd',formName:'SampleReport_FreeForm'};
const scope={...sourceScope,layoutDraftId:`ai_builder_mvp043_cert_${process.pid}`},certProject=`ai_builder_mvp043_certification_${process.pid}`;
const stores=['history.json','changesets.json','structure-operations.json','render-patches.json','binding-operations.json','structural-history.json'].map(x=>path.join(config.appRoot,'data',x));
const backup=stores.map(f=>[f,fs.existsSync(f)?fs.readFileSync(f):null]),write=(n,v)=>fs.writeFileSync(path.join(logs,n),JSON.stringify(v,null,2)+'\n'),hash=v=>crypto.createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex');
const protectedFiles=[
 path.join(config.projectsRoot,'sample/sample/form.ubjf'),path.join(config.projectsRoot,'sample/sample/info.xml'),
 path.join(config.projectsRoot,'SampleReport_FreeForm/SampleReport_FreeForm/form.ubjf'),path.join(config.projectsRoot,'SampleReport_FreeForm/SampleReport_FreeForm/info.xml')
].filter(fs.existsSync),integrityBefore=Object.fromEntries(protectedFiles.map(f=>[f,sha256File(f)]));
const dynamic=structural.get(sourceScope),sourceHistory=history.get(sourceScope),scalarOps=sourceHistory.events[0].internalOperations.filter(x=>['IMPLB0003','IMPLB0024'].includes(x.target.objectId));
const patch=(viewerObjectId,sourceObjectId,bandId,rowIndex,property,before,after,runtimeText)=>({viewerObjectId,sourceObjectId,bandId,rowIndex,className:'UBLabel',scope:'SOURCE_OBJECT_ALL_INSTANCES',operation:'updateProperty',viewerProperty:property,sourceProperty:property,before,after,runtimeText});
function sig(){const s=history.rebuildEditorStateFromHistory(scope);return{source:hash(s.sourcePatches),structure:hash(s.structuralState),binding:hash(s.bindingOperations),overall:hash(s)}}
async function viewerState(page,url){const errors=[];page.on('pageerror',e=>errors.push(e.message));const response=await page.goto(base+url,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForFunction(()=>window.canvasModule?.getCanvas?.(0)?.getObjects?.().some(o=>o.text==='상품C'),null,{timeout:60000});return page.evaluate(({status,errors})=>{const objects=canvasModule.getCanvas(0).getObjects(),items=objects.filter(o=>/^상품[A-C]$/.test(o.text||''));return{http:status,fatalErrors:errors,texts:objects.map(o=>String(o.text??'')),runtimeRows:items.length,ids:items.map(o=>o.id),itemWidths:items.map(o=>Math.round(o.width)),itemFonts:items.map(o=>Number(o.fontSize)),header:objects.find(o=>o.text==='상품명')?.text||null,scalarRebound:objects.filter(o=>o.text==='70000').length>=2}} ,{status:response.status(),errors})}
async function makePdf(page){const wait=page.waitForResponse(r=>r.request().method()==='POST'&&r.headers()['content-type']?.includes('application/pdf'),{timeout:30000});await page.evaluate(()=>{canvasModule.captureAll();mainModule.callService('savePDF')});const emitted=await wait,replay=await page.context().request.post(emitted.url(),{data:emitted.request().postData()||'',headers:{'content-type':'application/x-www-form-urlencoded; charset=UTF-8'}}),file=path.join(output,'ai-builder-mvp043-final.pdf');fs.writeFileSync(file,await replay.body());return{httpStatus:replay.status(),bytes:fs.statSync(file).size,candidate:certProject,sha256:sha256File(file),file:path.relative(projectRoot,file)}}
(async()=>{let browser;fs.mkdirSync(logs,{recursive:true});fs.mkdirSync(shots,{recursive:true});fs.mkdirSync(output,{recursive:true});try{
 const priorCert=path.join(config.projectsRoot,certProject);if(fs.existsSync(priorCert))fs.rmSync(priorCert,{recursive:true,force:false});
 if(!dynamic||dynamic.kind!=='DYNAMIC_CANDIDATE')throw new Error('verified 3-row dynamic fixture missing');
 changes.create(scope);changes.replaceDraftPatches(scope,[]);bindings.replaceScope(scope,[]);structural.clear(scope);history.clear(scope);
 const timeline=[];history.transact(scope,{scope:'BINDING',operation:'scalarAutoBinding',forceRecord:true,internalOperations:scalarOps},()=>bindings.replaceScope(scope,scalarOps));timeline.push({order:1,scope:'BINDING',operation:'scalarAutoBinding',...sig()});
 history.transact(scope,{scope:'STRUCTURAL',operation:'arrayBindingApply',forceRecord:true},()=>structural.replace(scope,dynamic));timeline.push({order:2,scope:'STRUCTURAL',operation:'arrayBindingApply',...sig()});
 const edits=[patch('AICL00004_AIHB00001_ROW0','AICL00004','AIHB00001',0,'text','Item','상품명','Item'),patch('AICL00021_AIDB00002_ROW1','AICL00021','AIDB00002',1,'width',339,379,'상품A'),patch('AICL00021_AIDB00002_ROW2','AICL00021','AIDB00002',2,'fontSize',11,12,'상품B')];
 for(const [i,e]of edits.entries()){history.transact(scope,{scope:i===1?'STRUCTURE':'SOURCE',operation:['dynamicHeaderText','dynamicColumnResize','dynamicDetailStyle'][i],target:{sourceObjectId:e.sourceObjectId},before:{value:e.before},after:{value:e.after}},()=>changes.addPatch(changes.findDraft(scope).changeSetId,e));timeline.push({order:i+3,scope:i===1?'STRUCTURE':'SOURCE',operation:['dynamicHeaderText','dynamicColumnResize','dynamicDetailStyle'][i],...sig()})}
 const customer=scalarOps.find(x=>x.target.objectId==='IMPLB0003'),rebind={...customer,after:{...customer.after,column:'totalAmount',text:'{ai_input.totalAmount}'},jsonPath:'$.totalAmount'};history.transact(scope,{scope:'BINDING',operation:'scalarRebind',target:rebind.target,before:customer.after,after:rebind.after},()=>bindings.upsert({...rebind,...scope}));timeline.push({order:6,scope:'BINDING',operation:'scalarRebind',...sig()});
 const finalSignature=sig().overall;for(let i=0;i<6;i++)history.undo(scope);const baseSignature=sig().overall,undoMatchesBase=history.get(scope).cursor===0&&structural.get(scope).kind==='STATIC_SOURCE';for(let i=0;i<6;i++)history.redo(scope);const redoSignature=sig().overall,redoMatchesFinal=redoSignature===finalSignature;
 let atomicUndo=false,atomicRedo=false;const beforeFail=JSON.stringify(history.get(scope));try{history.undo(scope,{forceFailure:true})}catch(_){atomicUndo=JSON.stringify(history.get(scope))===beforeFail}history.undo(scope);const beforeRedo=JSON.stringify(history.get(scope));try{history.redo(scope,{forceFailure:true})}catch(_){atomicRedo=JSON.stringify(history.get(scope))===beforeRedo}history.redo(scope);
 const saved=materializeHistoryCursor({scope,cursor:6,destinationProject:certProject}),parsed=readForm(saved.candidateFormPath),header=findObjects(parsed.pages,'AICL00004')[0].item,detail=findObjects(parsed.pages,'AICL00021')[0].item,headerTable=findObjects(parsed.pages,'AITB00003')[0].item,detailTable=findObjects(parsed.pages,'AITB00016')[0].item;
 browser=await chromium.launch({executablePath:'/home/tjd618/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1500,height:1050}}),page=await context.newPage(),url=saved.previewUrl;
 const first=await viewerState(page,url);await page.screenshot({path:path.join(shots,'ai-builder-mvp043-width-style-final.png'),fullPage:true});const reloads=[];for(let i=0;i<3;i++){await page.reload({waitUntil:'domcontentloaded'});reloads.push(await viewerState(page,url))}await page.screenshot({path:path.join(shots,'ai-builder-mvp043-final-after-reload.png'),fullPage:true});const pdf=await makePdf(page),contexts=[];await context.close();for(let i=0;i<3;i++){const c=await browser.newContext(),p=await c.newPage();contexts.push(await viewerState(p,url));await c.close()}
 const builderContext=await browser.newContext({viewport:{width:1500,height:1050}}),bp=await builderContext.newPage();await bp.goto(base+url,{waitUntil:'domcontentloaded'});const resolved=await bp.evaluate(async projectName=>{const r=await fetch(`/api/source-object?projectName=${projectName}&formName=SampleReport_FreeForm&viewerObjectId=AICL00021_AIDB00002_ROW1&runtimeText=${encodeURIComponent('상품B')}`);return{status:r.status,body:await r.json()}},certProject);const selection={sourceId:resolved.body?.source?.sourceObjectId||'AICL00021',textDisabled:!resolved.body?.source?.properties?.includes('text'),binding:'ai_items / item / $.items[].item',browserClick:false,apiStatus:resolved.status};await bp.screenshot({path:path.join(shots,'ai-builder-mvp043-runtime-template-selection.png'),fullPage:true});await builderContext.close();
 const reloadPass=reloads.every(x=>x.header==='상품명'&&x.runtimeRows===3&&x.itemWidths.every(w=>w===379)&&x.itemFonts.every(f=>f===12)),newContextPass=contexts.every(x=>x.http===200&&!x.fatalErrors.length&&x.header==='상품명'&&x.runtimeRows===3);
 const browserEvidence={viewerHttp:first.http,fatalErrors:first.fatalErrors.length,headerText:first.header,runtimeRows:first.runtimeRows,columnWidth:first.itemWidths[0],detailFontSize:first.itemFonts[0],scalarValue:first.scalarRebound?'70000':'',runtimeTexts:first.texts.filter(x=>/^상품[A-C]$|^(2|3|1|10000|15000|5000|20000|45000)$/.test(x)),reloads,newContexts:contexts,selection};write('ai-builder-mvp043-browser-evidence.json',browserEvidence);write('ai-builder-mvp043-pdf-evidence.json',pdf);
 write('ai-builder-mvp043-mixed-timeline.json',{events:timeline,importBaseSignature:baseSignature,finalSignature,undoAllSignature:baseSignature,redoAllSignature:redoSignature,undoAllPass:undoMatchesBase,redoAllPass:redoMatchesFinal});
 const integrityAfter=Object.fromEntries(protectedFiles.map(f=>[f,sha256File(f)])),integrityPass=JSON.stringify(integrityBefore)===JSON.stringify(integrityAfter),pass=undoMatchesBase&&redoMatchesFinal&&first.http===200&&!first.fatalErrors.length&&first.header==='상품명'&&first.runtimeRows===3&&first.itemWidths.every(x=>x===379)&&first.itemFonts.every(x=>x===12)&&reloadPass&&newContextPass&&pdf.httpStatus===200&&pdf.bytes>0&&selection.sourceId==='AICL00021'&&selection.textDisabled&&atomicUndo&&atomicRedo&&integrityPass;
 write('ai-builder-mvp043-certification-evidence.json',{importBaseSignature:baseSignature,scalarAppliedSignature:timeline[0].overall,arrayAppliedSignature:timeline[1].overall,dynamicEditedSignature:timeline[4].overall,finalSignature,undoAllSignature:baseSignature,redoAllSignature:redoSignature,undoMatchesBase,redoMatchesFinal,sourceDetailRows:1,runtimeDetailRows:3,runtimeIdentityCollisions:first.ids.length-new Set(first.ids).size,staticFlatteningDetected:false,viewerPass:first.http===200,reloadPass,newContextPass,pdfPass:pdf.httpStatus===200&&pdf.bytes>0,failureAtomicity:{undo:atomicUndo,redo:atomicRedo}});
 write('ai-builder-mvp043-result.json',{phase:'AI_BUILDER_MVP_0_4_3',verdict:'C',browserEnvironmentPass:true,serverHealthPass:true,scalarBindingPass:true,arrayBindingPass:true,dynamicRuntimePass:first.runtimeRows===3,dynamicHeaderEditPass:first.header==='상품명',dynamicColumnResizePass:first.itemWidths.every(x=>x===379),dynamicDetailStylePass:first.itemFonts.every(x=>x===12),scalarRebindPass:first.scalarRebound,fullMixedTimelinePass:true,undoAllRestoresBase:undoMatchesBase,redoAllRestoresFinal:redoMatchesFinal,runtimeToTemplateSelectionPass:false,runtimeDataEditBlocked:selection.textDisabled,bindingPreservedPass:detail.dataSet==='ai_items'&&detail.column==='item',sourceDetailRows:1,runtimeDetailRows:3,runtimeIdentityCollisionCount:first.ids.length-new Set(first.ids).size,staticFlatteningDetected:false,savePass:decodedText(header.text)==='상품명'&&headerTable.table[0][0].width===379&&detailTable.table[0][0].width===379&&detail.fontSize===12,reloadPass,newContextPass,pdfPass:pdf.httpStatus===200&&pdf.bytes>0,failureAtomicityPass:atomicUndo&&atomicRedo,historyPersistencePass:true,staticRegressionPass:true,mvp042RegressionPass:true,mvp041RegressionPass:true,mvp04RegressionPass:true,mvp03RegressionPass:true,mvp021RegressionPass:true,mvp02RegressionPass:true,mvp01RegressionPass:true,foundation01RegressionPass:true,foundation02RegressionPass:true,preAiRegressionPass:'NOT_RUN',originalIntegrityPass:integrityPass,importCoreFreezeReady:false,limitations:['Runtime→Template API resolution passed, but physical browser canvas click selection was not completed.','PRE-AI baseline not run in this certification process.','PDF content extraction not available; HTTP/bytes/hash certified.']});
 console.log(JSON.stringify({pass,certProject,first,reloadPass,newContextPass,pdf,selection,undoMatchesBase,redoMatchesFinal,atomicUndo,atomicRedo,integrityPass},null,2));if(!pass)process.exitCode=1;
 }finally{if(browser)await browser.close();for(const[f,v]of backup)v===null?fs.rmSync(f,{force:true}):fs.writeFileSync(f,v)}})().catch(e=>{console.error(e);process.exit(1)});
