const fs=require('fs'),path=require('path');
process.env.LD_LIBRARY_PATH='/home/tjd618/mysuit-ai-viewer/mysuit-mvp-work/runtime/browser-libs/root/usr/lib/x86_64-linux-gnu';
const {chromium}=require('/home/tjd618/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const importer=require('../src/server/import/import-project-service'),config=require('../src/server/config');
const base='http://127.0.0.1:3100',draft=`editing_ui_${process.pid}`,shots=path.resolve(__dirname,'../../screenshots');let browser,savedProject;
async function clickObject(page,predicate){return page.evaluate(predicate=>{const frame=document.querySelector('#viewer'),w=frame.contentWindow,c=w.canvasModule.getCanvas(0),target=c.getObjects().find(object=>Function('object',`return (${predicate})(object)`)(object));if(!target)return null;const canvas=w.document.querySelector('canvas.upper-canvas')||[...w.document.querySelectorAll('canvas')].at(-1),r=target.getBoundingRect(),screen=canvas.getBoundingClientRect(),x=screen.left+(r.left+r.width/2)*(screen.width/canvas.width),y=screen.top+(r.top+r.height/2)*(screen.height/canvas.height),event={bubbles:true,clientX:x,clientY:y,button:0};canvas.dispatchEvent(new w.MouseEvent('mousedown',event));canvas.dispatchEvent(new w.MouseEvent('mouseup',event));return{id:target.id,className:target.className}},predicate.toString())}
(async()=>{try{
  fs.mkdirSync(shots,{recursive:true});browser=await chromium.launch({executablePath:'/home/tjd618/.cache/ms-playwright/chromium-1223/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(`${base}/ai-builder?projectName=sample&layoutDraftId=${draft}`,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('#viewer')?.contentWindow?.canvasModule?.getCanvas?.(0)?.getObjects?.().length===180&&window.aiBuilder&&!document.querySelector('#viewer').classList.contains('viewer-loading'),{timeout:60000});
  const layout=await page.evaluate(()=>({sidebar:document.querySelector('.ai-sidebar').getBoundingClientRect().width,panel:document.querySelector('main>aside').getBoundingClientRect().width,viewer:document.querySelector('.viewer-pane').getBoundingClientRect().width,iframe:document.querySelector('#viewer').tagName,iframeSrc:document.querySelector('#viewer').src,tabs:[...document.querySelectorAll('.builder-tab')].map(x=>x.textContent),active:document.querySelector('.builder-tab[aria-selected=true]').textContent,topbar:document.querySelector('body>header').getBoundingClientRect().height,toolbarDuplicates:[...document.querySelectorAll('.viewer-pane>nav')].filter(x=>getComputedStyle(x).display!=='none').length}));await page.screenshot({path:path.join(shots,'editing-chat.png')});
  const srcBefore=await page.locator('#viewer').getAttribute('src');await page.click('[data-tab=direct]');await page.evaluate(()=>{const button=document.querySelector('#review-toggle');if(button.getAttribute('aria-pressed')!=='true')button.click()});await page.waitForFunction(()=>document.querySelector('#viewer').contentWindow.document.querySelectorAll('canvas').length>0);const selected=await clickObject(page,object=>object.className==='UBLabel');if(!selected)throw new Error('Selectable text not found');await page.waitForFunction(()=>document.querySelector('#source-id').textContent!=='—');const direct=await page.evaluate(()=>({textVisible:!document.querySelector('#prop-text').disabled,widthVisible:!document.querySelector('#prop-width').disabled,selected:document.querySelector('#context-title').textContent}));await page.screenshot({path:path.join(shots,'editing-direct-text.png')});
  const oldText=await page.locator('#prop-text').inputValue();await page.evaluate(()=>mvpDirectBridge.property('text','Editing UI 검증'));await page.waitForFunction(()=>document.querySelector('#history-cursor').textContent.startsWith('1 / 1'));await page.click('#history-undo');await page.waitForFunction(()=>document.querySelector('#history-cursor').textContent.startsWith('0 / 1'));await page.click('#history-redo');await page.waitForFunction(()=>document.querySelector('#history-cursor').textContent.startsWith('1 / 1'));
  await page.evaluate(()=>{const row=__mvp52rows.rows.find(x=>x.rowRole==='HEADER');__mvp52rows.select(row.logicalRowKey)});await page.waitForFunction(()=>document.querySelector('#builder-inspector').innerText.includes('행 편집'));const rowUi=await page.evaluate(()=>{const text=document.querySelector('#builder-inspector').innerText;return{title:text.includes('행 편집')?'행 편집':'',height:Boolean(document.querySelector('#builder-inspector input[data-key=row-height]')),hide:text.includes('행 숨김')}});await page.screenshot({path:path.join(shots,'editing-direct-row.png')});
  const image=await clickObject(page,object=>object.className==='UBImage');if(image)await page.waitForTimeout(350);const imageUi=image?await page.evaluate(()=>({width:!document.querySelector('#prop-width').disabled,height:!document.querySelector('#prop-height').disabled,left:!document.querySelector('#prop-left').disabled,replace:Boolean([...document.querySelectorAll('button')].find(x=>x.textContent.includes('이미지 교체'))),sourceClass:document.querySelector('#source-class').textContent})):null;await page.screenshot({path:path.join(shots,'editing-direct-image.png')});
  await page.click('[data-tab=binding]');await page.waitForTimeout(300);const srcAfter=await page.locator('#viewer').getAttribute('src');const bindingVisible=await page.locator('#builder-binding-body').isVisible();await page.screenshot({path:path.join(shots,'editing-data-binding.png')});
  await page.click('#builder-save');await page.waitForFunction(()=>document.querySelector('#builder-save-state').textContent==='저장 완료',null,{timeout:30000});savedProject=await page.evaluate(()=>aiBuilder.savedPreview?.match(/projectName=([^&]+)/)?.[1]);
  await page.setViewportSize({width:1920,height:1080});const wide=await page.evaluate(()=>({panel:document.querySelector('main>aside').getBoundingClientRect().width,viewer:document.querySelector('.viewer-pane').getBoundingClientRect().width,height:document.querySelector('main').getBoundingClientRect().height,viewport:innerHeight}));
  const result={layout,direct,selected,rowUi,image,imageUi,tabKeepsViewer:srcBefore===srcAfter,bindingVisible,undoRedo:true,savePass:Boolean(savedProject),wide,errors,oldText,screenshots:['editing-chat.png','editing-direct-text.png','editing-direct-row.png','editing-direct-image.png','editing-data-binding.png']};const pass=layout.sidebar===184&&layout.panel===380&&layout.iframe==='IFRAME'&&layout.tabs.join('|')==='채팅|직접 편집|데이터 연결'&&layout.active==='채팅'&&layout.topbar===52&&layout.toolbarDuplicates===0&&direct.textVisible&&direct.widthVisible&&rowUi.title==='행 편집'&&rowUi.height&&rowUi.hide&&result.tabKeepsViewer&&bindingVisible&&result.savePass&&wide.panel===380&&wide.viewer>layout.viewer&&wide.height===wide.viewport-52&&errors.filter(x=>!x.includes('표시 중인 Viewer canvas')).length===0;if(!pass)throw new Error(JSON.stringify(result));console.log(JSON.stringify(result,null,2));
}finally{if(browser)await browser.close();if(savedProject)try{importer.removeImportedProject(savedProject)}catch(_){}for(const name of['history.json','changesets.json','structure-operations.json','render-patches.json','binding-operations.json']){const file=path.join(config.appRoot,'data',name);if(fs.existsSync(file)){const data=JSON.parse(fs.readFileSync(file,'utf8')),clean=Array.isArray(data)?data.filter(x=>x.layoutDraftId!==draft):data;fs.writeFileSync(file,JSON.stringify(clean,null,2)+'\n')}}}})().catch(error=>{console.error(error);process.exit(1)});
