const fs=require('fs'),path=require('path'),crypto=require('crypto');const {chromium}=require('/home/tjd618/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const base='http://127.0.0.1:3100',draft='layout_sample_mvp52',query=`layoutDraftId=${draft}&projectName=sample&formName=sample`,root=path.resolve(__dirname,'../..'),project=path.resolve(root,'..'),logs=path.join(root,'logs'),shots=path.join(root,'screenshots');fs.mkdirSync(logs,{recursive:true});fs.mkdirSync(shots,{recursive:true});
const form=path.join(project,'apache-tomcat-8.5.78/webapps/MYSUIT/UFile/project/sample/sample/form.ubjf'),info=form.replace('form.ubjf','info.xml'),sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),candidateRoot=path.join(project,'apache-tomcat-8.5.78/webapps/MYSUIT/UFile/project'),candidateDirs=()=>fs.readdirSync(candidateRoot).filter(x=>/^sample_mvp4_/.test(x)).sort();
async function ready(page){await page.goto(`${base}/?layoutDraftId=${draft}`);await page.waitForFunction(()=>window.__mvp51?.columns?.every(x=>x.length===24)&&window.__mvp52rows?.rows?.length===24&&!document.querySelector('#viewer').classList.contains('viewer-loading'));}
async function snapshot(page){return page.evaluate(()=>({column:{order:__mvp51.state().order,widths:__mvp51.state().widths,hidden:__mvp51.state().hidden,counts:__mvp51.columns.map(c=>c.length),ids:__mvp51.columns.map(c=>c.map(x=>x.object.id).sort())},rows:__mvp52rows.rows.map(r=>{const s=__mvp52rows.derived().get(r.logicalRowKey);return{key:r.logicalRowKey,role:r.rowRole,count:r.members.length,top:s.top,height:s.height,hidden:s.hidden}}),ops:__mvp51.operations.map(x=>({operation:x.operation,columnIndex:x.columnIndex,toVisualIndex:x.toVisualIndex,logicalRowKey:x.logicalRowKey,afterWidth:x.afterWidth,afterHeight:x.afterHeight})).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)))}))}
const write=(name,data)=>fs.writeFileSync(path.join(logs,name),JSON.stringify(data,null,2)+'\n');
(async()=>{let browser;const hashesBefore={form:sha(form),info:sha(info)},dirsBefore=candidateDirs();try{await fetch(`${base}/api/structure-operations?${query}`,{method:'DELETE'});browser=await chromium.launch({executablePath:'/home/tjd618/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1680,height:1150}}),page=await context.newPage();await ready(page);await page.click('#review-toggle');const original=await snapshot(page);
 await page.evaluate(()=>__mvp51.select(2));await page.click('#mvp52-left');await page.waitForFunction(()=>JSON.stringify(__mvp51.state().order)==='[0,2,1,3,4,5,6]');const moved=await snapshot(page);await page.screenshot({path:path.join(shots,'mvp52-column-reordered.png'),fullPage:true});
 const boundaryBefore=await page.evaluate(()=>__mvp51.operations.length);await page.evaluate(async()=>{__mvp51.select(0);await __mvp51.saveMove(-1)});const boundary={before:boundaryBefore,after:await page.evaluate(()=>__mvp51.operations.length),message:await page.locator('#mvp51-status').textContent()};
 await page.evaluate(()=>__mvp51.select(2));await page.locator('#mvp51-width').fill('100');await page.click('#mvp51-save-width');await page.waitForFunction(()=>__mvp51.state().widths[2]===100);await page.evaluate(()=>__mvp51.select(4));await page.click('#mvp51-hide');await page.waitForFunction(()=>__mvp51.state().hidden[4]);const columnCombo=await snapshot(page);await page.screenshot({path:path.join(shots,'mvp52-column-reorder-resize-hide.png'),fullPage:true});
 await page.click('#mvp52-row-toggle');const summary='tbl:financial-7col|band:UGHB7543grp_0_dataset_2|rendered-row:0';await page.evaluate(k=>__mvp52rows.select(k),summary);await page.locator('#mvp52-row-height').fill('39');await page.click('#mvp52-row-resize');await page.waitForFunction(k=>__mvp52rows.derived().get(k).height===39,summary);const rowResized=await snapshot(page);await page.screenshot({path:path.join(shots,'mvp52-fixed-row-resized.png'),fullPage:true});
 const group='tbl:financial-7col|band:grp_0_UGHB7543|rendered-row:0';await page.evaluate(k=>__mvp52rows.select(k),group);await page.click('#mvp52-row-hide');await page.waitForFunction(k=>__mvp52rows.derived().get(k).hidden,group);const rowHidden=await snapshot(page);await page.screenshot({path:path.join(shots,'mvp52-fixed-row-hidden.png'),fullPage:true});const hideOp=await page.evaluate(k=>__mvp52rows.operations.find(x=>x.operation==='hideRow'&&x.logicalRowKey===k),group);await fetch(`${base}/api/structure-operations/${hideOp.operationId}?${query}`,{method:'DELETE'});await page.evaluate(()=>Promise.all([__mvp51.loadOps(),__mvp52rows.loadOps()]));await page.waitForFunction(k=>!__mvp52rows.derived().get(k).hidden,group);const rowRestored=await snapshot(page);
 const detail='tbl:financial-7col|band:grp_0_UDB3195|rendered-row:0';await page.evaluate(k=>__mvp52rows.select(k),detail);const dataRowUi={role:await page.evaluate(()=>__mvp52rows.selected.rowRole),resizeDisabled:await page.locator('#mvp52-row-resize').isDisabled(),hideDisabled:await page.locator('#mvp52-row-hide').isDisabled(),message:await page.locator('#mvp52-row-status').textContent()};const rejected=await fetch(`${base}/api/structure-operations`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({layoutDraftId:draft,projectName:'sample',formName:'sample',logicalTableKey:'tbl:financial-7col',operation:'resizeRow',logicalRowKey:detail,afterHeight:40})}).then(async r=>({status:r.status,body:await r.json()}));
 const expected=await snapshot(page),samples=[];for(let i=0;i<5;i++){await page.reload();await page.waitForFunction(()=>window.__mvp51?.columns?.every(x=>x.length===24)&&window.__mvp52rows?.rows?.length===24);samples.push({kind:'refresh',index:i+1,value:await snapshot(page)})}for(let i=0;i<5;i++){const p=await context.newPage();await ready(p);samples.push({kind:'new-context',index:i+1,value:await snapshot(p)});await p.close()}const stable=samples.every(x=>JSON.stringify(x.value)===JSON.stringify(expected));
 const moveOp=await page.evaluate(()=>__mvp51.operations.find(x=>x.operation==='moveColumn'&&x.columnIndex===2));await fetch(`${base}/api/structure-operations/${moveOp.operationId}?${query}`,{method:'DELETE'});await page.evaluate(()=>Promise.all([__mvp51.loadOps(),__mvp52rows.loadOps()]));const afterDelete=await snapshot(page);await page.evaluate(()=>__mvp51.select(2));await page.click('#mvp52-left');await page.waitForFunction(()=>__mvp51.state().order[1]===2);const afterReplay=await snapshot(page);
 const hashesAfter={form:sha(form),info:sha(info)},integrity={hashesBefore,hashesAfter,unchanged:hashesBefore.form===hashesAfter.form&&hashesBefore.info===hashesAfter.info,candidateDirsBefore:dirsBefore,candidateDirsAfter:candidateDirs(),newCandidateDirs:candidateDirs().filter(x=>!dirsBefore.includes(x))};const result={original,moved,columnCombo,boundary,rowResized,rowHidden,rowRestored,dataRowUi,rejected,stable,samples,afterDelete,afterReplay,integrity,rowReorder:{implemented:false,status:'STOPPED_BY_DATA_SEMANTICS',reason:'Rendered Detail 반복 순서와 fixed/data 경계의 안전한 source 의미가 검증되지 않음'}};write('mvp52-column-reorder.json',{original:original.column,moved:moved.column,columnCombo:columnCombo.column,boundary,afterDelete:afterDelete.column,afterReplay:afterReplay.column});write('mvp52-row-editing.json',{rowResized:rowResized.rows,rowHidden:rowHidden.rows,rowRestored:rowRestored.rows,dataRowUi,rejected,rowReorder:result.rowReorder});write('mvp52-structure-replay.json',{stable,samples});write('mvp52-integrity.json',integrity);write('mvp52-e2e-result.json',result);
 const identitiesStable=JSON.stringify(original.column.ids)===JSON.stringify(moved.column.ids);if(!identitiesStable||moved.column.counts.some(x=>x!==24)||boundary.before!==boundary.after||columnCombo.column.widths[2]!==100||!columnCombo.column.hidden[4]||rowResized.rows.find(x=>x.key===summary).height!==39||!rowHidden.rows.find(x=>x.key===group).hidden||rowRestored.rows.find(x=>x.key===group).hidden||dataRowUi.role!=='RENDERED_DETAIL'||!dataRowUi.resizeDisabled||!dataRowUi.hideDisabled||rejected.status!==409||rejected.body.code!=='DATA_ROW_STRUCTURE_EDIT_REJECTED'||!stable||afterDelete.column.order[2]!==2||afterReplay.column.order[1]!==2||!integrity.unchanged||integrity.newCandidateDirs.length)throw new Error('MVP52 assertion failed');console.log(JSON.stringify({success:true,identitiesStable,order:moved.column.order,boundary,rowHeight:39,dataRowRejected:rejected,stable,integrity},null,2));
 }finally{await fetch(`${base}/api/structure-operations?${query}`,{method:'DELETE'}).catch(()=>{});if(browser)await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
