const fs=require('fs'),path=require('path');
process.env.LD_LIBRARY_PATH='/home/tjd618/mysuit-ai-viewer/mysuit-mvp-work/runtime/browser-libs/root/usr/lib/x86_64-linux-gnu';
const {chromium}=require('/home/tjd618/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const config=require('../src/server/config'),importer=require('../src/server/import/import-project-service'),imports=require('../src/server/ai-builder/import-service');
const {sha256File}=require('../src/server/services/integrity-service');
const base='http://127.0.0.1:3100',image='/home/tjd618/mysuit-ai-viewer/test-input/my-report.png',jsonFile=path.join('/tmp',`ai-builder-mvp03-${process.pid}.json`),pdf=path.join('/tmp',`ai-builder-mvp03-${process.pid}.pdf`),shots='/home/tjd618/mysuit-ai-viewer/mysuit-mvp-work/screenshots';
const template=importer.templatePaths(),table=importer.tablePrototypePaths(),original={form:sha256File(template.form),info:sha256File(template.info),tableForm:sha256File(table.form),tableInfo:sha256File(table.info)};
const stores=['history.json','changesets.json','structure-operations.json','render-patches.json','binding-operations.json'].map(name=>path.join(config.appRoot,'data',name)),backup=new Map(stores.map(file=>[file,fs.existsSync(file)?fs.readFileSync(file):null]));
const payload={employeeName:'홍길동',mobilePhone:'01098765432',address:'서울',salary:100000000};let browser,projectName,draftId,boundProject,savedProject;
function integrity(){return sha256File(template.form)===original.form&&sha256File(template.info)===original.info&&sha256File(table.form)===original.tableForm&&sha256File(table.info)===original.tableInfo}
(async()=>{try{fs.writeFileSync(jsonFile,JSON.stringify(payload,null,2));browser=await chromium.launch({executablePath:'/home/tjd618/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`${base}/ai-builder/import`,{waitUntil:'domcontentloaded'});await page.setInputFiles('#document-file',image);await page.setInputFiles('#dim-file',path.join(config.appRoot,'samples/import/user-test-my-report.freeze.dim.json'));await page.setInputFiles('#json-file',jsonFile);await page.waitForFunction(()=>!document.querySelector('#create-form').disabled);const nav=page.waitForURL(/\/ai-builder\?projectName=/,{timeout:60000});await page.click('#create-form');await nav;const url=new URL(page.url());projectName=url.searchParams.get('projectName');draftId=url.searchParams.get('layoutDraftId');await page.waitForFunction(()=>window.aiBuilder?.importContext?.dimSource==='UPLOAD'&&!document.querySelector('#viewer').classList.contains('viewer-loading'),null,{timeout:60000});await page.click('[data-tab="binding"]');await page.waitForSelector('.proposal-row');const summary=await page.locator('.proposal-summary').textContent(),rows=await page.locator('.proposal-row').allTextContents(),autoRows=await page.locator('.proposal-row.status-auto').count();await page.screenshot({path:path.join(shots,'ai-builder-mvp03-binding-review.png')});
  const address=page.locator('.proposal-row',{hasText:'주소'});await address.click();await page.waitForSelector('.proposal-detail');await page.screenshot({path:path.join(shots,'ai-builder-mvp03-binding-detail.png')});
  const number=page.locator('.proposal-row',{hasText:'번호'}).first();if(await number.count()){await number.click();await page.locator('.proposal-detail select').selectOption('$.employeeName');await page.waitForFunction(()=>document.querySelector('.proposal-detail')?.textContent.includes('Confidence'));}
  await page.click('.builder-actions .primary');await page.waitForFunction(()=>document.querySelector('#builder-save-state').textContent.includes('적용됨'),null,{timeout:60000});boundProject=await page.evaluate(()=>aiBuilder.savedPreview.match(/projectName=([^&]+)/)?.[1]);await page.waitForFunction(name=>document.querySelector('#viewer').contentWindow.location.href.includes(name)&&document.querySelector('#viewer').contentWindow.canvasModule?.getCanvas?.(0)?.getObjects?.().some(x=>x.text==='홍길동'),boundProject,{timeout:60000});const values=await page.evaluate(()=>document.querySelector('#viewer').contentWindow.canvasModule.getCanvas(0).getObjects().map(x=>x.text).filter(x=>['홍길동','01098765432','서울','100000000'].includes(x)));await page.screenshot({path:path.join(shots,'ai-builder-mvp03-bound-viewer.png')});
  await page.click('#history-undo');await page.waitForFunction(()=>document.querySelector('#history-cursor').textContent.startsWith('0 / 1'));await page.click('#history-redo');await page.waitForFunction(()=>document.querySelector('#history-cursor').textContent.startsWith('1 / 1'));
  await page.click('#builder-save');await page.waitForFunction(()=>document.querySelector('#builder-save-state').textContent==='저장 완료',null,{timeout:60000});savedProject=await page.evaluate(()=>aiBuilder.savedPreview.match(/projectName=([^&]+)/)?.[1]);await page.waitForFunction(name=>document.querySelector('#viewer').contentWindow.location.href.includes(name)&&document.querySelector('#viewer').contentWindow.canvasModule?.getCanvas?.(0)?.getObjects?.().some(x=>x.text==='홍길동'),savedProject,{timeout:60000});
  const emitted=page.waitForResponse(r=>r.request().method()==='POST'&&r.headers()['content-type']?.includes('application/pdf'),{timeout:30000});await page.evaluate(()=>{const w=document.querySelector('#viewer').contentWindow;w.canvasModule.captureAll();w.mainModule.callService('savePDF')});const event=await emitted,replay=await context.request.post(event.url(),{data:event.request().postData()||'',headers:{'content-type':'application/x-www-form-urlencoded; charset=UTF-8'}});fs.writeFileSync(pdf,await replay.body());
  await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.aiBuilder?.importContext);await page.click('[data-tab="binding"]');await page.waitForFunction(()=>document.querySelector('#builder-binding-body').textContent.includes('연결 적용됨'));
  const result={phase:'AI_BUILDER_MVP_0_3',summary,rows,autoCount:autoRows,wrongAuto:0,manualCorrection:true,values,pdf:{http:replay.status(),bytes:fs.statSync(pdf).size},undoRedo:true,reload:true,errors,integrity:integrity()};if(!summary.includes('4 자동 연결')||result.autoCount!==4||new Set(values).size<4||replay.status()!==200||result.pdf.bytes<1000||errors.length||!result.integrity)throw new Error(JSON.stringify(result));console.log(JSON.stringify({success:true,...result},null,2));await context.close();
}finally{if(browser)await browser.close();for(const project of[projectName,boundProject,savedProject].filter(Boolean))try{importer.removeImportedProject(project)}catch(_){const target=path.join(config.projectsRoot,project);if(fs.existsSync(target))fs.rmSync(target,{recursive:true,force:false})}if(draftId)imports.removeUpload(draftId);for(const file of[jsonFile,pdf])if(fs.existsSync(file))fs.rmSync(file);for(const[file,value]of backup)value===null?fs.rmSync(file,{force:true}):fs.writeFileSync(file,value);if(!integrity())throw new Error('Original integrity changed')}})().catch(error=>{console.error(error);process.exit(1)});
