const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {chromium}=require('/home/tjd618/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const config=require('../src/server/config');
const {materializeUnifiedCandidate}=require('../src/server/ai-builder/unified-materializer');
const {sha256File}=require('../src/server/services/integrity-service');
const base='http://127.0.0.1:3100',baseProject='import_mvp11_20260827_170551_e59e1d',baseForm='SampleReport_FreeForm';
const destinationProject=`foundation01_e2e_${process.pid}_${crypto.randomBytes(3).toString('hex')}`,destination=path.join(config.projectsRoot,destinationProject),pdf=path.join('/tmp',`${destinationProject}.pdf`);
const sourceForm=path.join(config.projectsRoot,baseProject,baseForm,'form.ubjf'),sourceInfo=path.join(config.projectsRoot,baseProject,baseForm,'info.xml'),before={form:sha256File(sourceForm),info:sha256File(sourceInfo)};
async function inspect(page){await page.waitForFunction(()=>{const objects=canvasModule?.getCanvas?.(0)?.getObjects?.()||[],by=id=>objects.find(x=>x.id===id);return by('IMPLB0001')?.text==='AI Builder 통합 보고서'&&by('IMPLB0002')?.text==='홍길동'&&Math.round(by('IMPCL0002')?.width)===225;},null,{timeout:60000});return page.evaluate(()=>{const objects=canvasModule.getCanvas(0).getObjects(),by=id=>objects.find(x=>x.id===id);return{title:by('IMPLB0001')?.text,bound:by('IMPLB0002')?.text,columnWidth:by('IMPCL0002')?.width,objectCount:objects.length};});}
(async()=>{let browser;try{const materialized=materializeUnifiedCandidate({baseProject,baseForm,destinationProject,sourcePatches:[{operation:'updateText',target:{objectId:'IMPLB0001'},before:{text:'월간 실적 보고서'},after:{text:'AI Builder 통합 보고서'}}],structureOperations:[{operation:'resizeColumn',sourceTableId:'IMPTB0001',columnIndex:1,afterWidth:225}],datasets:[{id:'ai_builder_test',columns:['applicantName'],rows:[{applicantName:'홍길동'}]}],bindingOperations:[{operation:'bindField',target:{objectId:'IMPLB0002'},after:{dataType:'1',dataSet:'ai_builder_test',column:'applicantName'}}]});browser=await chromium.launch({executablePath:'/home/tjd618/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});const results=[],errors=[];for(let i=0;i<5;i++){const context=await browser.newContext({viewport:{width:1280,height:1000}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));const response=await page.goto(`${base}${materialized.previewUrl}`,{waitUntil:'domcontentloaded',timeout:30000});const state=await inspect(page);results.push({http:response.status(),...state});if(i===0){const observed=page.waitForResponse(r=>r.request().method()==='POST'&&r.headers()['content-type']?.includes('application/pdf'),{timeout:30000});await page.evaluate(()=>{canvasModule.captureAll();mainModule.callService('savePDF')});const emitted=await observed,replay=await context.request.post(emitted.url(),{data:emitted.request().postData()||'',headers:{'content-type':'application/x-www-form-urlencoded; charset=UTF-8'}});fs.writeFileSync(pdf,await replay.body());results[0].pdf={http:replay.status(),bytes:fs.statSync(pdf).size};}await context.close();}const expected=results.every(x=>x.http===200&&x.title==='AI Builder 통합 보고서'&&x.bound==='홍길동'&&Math.round(x.columnWidth)===225);if(!expected||errors.length||results[0].pdf.http!==200||results[0].pdf.bytes<=0)throw new Error(JSON.stringify({results,errors}));console.log(JSON.stringify({success:true,materialized:{operationCounts:materialized.operationCounts,signature:materialized.signature},contexts:results,errors,integrity:{form:sha256File(sourceForm)===before.form,info:sha256File(sourceInfo)===before.info}},null,2));}finally{if(browser)await browser.close();if(fs.existsSync(destination))fs.rmSync(destination,{recursive:true,force:false});if(fs.existsSync(pdf))fs.rmSync(pdf);if(sha256File(sourceForm)!==before.form||sha256File(sourceInfo)!==before.info)throw new Error('Original integrity changed');}})().catch(e=>{console.error(e);process.exit(1)});
