const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {chromium}=require('/home/tjd618/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const adapter=require('../src/server/services/ubjf-add-remove-adapter'),{removeCandidate}=require('../src/server/services/project-copy-service'),{readForm}=require('../src/server/services/form-patch-service');
const work=path.resolve(__dirname,'../..'),project=path.resolve(work,'..'),logs=path.join(work,'logs'),output=path.join(work,'output'),shots=path.join(work,'screenshots'),source=path.join(project,'apache-tomcat-8.5.78/webapps/MYSUIT/UFile/project/sample/sample/form.ubjf'),info=source.replace('form.ubjf','info.xml');for(const d of[logs,output,shots])fs.mkdirSync(d,{recursive:true});
const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),write=(n,v)=>fs.writeFileSync(path.join(logs,n),JSON.stringify(v,null,2)+'\n'),created=[];
async function load(page,name,shot){await page.goto(`http://127.0.0.1:3100/mysuit/UView5/index.jsp?projectName=${name}&formName=sample`,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.canvasModule?.getCanvas?.(0)?.getObjects?.().length>0,{timeout:30000});await page.waitForTimeout(1500);const state=await page.evaluate(()=>{const c=canvasModule.getCanvas(0),o=c.getObjects(),cells=o.filter(x=>String(x.id||'').startsWith('UB'));c.renderAll();return{objectCount:o.length,cellCount:cells.length,canvasWidth:c.width,maxRight:Math.max(...cells.map(x=>(x.left||0)+(x.width||0)*(x.scaleX||1))),ids:cells.map(x=>x.id),texts:cells.map(x=>{try{return decodeURIComponent(x.text||'')}catch{return x.text||''}})}});await page.waitForTimeout(150);if(shot)await page.screenshot({path:path.join(shots,shot),fullPage:true});return state}
async function pdf(page,file){const responsePromise=page.waitForResponse(r=>r.request().method()==='POST'&&r.headers()['content-type']?.includes('application/pdf'),{timeout:30000});await page.evaluate(()=>{canvasModule.captureAll();mainModule.callService('savePDF')});const response=await responsePromise,request=response.request(),copy=await page.context().request.post(response.url(),{data:request.postData()||'',headers:{'content-type':'application/x-www-form-urlencoded; charset=UTF-8'}}),target=path.join(output,file);fs.writeFileSync(target,await copy.body());return{file:path.relative(work,target),bytes:fs.statSync(target).size,sha256:sha(target),status:copy.status(),contentType:copy.headers()['content-type']}}
(async()=>{let browser;const projectsRoot=path.dirname(path.dirname(path.dirname(source))),originalHash={form:sha(source),info:sha(info)},beforeDirs=new Set(fs.readdirSync(projectsRoot).filter(x=>x.startsWith('sample_'))),results={},pdfs={};try{
  const parsed=readForm(source),geometry=adapter.pageGeometry(parsed);write('mvp55-page-geometry.json',geometry);
  let overflow;const temp=path.join('/tmp',`mvp55-overflow-${process.pid}.ubjf`);fs.copyFileSync(source,temp);try{adapter.applyAddRemoveOperationsToUbjf({sourceFormPath:source,candidateFormPath:temp,operations:[{operation:'addStaticColumn',width:20,headerText:'초과'}]})}catch(e){overflow={blocked:true,code:e.code,currentWidth:e.currentWidth,requestedWidth:e.requestedWidth,maxWidth:e.maxWidth,message:e.message}}finally{fs.rmSync(temp,{force:true})}write('mvp55-width-guard.json',{geometry,overflow});
  const specs={addcol:[{operation:'resizeColumn',columnIndex:0,afterWidth:340},{operation:'addStaticColumn',insertIndex:7,width:30,headerText:'비고'}],removecol:[{operation:'removeColumn',columnIndex:6}],addrow:[{operation:'addStaticRow',bandId:'UDHB4114',height:20,label:'검수 메모'}],removerow:[{operation:'addStaticRow',bandId:'UDHB4114',height:20,label:'삭제 예정'},{operation:'removeStaticRow',bandId:'UDHB4114',rowIndex:1}],boundcol:[{operation:'resizeColumn',columnIndex:0,afterWidth:320},{operation:'addBoundColumn',insertIndex:7,width:50,headerText:'2018 복제',dataSet:'dataset_2',column:'col_8'}]};
  for(const [variant,operations]of Object.entries(specs)){const c=adapter.createCandidate({operations,variant});created.push(c.candidateProjectName);results[variant]={candidate:c.candidateProjectName,operations,result:c.result,sourceTables:adapter.sourceTables(readForm(c.candidateForm)).map(t=>({id:t.id,band:t.band,rowCount:t.rowCount,columnCount:t.columnCount,width:t.width,height:t.height,cellIds:t.table.flat().map(w=>w.cell.id)}))}}
  browser=await chromium.launch({executablePath:'/home/tjd618/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1500,height:1050}});
  results.originalViewer=await load(page,'sample');pdfs.original=await pdf(page,'mvp55-original.pdf');
  const shotMap={addcol:'mvp55-add-column-preview.png',removecol:'mvp55-remove-column.png',addrow:'mvp55-add-row.png'};
  for(const variant of Object.keys(specs)){results[variant].viewer=await load(page,results[variant].candidate,shotMap[variant]);pdfs[variant]=await pdf(page,variant==='removerow'?'mvp55-remove-row.pdf':variant==='removecol'?'mvp55-remove-column.pdf':variant==='addrow'?'mvp55-add-row.pdf':variant==='boundcol'?'mvp55-bound-column.pdf':'mvp55-add-column.pdf')}
  await load(page,results.addcol.candidate,'mvp55-add-column-source.png');
  write('mvp55-add-static-column.json',results.addcol);write('mvp55-remove-column.json',results.removecol);write('mvp55-add-static-row.json',results.addrow);write('mvp55-remove-static-row.json',results.removerow);write('mvp55-add-bound-column.json',results.boundcol);write('mvp55-source-validation.json',Object.fromEntries(Object.entries(results).filter(([k])=>k!=='originalViewer').map(([k,v])=>[k,v.result?.validation])));write('mvp55-pdf-results.json',pdfs);
  const assertions={addColumn:results.addcol.viewer.objectCount>results.originalViewer.objectCount&&results.addcol.viewer.texts.includes('비고'),removeColumn:results.removecol.viewer.objectCount<results.originalViewer.objectCount,addRow:results.addrow.viewer.objectCount>results.originalViewer.objectCount&&results.addrow.viewer.texts.includes('검수 메모'),removeRow:results.removerow.viewer.objectCount===results.originalViewer.objectCount,boundColumn:results.boundcol.viewer.objectCount>results.originalViewer.objectCount,widthGuard:overflow?.code==='TABLE_WIDTH_OVERFLOW'&&results.addcol.viewer.maxRight<=geometry.usableRight+1,pdfs:Object.values(pdfs).every(x=>x.status===200&&x.bytes>1000&&/pdf/i.test(x.contentType||''))};write('mvp55-regression.json',{assertions,viewer:Object.fromEntries(Object.entries(results).map(([k,v])=>[k,v.viewer||v]))});const integrity={originalBefore:originalHash,originalAfter:{form:sha(source),info:sha(info)},unchanged:originalHash.form===sha(source)&&originalHash.info===sha(info),existingCandidatesPreserved:[...beforeDirs].every(x=>fs.existsSync(path.join(projectsRoot,x)))};write('mvp55-integrity.json',integrity);if(!Object.values(assertions).every(Boolean)||!integrity.unchanged||!integrity.existingCandidatesPreserved)throw new Error(`MVP55 assertion failed ${JSON.stringify(assertions)}`);console.log(JSON.stringify({success:true,assertions,integrity,pdfs,viewer:Object.fromEntries(Object.entries(results).filter(([k])=>k!=='originalViewer').map(([k,v])=>[k,v.viewer]))},null,2));
}finally{if(browser)await browser.close();for(const name of created)try{removeCandidate(name)}catch(e){console.error('cleanup',name,e.message)}}})().catch(e=>{console.error(e);process.exitCode=1});
