const fs=require('fs'),path=require('path');
process.env.LD_LIBRARY_PATH='/home/tjd618/mysuit-ai-viewer/mysuit-mvp-work/runtime/browser-libs/root/usr/lib/x86_64-linux-gnu';
const {chromium}=require('/home/tjd618/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const importer=require('../src/server/import/import-project-service'),imports=require('../src/server/ai-builder/import-service');
const base='http://127.0.0.1:3100',root=path.resolve(__dirname,'../..'),shots=path.join(root,'screenshots');
const image=path.join(root,'../test-input/my-report.png'),dim=path.join(__dirname,'../samples/import/user-test-my-report.freeze.dim.json');
const hwpx=fs.readdirSync(path.join(root,'uploads/ai-builder')).map(name=>path.join(root,'uploads/ai-builder',name,'__.hwpx')).find(fs.existsSync);
const created=[];let browser;
function remember(value){if(value?.projectName)created.push({projectName:value.projectName,draftId:value.draftId});return value}
(async()=>{try{
  if(!hwpx)throw new Error('HWPX browser fixture not found');fs.mkdirSync(shots,{recursive:true});
  browser=await chromium.launch({executablePath:'/home/tjd618/.cache/ms-playwright/chromium-1223/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});
  const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),pageErrors=[];page.on('pageerror',error=>pageErrors.push(error.message));
  const response=await page.goto(`${base}/ai-builder/import`,{waitUntil:'networkidle'});await page.screenshot({path:path.join(shots,'ai-builder-ui-upload-empty.png'),fullPage:true});
  await page.setInputFiles('#document-file',hwpx);await page.waitForFunction(()=>aiBuilderImport.state==='READY');await page.screenshot({path:path.join(shots,'ai-builder-ui-upload-hwpx-selected.png'),fullPage:true});
  const ui={title:await page.locator('h1').textContent(),sidebar:await page.locator('.ai-sidebar').isVisible(),button:await page.locator('#create-form').isEnabled(),dimHidden:await page.locator('#advanced').isHidden(),dataSummary:await page.locator('#summary-json').textContent(),jsonOptional:await page.locator('#json-title').textContent()};
  await page.setInputFiles('#document-file',{name:'legacy.hwp',mimeType:'application/octet-stream',buffer:Buffer.from('legacy')});const hwpMessage=await page.locator('#document-error').textContent(),importPageErrors=[...pageErrors];
  await page.setInputFiles('#document-file',hwpx);await page.waitForFunction(()=>aiBuilderImport.state==='READY');await page.route('**/api/ai-builder/import',async route=>{await new Promise(resolve=>setTimeout(resolve,800));await route.continue()},{times:1});const navigation=page.waitForURL(/\/ai-builder\?projectName=.*layoutDraftId=/,{timeout:60000});await page.click('#create-form');await page.waitForSelector('#job-state:not([hidden])');await page.screenshot({path:path.join(shots,'ai-builder-ui-upload-processing.png'),fullPage:true});await navigation;const importedUrl=new URL(page.url()),projectName=importedUrl.searchParams.get('projectName'),draftId=importedUrl.searchParams.get('layoutDraftId');created.push({projectName,draftId});await page.waitForFunction(()=>document.querySelector('#viewer')?.contentWindow?.canvasModule?.getCanvas?.(0)?.getObjects?.().length>0,null,{timeout:60000});const viewerObjectCount=await page.locator('#viewer').evaluate(frame=>frame.contentWindow.canvasModule.getCanvas(0).getObjects().length),hwpxContext=imports.read(projectName);
  const jsonResult=remember(await context.request.post(`${base}/api/ai-builder/import`,{data:{document:{name:'personnel.hwpx',base64:fs.readFileSync(hwpx).toString('base64')},json:{raw:'{"employee":"홍길동"}',fileName:'employee.json'}}}).then(r=>r.json()));
  const jsonContext=imports.read(jsonResult.projectName);
  const imageResult=remember(await context.request.post(`${base}/api/ai-builder/import`,{data:{document:{name:'my-report.png',base64:fs.readFileSync(image).toString('base64')},dim:{raw:fs.readFileSync(dim,'utf8'),fileName:'analysis.dim.json'}}}).then(r=>r.json()));
  await page.goto(`${base}/ai-builder/import`,{waitUntil:'domcontentloaded'});await page.setInputFiles('#document-file',image);await page.waitForFunction(()=>!document.querySelector('#create-form').disabled);await page.route('**/api/ai-builder/import',route=>route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({success:false,message:'파일이 손상되었습니다.'})}),{times:1});await page.click('#create-form');await page.waitForSelector('#form-error-wrap:not([hidden])');await page.screenshot({path:path.join(shots,'ai-builder-ui-upload-error.png'),fullPage:true});
  await page.setViewportSize({width:1024,height:900});await page.reload();const responsive={sidebarWidth:await page.locator('.ai-sidebar').evaluate(node=>node.getBoundingClientRect().width),infoVisible:await page.locator('.info-panel').isVisible()};
  const result={phase:'AI_BUILDER_UPLOAD_UI_PRODUCTIZATION',httpStatus:response.status(),ui,hwpBlocked:hwpMessage.includes('HWPX 형식'),hwpxPipeline:hwpxContext.dimSource==='HWPX_NATIVE',workspaceRedirect:projectName&&draftId&&importedUrl.pathname==='/ai-builder',viewerPass:viewerObjectCount>0,viewerObjectCount,jsonOptional:jsonContext.json.source==='FILE',imageDimPipeline:imageResult.success===true&&imageResult.context.dimSource==='UPLOAD',responsive,importPageErrors,workspaceWarnings:pageErrors.slice(importPageErrors.length),screenshots:['ai-builder-ui-upload-empty.png','ai-builder-ui-upload-hwpx-selected.png','ai-builder-ui-upload-processing.png','ai-builder-ui-upload-error.png']};
  const checks=[response.status()===200,ui.sidebar,ui.button,ui.dimHidden,ui.dataSummary==='없음',result.hwpBlocked,result.hwpxPipeline,result.workspaceRedirect,result.viewerPass,result.jsonOptional,result.imageDimPipeline,responsive.sidebarWidth===64,importPageErrors.length===0];if(checks.some(value=>!value))throw new Error(JSON.stringify(result));console.log(JSON.stringify(result,null,2));
}finally{if(browser)await browser.close();for(const item of created){try{importer.removeImportedProject(item.projectName)}catch(_){}try{imports.removeUpload(item.draftId)}catch(_){}}}})().catch(error=>{console.error(error);process.exit(1)});
