const fs=require('fs'),path=require('path');
process.env.LD_LIBRARY_PATH='/home/tjd618/mysuit-ai-viewer/mysuit-mvp-work/runtime/browser-libs/root/usr/lib/x86_64-linux-gnu';
const {chromium}=require('/home/tjd618/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const config=require('../src/server/config'),changes=require('../src/server/services/changeset-service'),history=require('../src/server/services/history-service'),binding=require('../src/server/services/binding-operation-service');
const {sha256File}=require('../src/server/services/integrity-service');
const projectName='import_mvp11_20260827_170551_e59e1d',formName='SampleReport_FreeForm',draft=`builder_mvp01_${process.pid}`,base='http://127.0.0.1:3100';
const scope={layoutDraftId:draft,projectName,formName}, sourceRoot=path.join(config.projectsRoot,projectName), sourceForm=path.join(sourceRoot,formName,'form.ubjf'),sourceInfo=path.join(sourceRoot,formName,'info.xml'),before={form:sha256File(sourceForm),info:sha256File(sourceInfo)};
const stores=['history.json','changesets.json','structure-operations.json','render-patches.json','binding-operations.json'].map(name=>path.join(config.appRoot,'data',name)),backup=new Map(stores.map(file=>[file,fs.existsSync(file)?fs.readFileSync(file):null]));
const shots='/home/tjd618/mysuit-ai-viewer/mysuit-mvp-work/screenshots',pdf=path.join('/tmp',`ai-builder-mvp01-${process.pid}.pdf`);let destination=null,browser;
async function ready(page,viewport){await page.setViewportSize(viewport);const response=await page.goto(`${base}/ai-builder?projectName=${projectName}&layoutDraftId=${draft}`,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForFunction(()=>window.aiBuilder&&document.body.classList.contains('ai-builder')&&!document.querySelector('#viewer').classList.contains('viewer-loading'),null,{timeout:60000});return response;}
async function clickSource(page,id){await page.evaluate(sourceId=>{const w=document.querySelector('#viewer').contentWindow,c=w.canvasModule.getCanvas(0),target=c.getObjects().find(x=>x.id===sourceId),r=target.getBoundingRect(),upper=w.document.querySelector('canvas.upper-canvas'),screen=upper.getBoundingClientRect(),x=screen.left+(r.left+r.width/2)*(screen.width/upper.width),y=screen.top+(r.top+r.height/2)*(screen.height/upper.height),event={bubbles:true,clientX:x,clientY:y,button:0};upper.dispatchEvent(new w.MouseEvent('mousedown',event));upper.dispatchEvent(new w.MouseEvent('mouseup',event))},id);await page.waitForFunction(sourceId=>document.querySelector('#source-id').textContent===sourceId,id)}
(async()=>{try{
  history.clear(scope);binding.clear(scope);const existing=changes.findDraft(scope);if(existing)changes.clearPatches(existing.changeSetId);
  browser=await chromium.launch({executablePath:'/home/tjd618/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});
  const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
  const response=await ready(page,{width:1440,height:900});await page.click('[data-tab="direct"]');await clickSource(page,'IMPLB0001');
  const selected=await page.evaluate(()=>({id:aiBuilder.selectedObjectId,type:document.querySelector('#source-class').textContent,viewerSrc:document.querySelector('#viewer').src,fields:[...document.querySelectorAll('#property-editor .field:not([hidden]) label')].map(x=>x.textContent.trim())}));
  await page.evaluate(()=>mvpDirectBridge.property('text','AI Builder MVP 0.1 보고서'));await page.waitForFunction(()=>document.querySelector('#history-cursor').textContent.startsWith('1 / 1'));
  const text=await page.evaluate(()=>document.querySelector('#viewer').contentWindow.canvasModule.getCanvas(0).getObjects().find(x=>x.id==='IMPLB0001').text);
  // This static imported fixture intentionally has zero datasets. The binding panel must
  // represent that contract instead of inventing a selectable dataset (legacy test debt).
  await clickSource(page,'IMPLB0002');await page.click('[data-tab="binding"]');await page.waitForFunction(()=>document.querySelector('#builder-binding-body').textContent.includes('데이터 연결 없음'));
  const bindingState=await page.locator('#builder-binding-body').textContent();
  await page.click('[data-tab="direct"]');await page.evaluate(()=>window.__mvp12.selectColumn(1));const width='#builder-inspector [data-structure=column] input[type=number]';await page.waitForSelector(width);await page.locator(width).fill('225');await page.locator(width).press('Enter');await page.waitForFunction(()=>document.querySelector('#history-cursor').textContent.startsWith('2 / 2'));
  const srcBefore=await page.locator('#viewer').getAttribute('src');await page.click('[data-action="ai-assistant"]');const srcAi=await page.locator('#viewer').getAttribute('src');await page.click('[data-tab="binding"]');const srcBinding=await page.locator('#viewer').getAttribute('src');await page.click('[data-tab="direct"]');
  await page.click('#history-undo');await page.waitForFunction(()=>document.querySelector('#history-cursor').textContent.startsWith('1 / 2'));await page.click('#history-redo');await page.waitForFunction(()=>document.querySelector('#history-cursor').textContent.startsWith('2 / 2'));
  await page.screenshot({path:path.join(shots,'ai-builder-mvp01-1440x900.png')});await page.setViewportSize({width:1920,height:1080});await page.screenshot({path:path.join(shots,'ai-builder-mvp01-1920x1080.png')});
  await page.click('#builder-save');await page.waitForFunction(()=>document.querySelector('#builder-save-state').textContent==='저장 완료',null,{timeout:30000});destination=await page.evaluate(()=>aiBuilder.savedPreview.match(/projectName=([^&]+)/)?.[1]);await page.waitForFunction(name=>document.querySelector('#viewer').contentWindow.location.href.includes(name)&&document.querySelector('#viewer').contentWindow.canvasModule?.getCanvas?.(0)?.getObjects?.().find(x=>x.id==='IMPLB0001')?.text==='AI Builder MVP 0.1 보고서',destination,{timeout:60000});
  const savedText=await page.evaluate(()=>document.querySelector('#viewer').contentWindow.canvasModule.getCanvas(0).getObjects().find(x=>x.id==='IMPLB0001')?.text);
  const layout=await page.evaluate(()=>({tabs:[...document.querySelectorAll('.builder-tab')].map(x=>x.textContent),grid:getComputedStyle(document.querySelector('main')).gridTemplateColumns,panelOverlay:document.querySelector('main>aside').getBoundingClientRect().left<document.querySelector('.viewer-pane').getBoundingClientRect().right,toolbar:Boolean(document.querySelector('#viewer').contentDocument.querySelector('body'))}));
  const savedStructure=await page.evaluate(()=>Math.round(document.querySelector('#viewer').contentWindow.canvasModule.getCanvas(0).getObjects().find(x=>x.id==='IMPCL0002')?.width||0));
  const emitted=page.waitForResponse(r=>r.request().method()==='POST'&&r.headers()['content-type']?.includes('application/pdf'),{timeout:30000});await page.evaluate(()=>{const win=document.querySelector('#viewer').contentWindow;win.canvasModule.captureAll();win.mainModule.callService('savePDF')});const pdfResponse=await emitted,replay=await context.request.post(pdfResponse.url(),{data:pdfResponse.request().postData()||'',headers:{'content-type':'application/x-www-form-urlencoded; charset=UTF-8'}});fs.writeFileSync(pdf,await replay.body());const pdfResult={http:replay.status(),bytes:fs.statSync(pdf).size};
  const result={phase:'AI_BUILDER_MVP_0_1',http:response.status(),selected,text,savedText,savedStructure,bindingState,tabsPreserveViewer:srcBefore===srcAi&&srcAi===srcBinding,undoRedo:true,pdf:pdfResult,layout,errors,viewports:['1440x900','1920x1080'],integrity:{form:sha256File(sourceForm)===before.form,info:sha256File(sourceInfo)===before.info}};
  if(response.status()!==200||selected.id!=='IMPLB0001'||text!=='AI Builder MVP 0.1 보고서'||savedText!==text||savedStructure!==225||!bindingState.includes('데이터 연결 없음')||pdfResult.http!==200||pdfResult.bytes<1000||!result.tabsPreserveViewer||layout.panelOverlay||errors.length||!result.integrity.form||!result.integrity.info)throw new Error(JSON.stringify(result));
  console.log(JSON.stringify({success:true,...result},null,2));await context.close();
}finally{
  if(browser)await browser.close();if(destination){const target=path.join(config.projectsRoot,destination);if(fs.existsSync(target))fs.rmSync(target,{recursive:true,force:false});}if(fs.existsSync(pdf))fs.rmSync(pdf);
  for(const [file,value] of backup)value===null?fs.rmSync(file,{force:true}):fs.writeFileSync(file,value);
  if(sha256File(sourceForm)!==before.form||sha256File(sourceInfo)!==before.info)throw new Error('Original integrity changed');
}})().catch(error=>{console.error(error);process.exit(1)});
