const fs=require('fs'),path=require('path'),{chromium}=require('/home/tjd618/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const base='http://127.0.0.1:3100',draft='pre_ai_v11_row_pointer',work=path.resolve(__dirname,'../..'),logs=path.join(work,'logs'),shots=path.join(work,'screenshots'),query=`layoutDraftId=${draft}&projectName=sample&formName=sample`;
const write=(name,value)=>fs.writeFileSync(path.join(logs,name),JSON.stringify(value,null,2)+'\n');
(async()=>{let browser;try{
  await fetch(`${base}/api/structure-operations?${query}`,{method:'DELETE'});await fetch(`${base}/api/history?draftId=${draft}&projectName=sample&formName=sample`,{method:'DELETE'});
  browser=await chromium.launch({executablePath:'/home/tjd618/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1800,height:1200}});await page.goto(`${base}/?layoutDraftId=${draft}`);await page.waitForFunction(()=>window.__mvp52rows?.rows?.length===24&&window.__mvp57,{timeout:30000});await page.click('#review-toggle');const vf=page.frames().find(x=>x.url().includes('/UView5/index.jsp')),rowKey=await page.evaluate(()=>__mvp52rows.rows.find(x=>x.rowRole==='SUMMARY').logicalRowKey);await vf.waitForSelector(`.mvp57-row-boundary[data-row-key="${rowKey}"]`);
  await vf.evaluate(key=>{window.__v11Pointer=[];for(const type of['pointerdown','pointermove','pointerup','mousedown','mousemove','mouseup'])document.addEventListener(type,e=>{if(window.__v11Pointer.length>80)return;window.__v11Pointer.push({type,target:e.target?.className||e.target?.tagName,path:e.composedPath().slice(0,7).map(x=>x?.className||x?.id||x?.tagName).filter(Boolean),clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,screenX:e.screenX,screenY:e.screenY,pointerId:e.pointerId,capture:e.target?.hasPointerCapture?.(e.pointerId)||false,rowKey:e.target?.dataset?.rowKey||null})},true)},rowKey);
  const locator=vf.locator(`.mvp57-row-boundary[data-row-key="${rowKey}"]`),box=await locator.boundingBox(),iframeBox=await page.locator('#viewer').boundingBox(),local=await locator.evaluate(e=>{const r=e.getBoundingClientRect(),canvas=document.querySelector('canvas.upper-canvas').getBoundingClientRect(),s=getComputedStyle(e),hit=document.elementFromPoint(r.left+r.width/2,r.top+r.height/2);return{rect:{left:r.left,top:r.top,right:r.right,bottom:r.bottom,width:r.width,height:r.height},canvas:{left:canvas.left,top:canvas.top,right:canvas.right,bottom:canvas.bottom,width:canvas.width,height:canvas.height},hit:{className:hit?.className,rowKey:hit?.dataset?.rowKey},style:{zIndex:s.zIndex,pointerEvents:s.pointerEvents,position:s.position,transform:s.transform},scroll:{x:scrollX,y:scrollY},dpr:devicePixelRatio,zoom:canvasModule.getCanvas(0).getZoom?.(),viewportTransform:canvasModule.getCanvas(0).viewportTransform}}),before=await page.evaluate(k=>({height:__mvp52rows.derived().get(k).height,selected:__mvp52rows.selected?.logicalRowKey,capability:window.mvpCapability?.result,approvalMembers:__mvpApproval.members.map(o=>({id:o.id,left:o.left,top:o.top,width:o.width,height:o.height,bounds:o.getBoundingRect()}))}),rowKey),x=box.x+box.width/2,y=box.y+box.height/2;
  await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x,y+12,{steps:6});await page.screenshot({path:path.join(shots,'pre-ai-v11-row-resizing.png'),fullPage:true});await page.mouse.up();await page.waitForTimeout(600);const after=await page.evaluate(k=>({height:__mvp52rows.derived().get(k).height,lock:__mvp57.lock,operations:__mvp52rows.operations.filter(x=>x.logicalRowKey===k)}),rowKey),events=await vf.evaluate(()=>window.__v11Pointer),debug={rowKey,topCoordinates:{x,y,box},iframeBox,local,before,after,events};write('pre-ai-v11-row-pointer-debug.json',debug);console.log(JSON.stringify(debug,null,2));
}finally{await fetch(`${base}/api/structure-operations?${query}`,{method:'DELETE'}).catch(()=>{});await fetch(`${base}/api/history?draftId=${draft}&projectName=sample&formName=sample`,{method:'DELETE'}).catch(()=>{});if(browser)await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
