const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {chromium}=require('/home/tjd618/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const base='http://127.0.0.1:3100',draft='layout_sample_mvp411',query=`layoutDraftId=${draft}&projectName=sample&formName=sample`;
const root=path.resolve(__dirname,'../..'),logs=path.join(root,'logs'),shots=path.join(root,'screenshots');
fs.mkdirSync(logs,{recursive:true});fs.mkdirSync(shots,{recursive:true});
const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function objects(frame){return frame.evaluate(()=>canvasModule.getCanvas(0).getObjects().map((o,renderIndex)=>({renderIndex,id:o.id,text:o.text,left:Number(o.left),top:Number(o.top),width:Number(o.width),height:Number(o.height),className:o.className,selectable:o.selectable,evented:o.evented,lockX:o.lockMovementX,lockY:o.lockMovementY})))}
async function drag(page,frame,index,dx,dy){const d=await frame.evaluate(index=>{const c=canvasModule.getCanvas(0),o=c.getObjects()[index],el=document.querySelector('canvas.upper-canvas'),r=el.getBoundingClientRect(),v=c.viewportTransform||[1,0,0,1,0,0],sx=r.width/el.width,sy=r.height/el.height;return{before:{left:Number(o.left),top:Number(o.top)},x:r.left+(o.left+o.width/2)*v[0]*sx,y:r.top+(o.top+o.height/2)*v[3]*sy,sx:v[0]*sx,sy:v[3]*sy}},index),box=await page.locator('#viewer').boundingBox();await page.mouse.move(box.x+d.x,box.y+d.y);await page.mouse.down();await page.mouse.move(box.x+d.x+dx*d.sx,box.y+d.y+dy*d.sy,{steps:8});await page.mouse.up();return d.before}
async function position(frame,index){return frame.evaluate(index=>{const o=canvasModule.getCanvas(0).getObjects()[index];return{left:Number(o.left),top:Number(o.top)}},index)}
async function waitPatch(key){for(let i=0;i<50;i++){const d=await fetch(`${base}/api/render-patches?${query}`).then(r=>r.json()),p=d.patches.find(x=>x.renderInstanceKey===key);if(p)return p;await sleep(50)}throw new Error(`patch timeout ${key}`)}
(async()=>{let browser,page,context;const form=path.resolve(root,'../apache-tomcat-8.5.78/webapps/MYSUIT/UFile/project/sample/sample/form.ubjf'),info=form.replace('form.ubjf','info.xml'),hashBefore={form:sha(form),info:sha(info)},requests=[];try{
 await fetch(`${base}/api/render-patches?${query}`,{method:'DELETE'}).catch(()=>{});
 browser=await chromium.launch({executablePath:'/home/tjd618/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});context=await browser.newContext({viewport:{width:1680,height:1150}});page=await context.newPage();page.on('request',r=>{if(r.url().includes('/api/render-patches/position'))requests.push({at:Date.now(),method:r.method(),body:JSON.parse(r.postData()||'{}')})});
 await page.goto(`${base}/?layoutDraftId=${draft}`);await page.waitForFunction(()=>!document.querySelector('#viewer').classList.contains('viewer-loading'));await page.waitForTimeout(300);let frame=page.frames().find(f=>f.url().includes('/UView5/index.jsp'));await frame.waitForFunction(()=>document.querySelector('canvas.upper-canvas')?.getBoundingClientRect().width>0);await page.click('#review-toggle');await frame.waitForFunction(()=>canvasModule.getCanvas(0).getObjects()[0].selectable===true);
 const initial=await objects(frame),title=initial[0],count=initial.length;await page.screenshot({path:path.join(shots,'mvp411-before-drag.png'),fullPage:true});
 const before=await drag(page,frame,0,30,-20);const key='p0|c0|src:LB6417|band:UPHB2584|row:0|idx:0',saved=await waitPatch(key),dragRequestCount=requests.filter(x=>x.body.renderInstanceKey===key).length,stability=[];for(const ms of [0,100,500,1000,2000]){if(ms)await page.waitForTimeout(ms-(stability.at(-1)?.ms||0));stability.push({ms,position:await position(frame,0)})}await page.screenshot({path:path.join(shots,'mvp411-after-drag.png'),fullPage:true});
 const stable=stability.every(x=>Math.abs(x.position.left-saved.after.left)<.01&&Math.abs(x.position.top-saved.after.top)<.01),stoppedBefore=await position(frame,0);await page.mouse.move(20,20);await page.waitForTimeout(150);const stoppedAfter=await position(frame,0);
 fs.writeFileSync(path.join(logs,'mvp411-drag-stability.json'),JSON.stringify({before,saved:saved.after,samples:stability,stable,stopped:JSON.stringify(stoppedBefore)===JSON.stringify(stoppedAfter)},null,2)+'\n');
 await page.reload();const visibleSamples=[];for(let i=0;i<80;i++){const s=await page.evaluate(()=>{const el=document.querySelector('#viewer'),w=el.contentWindow;let o;try{o=w.canvasModule?.getCanvas?.(0)?.getObjects?.()[0]}catch(_){}return{ms:performance.now(),hidden:el.classList.contains('viewer-loading'),position:o?{left:Number(o.left),top:Number(o.top)}:null}});visibleSamples.push(s);if(!s.hidden&&s.position)break;await page.waitForTimeout(25)}frame=page.frames().find(f=>f.url().includes('/UView5/index.jsp'));const refreshed=await position(frame,0);await page.screenshot({path:path.join(shots,'mvp411-after-refresh.png'),fullPage:true});
 const toggles=[];for(let i=0;i<5;i++){await page.click('#review-toggle');await page.waitForTimeout(500);toggles.push({cycle:i+1,state:'on',position:await position(frame,0)});await page.click('#review-toggle');await page.waitForTimeout(500);toggles.push({cycle:i+1,state:'off',position:await position(frame,0)})}fs.writeFileSync(path.join(logs,'mvp411-mode-toggle-result.json'),JSON.stringify({expected:refreshed,toggles,stable:toggles.every(x=>Math.abs(x.position.left-refreshed.left)<.01&&Math.abs(x.position.top-refreshed.top)<.01)},null,2)+'\n');await page.screenshot({path:path.join(shots,'mvp411-mode-toggle.png'),fullPage:true});
 await page.click('#review-toggle');await drag(page,frame,0,0,0);const keyboardBefore=await position(frame,0);for(const keypress of ['ArrowRight','ArrowDown','Shift+ArrowRight','Shift+ArrowUp'])await page.keyboard.press(keypress);await page.waitForTimeout(700);const keyboardAfter=await position(frame,0),keyboardPatch=await waitPatch(key);fs.writeFileSync(path.join(logs,'mvp411-keyboard-result.json'),JSON.stringify({before:keyboardBefore,after:keyboardAfter,expected:{left:keyboardBefore.left+11,top:keyboardBefore.top-9},patchAfter:keyboardPatch.after},null,2)+'\n');
 let failOnce=true;await page.route('**/api/render-patches/position',async route=>{if(failOnce){failOnce=false;return route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({success:false,code:'TEST_SAVE_REJECTED',message:'MVP411 rollback test'})})}return route.continue()});const rollbackBefore=await position(frame,0);await drag(page,frame,0,15,15);await page.waitForTimeout(500);const rollbackAfter=await position(frame,0);await page.unroute('**/api/render-patches/position');fs.writeFileSync(path.join(logs,'mvp411-save-failure-rollback.json'),JSON.stringify({before:rollbackBefore,attempted:{left:rollbackBefore.left+15,top:rollbackBefore.top+15},after:rollbackAfter,restored:Math.abs(rollbackAfter.left-rollbackBefore.left)<.01&&Math.abs(rollbackAfter.top-rollbackBefore.top)<.01},null,2)+'\n');await page.screenshot({path:path.join(shots,'mvp411-save-failure-restored.png'),fullPage:true});
 const aBefore=await position(frame,3),bBefore=await position(frame,4);await drag(page,frame,3,20,-10);const aKey='p0|c0|src:UB5103966|band:UPHB2584|row:0|idx:3',aPatch=await waitPatch(aKey);await page.screenshot({path:path.join(shots,'mvp411-duplicate-a-moved.png'),fullPage:true});await drag(page,frame,4,-15,25);const bKey='p0|c0|src:UB5103966|band:UPHB2584|row:0|idx:4',bPatch=await waitPatch(bKey);await page.screenshot({path:path.join(shots,'mvp411-duplicate-b-moved.png'),fullPage:true});await page.reload();await page.waitForFunction(()=>!document.querySelector('#viewer').classList.contains('viewer-loading'));frame=page.frames().find(f=>f.url().includes('/UView5/index.jsp'));const duplicateReload={a:await position(frame,3),b:await position(frame,4)};await page.locator(`.render-patch[data-render-instance-key="${aKey}"] button`).click();await page.waitForTimeout(300);const duplicateReset={a:await position(frame,3),b:await position(frame,4)};await page.screenshot({path:path.join(shots,'mvp411-duplicate-a-reset.png'),fullPage:true});
 const dragResult={object:{viewerObjectId:title.id,renderIndex:0,text:title.text,className:title.className},before,after:saved.after,requestCount:dragRequestCount,objectCountBefore:count,objectCountAfter:(await objects(frame)).length,refreshed,firstVisible:visibleSamples.find(x=>!x.hidden),unpatchedVisible:visibleSamples.some(x=>!x.hidden&&x.position&&(Math.abs(x.position.left-saved.after.left)>.01||Math.abs(x.position.top-saved.after.top)>.01)),duplicate:{aBefore,bBefore,aPatch:aPatch.after,bPatch:bPatch.after,reload:duplicateReload,reset:duplicateReset}};fs.writeFileSync(path.join(logs,'mvp411-drag-e2e-result.json'),JSON.stringify(dragResult,null,2)+'\n');
 const hashAfter={form:sha(form),info:sha(info)};fs.writeFileSync(path.join(logs,'mvp411-integrity-result.json'),JSON.stringify({hashBefore,hashAfter,unchanged:hashBefore.form===hashAfter.form&&hashBefore.info===hashAfter.info,objectCount:count},null,2)+'\n');
 const ok=stable&&!dragResult.unpatchedVisible&&dragResult.objectCountAfter===count&&duplicateReload.a.left===aPatch.after.left&&duplicateReload.b.left===bPatch.after.left&&duplicateReset.a.left===aBefore.left&&duplicateReset.b.left===bPatch.after.left&&rollbackAfter.left===rollbackBefore.left;if(!ok)throw new Error(`MVP411 assertions failed ${JSON.stringify(dragResult)}`);console.log(JSON.stringify({success:true,dragResult},null,2));
 }finally{await fetch(`${base}/api/render-patches?${query}`,{method:'DELETE'}).catch(()=>{});if(browser)await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
