const fs=require('fs'),path=require('path');
process.env.LD_LIBRARY_PATH='/home/tjd618/mysuit-ai-viewer/mysuit-mvp-work/runtime/browser-libs/root/usr/lib/x86_64-linux-gnu';
const {chromium}=require('/home/tjd618/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const config=require('../src/server/config'),importer=require('../src/server/import/import-project-service'),imports=require('../src/server/ai-builder/import-service');
const {sha256File}=require('../src/server/services/integrity-service');
const base='http://127.0.0.1:3100',image='/home/tjd618/mysuit-ai-viewer/test-input/my-report.png',jsonFile=path.join('/tmp',`ai-builder-mvp02-${process.pid}.json`),pdf=path.join('/tmp',`ai-builder-mvp02-${process.pid}.pdf`),shots='/home/tjd618/mysuit-ai-viewer/mysuit-mvp-work/screenshots';
const template=importer.templatePaths(),table=importer.tablePrototypePaths(),original={form:sha256File(template.form),info:sha256File(template.info),tableForm:sha256File(table.form),tableInfo:sha256File(table.info)};
const stores=['history.json','changesets.json','structure-operations.json','render-patches.json','binding-operations.json'].map(name=>path.join(config.appRoot,'data',name)),backup=new Map(stores.map(file=>[file,fs.existsSync(file)?fs.readFileSync(file):null]));
const payload={applicantName:'홍길동',address:'서울특별시 강남구 테헤란로 123',loanAmount:100000000};let browser,projectName,draftId,savedProject,directProject,directDraft;
function integrity(){return sha256File(template.form)===original.form&&sha256File(template.info)===original.info&&sha256File(table.form)===original.tableForm&&sha256File(table.info)===original.tableInfo}
(async()=>{try{
  fs.writeFileSync(jsonFile,JSON.stringify(payload,null,2));browser=await chromium.launch({executablePath:'/home/tjd618/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  let response=await page.goto(`${base}/ai-builder/import`,{waitUntil:'domcontentloaded'});await page.screenshot({path:path.join(shots,'ai-builder-mvp02-import-entry.png')});await page.evaluate(()=>{const d=document.querySelector('#json-direct');if(d.hidden)document.querySelector('#json-toggle').click()});await page.fill('#json-input','{ invalid');const invalid={buttonDisabled:await page.locator('#create-form').isDisabled(),message:await page.locator('#json-error').textContent()};
  await page.setInputFiles('#document-file',image);await page.setInputFiles('#json-file',jsonFile);await page.waitForFunction(()=>!document.querySelector('#create-form').disabled);await page.route('**/api/ai-builder/import',async route=>{await new Promise(resolve=>setTimeout(resolve,500));await route.continue()},{times:1});const navigation=page.waitForURL(/\/ai-builder\?projectName=/,{timeout:60000});await page.click('#create-form');await page.waitForSelector('#job-state:not([hidden])');await page.screenshot({path:path.join(shots,'ai-builder-mvp02-processing.png')});await navigation;
  const url=new URL(page.url());projectName=url.searchParams.get('projectName');draftId=url.searchParams.get('layoutDraftId');await page.waitForFunction(()=>window.aiBuilder?.importContext&&!document.querySelector('#viewer').classList.contains('viewer-loading'),null,{timeout:60000});const objectCount=await page.evaluate(()=>document.querySelector('#viewer').contentWindow.canvasModule.getCanvas(0).getObjects().length),viewerUrl=await page.locator('#viewer').getAttribute('src');
  await page.click('[data-tab="binding"]');await page.waitForFunction(()=>document.querySelector('#builder-binding-body').querySelector('.data-source strong'));const jsonStatus=await page.locator('#builder-binding-body').textContent(),srcBefore=await page.locator('#viewer').getAttribute('src');await page.click('[data-tab="direct"]');const srcAfter=await page.locator('#viewer').getAttribute('src');
  await page.waitForFunction(()=>document.querySelector('#review-toggle').getAttribute('aria-pressed')==='true');const selectedId=await page.evaluate(()=>{const w=document.querySelector('#viewer').contentWindow,c=w.canvasModule.getCanvas(0),target=c.getObjects().find(x=>x.id==='IMPLB0002'),r=target.getBoundingRect(),upper=w.document.querySelector('canvas.upper-canvas'),screen=upper.getBoundingClientRect(),x=screen.left+(r.left+r.width/2)*(screen.width/upper.width),y=screen.top+(r.top+r.height/2)*(screen.height/upper.height),event={bubbles:true,clientX:x,clientY:y,button:0};upper.dispatchEvent(new w.MouseEvent('mousedown',event));upper.dispatchEvent(new w.MouseEvent('mouseup',event));return target.id});await page.waitForFunction(id=>document.querySelector('#source-id').textContent===id,selectedId);await page.evaluate(()=>mvpDirectBridge.property('text','AI Builder Import 결과'));await page.waitForFunction(()=>document.querySelector('#history-cursor').textContent.startsWith('1 / 1'));
  await page.screenshot({path:path.join(shots,'ai-builder-mvp02-workspace.png')});await page.click('#builder-save');await page.waitForFunction(()=>document.querySelector('#builder-save-state').textContent==='저장 완료',null,{timeout:30000});savedProject=await page.evaluate(()=>aiBuilder.savedPreview.match(/projectName=([^&]+)/)?.[1]);await page.waitForFunction(name=>document.querySelector('#viewer').contentWindow.location.href.includes(name)&&document.querySelector('#viewer').contentWindow.canvasModule?.getCanvas?.(0)?.getObjects?.().some(x=>x.text==='AI Builder Import 결과'),savedProject,{timeout:60000});
  const emitted=page.waitForResponse(r=>r.request().method()==='POST'&&r.headers()['content-type']?.includes('application/pdf'),{timeout:30000});await page.evaluate(()=>{const w=document.querySelector('#viewer').contentWindow;w.canvasModule.captureAll();w.mainModule.callService('savePDF')});const event=await emitted,replay=await context.request.post(event.url(),{data:event.request().postData()||'',headers:{'content-type':'application/x-www-form-urlencoded; charset=UTF-8'}});fs.writeFileSync(pdf,await replay.body());
  const builderUrl=`${base}/ai-builder?projectName=${projectName}&layoutDraftId=${draftId}`;await page.goto(builderUrl,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.aiBuilder?.importContext);const reload=await page.evaluate(()=>aiBuilder.importContext.json);const fresh=await browser.newContext({viewport:{width:1440,height:900}}),freshPage=await fresh.newPage();await freshPage.goto(builderUrl,{waitUntil:'domcontentloaded'});await freshPage.waitForFunction(()=>window.aiBuilder?.importContext);const newContext=await freshPage.evaluate(()=>aiBuilder.importContext.json);await fresh.close();
  const direct=await context.request.post(`${base}/api/ai-builder/import`,{data:{document:{name:'direct.png',base64:fs.readFileSync(image).toString('base64')},json:{raw:JSON.stringify(payload)}}});const directResult=await direct.json();directProject=directResult.projectName;directDraft=directResult.draftId;const directContext=await context.request.get(`${base}/api/ai-builder/context?projectName=${directProject}&formName=SampleReport_FreeForm&layoutDraftId=${directDraft}`).then(r=>r.json());
  const result={success:true,http:response.status(),invalid,projectName,draftId,objectCount,viewerUrl,jsonStatus,tabsPreserveViewer:srcBefore===srcAfter,reload,newContext,directJson:directContext.importContext?.json,pdf:{http:replay.status(),bytes:fs.statSync(pdf).size},errors,integrity:integrity()};if(response.status()!==200||!invalid.buttonDisabled||!invalid.message.includes('올바르지')||objectCount<=0||!jsonStatus.includes(path.basename(jsonFile))||!result.tabsPreserveViewer||reload.source!=='FILE'||newContext.source!=='FILE'||directContext.importContext?.json?.source!=='DIRECT'||result.pdf.http!==200||result.pdf.bytes<1000||errors.length||!result.integrity)throw new Error(JSON.stringify(result));console.log(JSON.stringify(result,null,2));await context.close();
}finally{if(browser)await browser.close();for(const project of [projectName,savedProject,directProject].filter(Boolean))try{importer.removeImportedProject(project)}catch(_){const target=path.join(config.projectsRoot,project);if(fs.existsSync(target))fs.rmSync(target,{recursive:true,force:false})}for(const draft of [draftId,directDraft].filter(Boolean))imports.removeUpload(draft);for(const file of[jsonFile,pdf])if(fs.existsSync(file))fs.rmSync(file);for(const[file,value]of backup)value===null?fs.rmSync(file,{force:true}):fs.writeFileSync(file,value);if(!integrity())throw new Error('Original integrity changed')}})().catch(error=>{console.error(error);process.exit(1)});
