const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {chromium}=require('/home/tjd618/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const base='http://127.0.0.1:3100',draft='layout_sample_mvp44';
const root=path.resolve(__dirname,'../..'),logs=path.join(root,'logs'),shots=path.join(root,'screenshots');fs.mkdirSync(logs,{recursive:true});fs.mkdirSync(shots,{recursive:true});
const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
async function point(frame,index){return frame.evaluate(index=>{const c=canvasModule.getCanvas(0),o=c.getObjects()[index],el=document.querySelector('canvas.upper-canvas'),r=el.getBoundingClientRect(),v=c.viewportTransform||[1,0,0,1,0,0];return{x:r.left+(o.left+o.width/2)*v[0]*r.width/el.width,y:r.top+(o.top+o.height/2)*v[3]*r.height/el.height}},index)}
async function fire(frame,index,type){const p=await point(frame,index);await frame.evaluate(({p,type})=>document.querySelector('canvas.upper-canvas').dispatchEvent(new MouseEvent(type,{bubbles:true,cancelable:true,clientX:p.x,clientY:p.y,button:type==='contextmenu'?2:0})),{p,type})}
async function obj(frame,index){return frame.evaluate(index=>{const o=canvasModule.getCanvas(0).getObjects()[index];return{text:o.text,fontSize:o.fontSize,fontWeight:o.fontWeight,textAlign:o.textAlign,visible:o.visible!==false,width:o.width,height:o.height,scaleX:o.scaleX,scaleY:o.scaleY}},index)}
async function resize(page,frame,index,dx,dy){const p=await point(frame,index),box=await page.locator('#viewer').boundingBox();await page.mouse.move(box.x+p.x,box.y+p.y);await page.mouse.down();await frame.evaluate(({index,dx,dy})=>{const c=canvasModule.getCanvas(0),o=c.getObjects()[index];o.set({scaleX:(o.width+dx)/o.width,scaleY:(o.height+dy)/o.height});o.setCoords();c.fire('object:modified',{target:o})},{index,dx,dy});await page.mouse.up()}
(async()=>{let browser;const form=path.resolve(root,'../apache-tomcat-8.5.78/webapps/MYSUIT/UFile/project/sample/sample/form.ubjf'),info=form.replace('form.ubjf','info.xml'),before={form:sha(form),info:sha(info)};try{
 browser=await chromium.launch({executablePath:'/home/tjd618/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1680,height:1150}});await page.goto(`${base}/?layoutDraftId=${draft}`);await page.waitForFunction(()=>!document.querySelector('#viewer').classList.contains('viewer-loading'));const frame=page.frames().find(f=>f.url().includes('/UView5/index.jsp'));await page.click('#review-toggle');await frame.waitForFunction(()=>canvasModule.getCanvas(0).getObjects()[0].selectable===true);
 await fire(frame,0,'dblclick');await frame.locator('#mvp44-inline').waitFor();await frame.locator('#mvp44-inline').fill('MVP 4.4 직접 편집');await frame.locator('#mvp44-inline').press('Enter');await page.waitForTimeout(500);const inline=await obj(frame,0);
 await fire(frame,0,'dblclick');await frame.locator('#mvp44-inline').fill('취소 문구');await frame.locator('#mvp44-inline').press('Escape');const escaped=await obj(frame,0);
 await frame.locator('#mvp44-toolbar [data-prop=fontSize]').selectOption('24');await page.waitForTimeout(350);await frame.locator('#mvp44-toolbar [data-prop=bold]').click();await page.waitForTimeout(350);await frame.locator('#mvp44-toolbar [data-align=center]').click();await page.waitForTimeout(500);const toolbar=await obj(frame,0);
 await resize(page,frame,0,30,12);await page.waitForTimeout(700);const resized=await obj(frame,0);console.log('step:resize',resized);
 console.log('step:hide');await fire(frame,0,'contextmenu');await frame.evaluate(()=>document.querySelector('#mvp44-menu [data-action=hide]').click());await page.waitForTimeout(500);const hidden=await obj(frame,0);console.log('step:restore',hidden);await page.evaluate(()=>[...document.querySelectorAll('#patch-list .patch')].find(x=>x.textContent.includes('표시 여부'))?.querySelectorAll('button')[1]?.click());await page.waitForTimeout(500);const restored=await obj(frame,0);console.log('step:done',restored);
 const patches=await page.locator('.patch').count();await page.screenshot({path:path.join(shots,'mvp44-direct-editing.png'),fullPage:true});const after={form:sha(form),info:sha(info)},result={inline,escaped,toolbar,resized,hidden,restored,patches,hashes:{before,after,unchanged:before.form===after.form&&before.info===after.info}};fs.writeFileSync(path.join(logs,'mvp44-direct-editing-result.json'),JSON.stringify(result,null,2)+'\n');
 if(inline.text.trim()!=='MVP 4.4 직접 편집'||escaped.text.trim()!=='MVP 4.4 직접 편집'||toolbar.fontSize!==24||toolbar.fontWeight===inline.fontWeight||toolbar.textAlign!=='center'||(resized.width===toolbar.width&&resized.height===toolbar.height)||resized.scaleX!==1||resized.scaleY!==1||hidden.visible!==false||restored.visible!==true||!result.hashes.unchanged)throw new Error(JSON.stringify(result));console.log(JSON.stringify({success:true,result},null,2));
 }finally{await fetch(`${base}/api/render-patches?layoutDraftId=${draft}&projectName=sample&formName=sample`,{method:'DELETE'}).catch(()=>{});if(browser)await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
