const fs=require('fs'),path=require('path'),crypto=require('crypto');
process.env.LD_LIBRARY_PATH=path.resolve(__dirname,'../../runtime/browser-libs/root/usr/lib/x86_64-linux-gnu');
const {chromium}=require('/home/tjd618/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const cases=JSON.parse(fs.readFileSync('/tmp/mvp041-cases.json','utf8'));
const root=path.resolve(__dirname,'../..'),logs=path.join(root,'logs'),shots=path.join(root,'screenshots'),output=path.join(root,'output');
const base='http://127.0.0.1:3100';
const write=(name,value)=>fs.writeFileSync(path.join(logs,name),JSON.stringify(value,null,2)+'\n');
const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
function expected(c){return c.payload.items.flatMap(x=>[x.item,String(x.quantity),String(x.rate),String(x.amount)]);}
async function inspect(page,c){
  await page.waitForFunction(()=>window.canvasModule?.getCanvas?.(0)?.getObjects?.().length>0,{timeout:60000});
  await page.waitForTimeout(250);
  return page.evaluate(({items,customer,total})=>{const objects=[];for(let i=0;i<20;i++){const canvas=canvasModule.getCanvas(i);if(!canvas)break;for(const o of canvas.getObjects())objects.push({id:o.id||null,text:String(o.text??''),left:Number(o.left||0),top:Number(o.top||0),width:Number(o.width||0),height:Number(o.height||0)})}const itemSet=new Set(items),details=objects.filter(o=>itemSet.has(o.text)),ids=details.map(o=>o.id);return{pageCount:[...new Set(objects.map(o=>o.id))].length?1:0,objectCount:objects.length,runtimeDetailRows:details.length,detailIdentities:ids,identityCollisionCount:ids.length-new Set(ids).size,texts:objects.map(o=>o.text),customerPresent:objects.some(o=>o.text===customer),totalPresent:objects.some(o=>o.text===String(total)),geometry:details.map(o=>({id:o.id,left:o.left,top:o.top,width:o.width,height:o.height}))}}, {items:c.payload.items.map(x=>x.item),customer:c.payload.customerName,total:c.payload.totalAmount});
}
async function pdf(page,c){const wait=page.waitForResponse(r=>r.request().method()==='POST'&&r.headers()['content-type']?.includes('application/pdf'),{timeout:30000});await page.evaluate(()=>{canvasModule.captureAll();mainModule.callService('savePDF')});const emitted=await wait,replay=await page.context().request.post(emitted.url(),{data:emitted.request().postData()||'',headers:{'content-type':'application/x-www-form-urlencoded; charset=UTF-8'}}),file=path.join(output,`ai-builder-mvp041-${c.n}rows.pdf`);fs.writeFileSync(file,await replay.body());return{http:replay.status(),bytes:fs.statSync(file).size,sha256:sha(file),file:path.relative(root,file)}}
(async()=>{let browser;const evidence={environment:{nodeHealth:0,tomcatPort:true,viewerHealth:0},cases:[],newContexts:[],fatalErrors:[]};try{
  fs.mkdirSync(shots,{recursive:true});fs.mkdirSync(output,{recursive:true});
  const node=await fetch(base+'/'),viewer=await fetch(base+'/mysuit/UView5/index.jsp?projectName=sample&formName=sample');evidence.environment.nodeHealth=node.status;evidence.environment.viewerHealth=viewer.status;
  browser=await chromium.launch({executablePath:'/home/tjd618/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});
  for(const c of cases){const context=await browser.newContext({viewport:{width:1400,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const response=await page.goto(base+c.result.previewUrl,{waitUntil:'domcontentloaded',timeout:30000}),first=await inspect(page,c),reload=[];for(let i=0;i<3;i++){await page.reload({waitUntil:'domcontentloaded'});reload.push(await inspect(page,c))}const pdfResult=await pdf(page,c);await page.screenshot({path:path.join(shots,`ai-builder-mvp041-dynamic-${c.n}${c.n===1?'row':'rows'}.png`),fullPage:true});const content=expected(c).every(text=>first.texts.includes(text)),reloadPass=reload.every(x=>JSON.stringify({rows:x.runtimeDetailRows,texts:x.texts,geometry:x.geometry})===JSON.stringify({rows:first.runtimeDetailRows,texts:first.texts,geometry:first.geometry}));evidence.fatalErrors.push(...errors);evidence.cases.push({arrayLength:c.n,sourceDetailRows:c.result.sourceDetailRows,runtimeDetailRows:first.runtimeDetailRows,http:response.status(),viewerPass:response.status()===200&&first.runtimeDetailRows===c.n&&content&&!errors.length,pdfPass:pdfResult.http===200&&pdfResult.bytes>0,contentPass:content,scalarValues:{customer:first.customerPresent,total:first.totalPresent},identityCollisionCount:first.identityCollisionCount,detailIdentities:first.detailIdentities,reloadPass,reloads:reload.map(x=>({runtimeDetailRows:x.runtimeDetailRows,geometry:x.geometry})),pdf:pdfResult});await context.close()}
  const finalCase=cases.find(x=>x.n===5);for(let i=0;i<3;i++){const context=await browser.newContext(),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const response=await page.goto(base+finalCase.result.previewUrl,{waitUntil:'domcontentloaded'}),state=await inspect(page,finalCase);evidence.newContexts.push({context:i+1,http:response.status(),runtimeDetailRows:state.runtimeDetailRows,customerPresent:state.customerPresent,totalPresent:state.totalPresent,fatalErrors:errors});await context.close()}
  const c=cases.find(x=>x.n===3),context=await browser.newContext({viewport:{width:1500,height:1050}}),page=await context.newPage();await page.goto(`${base}/ai-builder?projectName=${c.created.projectName}&layoutDraftId=${c.created.draftId}`,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__mvp58?.state?.cursor===2,{timeout:30000});await page.click('#history-undo');await page.waitForFunction(projectName=>window.__mvp58?.state?.cursor===1&&document.querySelector('#viewer').contentWindow.location.href.includes(projectName)&&!document.querySelector('#viewer').contentWindow.location.href.includes('_array_'),c.created.projectName,{timeout:30000});await page.screenshot({path:path.join(shots,'ai-builder-mvp041-after-undo-static.png'),fullPage:true});const undo=await page.evaluate(()=>({cursor:__mvp58.state.cursor,structural:__mvp58.state.structuralState,iframe:document.querySelector('#viewer').contentWindow.location.href}));await page.click('#history-redo');await page.waitForFunction(()=>window.__mvp58?.state?.cursor===2&&document.querySelector('#viewer').contentWindow.canvasModule?.getCanvas?.(0)?.getObjects?.().filter(o=>/^상품[A-C]$/.test(o.text||'')).length===3,{timeout:60000});await page.screenshot({path:path.join(shots,'ai-builder-mvp041-after-redo-dynamic.png'),fullPage:true});const redo=await page.evaluate(()=>({cursor:__mvp58.state.cursor,structural:__mvp58.state.structuralState,iframe:document.querySelector('#viewer').contentWindow.location.href,rows:document.querySelector('#viewer').contentWindow.canvasModule.getCanvas(0).getObjects().filter(o=>/^상품[A-C]$/.test(o.text||'')).length}));evidence.structuralHistory={undo,redo,undoRestoresStatic:undo.structural.kind==='STATIC_SOURCE',redoRestoresDynamic:redo.structural.kind==='DYNAMIC_CANDIDATE'&&redo.rows===3};await context.close();
  evidence.pass=evidence.environment.nodeHealth===200&&evidence.environment.viewerHealth===200&&evidence.cases.every(x=>x.viewerPass&&x.pdfPass&&x.reloadPass&&x.scalarValues.customer&&x.scalarValues.total&&x.identityCollisionCount===0)&&evidence.newContexts.every(x=>x.http===200&&x.runtimeDetailRows===5&&!x.fatalErrors.length)&&evidence.structuralHistory.undoRestoresStatic&&evidence.structuralHistory.redoRestoresDynamic;
  write('ai-builder-mvp041-runtime-evidence.json',evidence);console.log(JSON.stringify(evidence,null,2));if(!evidence.pass)process.exitCode=1;
}finally{if(browser)await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
