const fs=require('fs'),path=require('path');
process.env.LD_LIBRARY_PATH='/home/tjd618/mysuit-ai-viewer/mysuit-mvp-work/runtime/browser-libs/root/usr/lib/x86_64-linux-gnu';
const {chromium}=require('/home/tjd618/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const base='http://127.0.0.1:3100',root=path.resolve(__dirname,'../..'),shots=path.join(root,'screenshots');
const hwpx=fs.readdirSync(path.join(root,'uploads/ai-builder')).map(name=>path.join(root,'uploads/ai-builder',name,'__.hwpx')).find(fs.existsSync);let browser;
(async()=>{try{
  if(!hwpx)throw new Error('HWPX fixture not found');browser=await chromium.launch({executablePath:'/home/tjd618/.cache/ms-playwright/chromium-1223/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});
  const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(`${base}/ai-builder/import`,{waitUntil:'networkidle'});
  const empty=await page.evaluate(()=>({sidebar:document.querySelector('.ai-sidebar').getBoundingClientRect().width,brand:document.querySelector('.ai-brand-name').textContent.trim(),brandHeight:document.querySelector('.ai-brand-name').getBoundingClientRect().height,menu:[...document.querySelectorAll('.ai-nav-item .ai-nav-label')].map(x=>x.textContent),title:document.querySelector('h1').textContent,jsonHidden:document.querySelector('#json-direct').hidden,jsonStatusRemoved:!document.querySelector('#json-status'),advancedOpen:document.querySelector('#advanced').open,supportVisible:Boolean(document.querySelector('.support-card')),hwpWarningVisible:Boolean(document.querySelector('.hwp-help')),summaryLabels:[...document.querySelectorAll('.summary-card dt')].map(x=>x.textContent),cta:document.querySelector('#create-form').getBoundingClientRect(),viewport:innerHeight,tempSave:[...document.querySelectorAll('button')].some(x=>x.textContent.trim()==='임시저장')}));
  await page.screenshot({path:path.join(shots,'upload-final-empty.png'),fullPage:true});
  await page.setInputFiles('#document-file',hwpx);await page.waitForFunction(()=>aiBuilderImport.state==='READY');const hwpxState=await page.evaluate(()=>({advancedHidden:document.querySelector('#advanced').hidden,document:document.querySelector('#summary-document').textContent,data:document.querySelector('#summary-json').textContent,status:document.querySelector('.file-state').textContent,ctaBottom:document.querySelector('#create-form').getBoundingClientRect().bottom}));await page.screenshot({path:path.join(shots,'upload-final-hwpx-selected.png'),fullPage:true});
  await page.setInputFiles('#json-file',{name:'employee.json',mimeType:'application/json',buffer:Buffer.from('{"employee":"홍길동"}')});const jsonFileState=await page.evaluate(()=>({visible:!document.querySelector('#json-meta').hidden,text:document.querySelector('#json-meta').textContent,summary:document.querySelector('#summary-json').textContent,statusBoxRemoved:!document.querySelector('#json-status')}));await page.click('#json-meta button');await page.click('#json-toggle');await page.fill('#json-input','{"applicantName":"홍길동"}');const jsonExpanded=await page.evaluate(()=>!document.querySelector('#json-direct').hidden&&document.querySelector('#json-toggle').getAttribute('aria-expanded')==='true');await page.screenshot({path:path.join(shots,'upload-final-json-expanded.png'),fullPage:true});
  await page.route('**/api/ai-builder/import',async route=>{await new Promise(resolve=>setTimeout(resolve,1000));await route.fulfill({status:400,contentType:'application/json',body:'{"success":false,"message":"visual test"}'})},{times:1});await page.click('#create-form');await page.waitForSelector('#job-state:not([hidden])');await page.screenshot({path:path.join(shots,'upload-final-processing.png'),fullPage:true});await page.waitForSelector('#form-error-wrap:not([hidden])');
  await page.setViewportSize({width:1920,height:1080});await page.goto(`${base}/ai-builder/import`,{waitUntil:'domcontentloaded'});const wide=await page.evaluate(()=>({sidebar:document.querySelector('.ai-sidebar').getBoundingClientRect().width,right:document.querySelector('.info-panel').getBoundingClientRect().width,ctaBottom:document.querySelector('#create-form').getBoundingClientRect().bottom,viewport:innerHeight}));
  const result={empty,hwpxState,jsonFileState,jsonExpanded,wide,errors,screenshots:['upload-final-empty.png','upload-final-hwpx-selected.png','upload-final-json-expanded.png','upload-final-processing.png']};const pass=empty.sidebar===184&&empty.brand==='MySuit AI Builder'&&empty.brandHeight<30&&empty.menu.join('|')==='생성하기|편집하기|내 작업|템플릿|설정'&&empty.title==='서식 생성'&&empty.jsonHidden&&empty.jsonStatusRemoved&&!empty.advancedOpen&&!empty.supportVisible&&!empty.hwpWarningVisible&&empty.summaryLabels.join('|')==='문서|데이터'&&!empty.tempSave&&empty.cta.bottom<=empty.viewport&&hwpxState.advancedHidden&&hwpxState.data==='없음'&&hwpxState.status.includes('준비 완료')&&hwpxState.ctaBottom<=900&&jsonFileState.visible&&jsonFileState.text.includes('employee.json')&&jsonFileState.text.includes('확인 완료')&&jsonFileState.summary==='employee.json'&&jsonFileState.statusBoxRemoved&&jsonExpanded&&wide.sidebar===184&&wide.right>=300&&wide.right<=320&&wide.ctaBottom<=wide.viewport&&errors.length===0;if(!pass)throw new Error(JSON.stringify(result));console.log(JSON.stringify(result,null,2));
}finally{if(browser)await browser.close()}})().catch(error=>{console.error(error);process.exit(1)});
