const {chromium}=require('/home/tjd618/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const base='http://127.0.0.1:3100',draft='ux_layout_regression',query=`layoutDraftId=${draft}&projectName=sample&formName=sample`;
(async()=>{let browser;try{
  await fetch(`${base}/api/structure-operations?${query}`,{method:'DELETE'});
  await fetch(`${base}/api/render-patches?${query}`,{method:'DELETE'});
  browser=await chromium.launch({executablePath:'/home/tjd618/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});
  const page=await browser.newPage({viewport:{width:1600,height:1000}});
  await page.goto(`${base}/?layoutDraftId=${draft}`,{waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>window.__mvp57&&window.__mvp51?.columns?.length===7&&document.getElementById('viewer').contentWindow.canvasModule?.getCanvas?.(0)?.getObjects?.().length===180,{timeout:30000});
  const frame=page.frames().find(value=>value.url().includes('/UView5/index.jsp'));
  const before=await frame.locator('.mvp57-column-drag-zone,.mvp57-row-gutter,.mvp57-table-grip').count();
  await page.click('#review-toggle');
  await frame.waitForSelector('.mvp57-column-header-zone');
  const zone=frame.locator('.mvp57-column-drag-zone').nth(1),box=await zone.boundingBox();
  await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.up();
  await page.waitForTimeout(300);
  const columnSelection=await page.evaluate(()=>({body:document.body.className,target:document.getElementById('capability-target').textContent,viewerId:document.getElementById('viewer-id').textContent}));
  const toolbarAfterColumn=await frame.locator('#mvp44-toolbar:not([hidden])').count();
  const row=frame.locator('.mvp57-row-gutter').filter({hasText:'↕'}).first(),rowBox=await row.boundingBox();
  await page.mouse.move(rowBox.x+rowBox.width/2,rowBox.y+rowBox.height/2);await page.mouse.down();await page.mouse.up();
  await page.waitForTimeout(300);
  const rowSelection=await page.evaluate(()=>({body:document.body.className,target:document.getElementById('capability-target').textContent,viewerId:document.getElementById('viewer-id').textContent}));
  const toolbarAfterRow=await frame.locator('#mvp44-toolbar:not([hidden])').count();
  await frame.evaluate(()=>scrollTo(0,420));await page.waitForTimeout(350);
  const geometry=await frame.evaluate(()=>{const canvas=document.querySelector('canvas.upper-canvas').getBoundingClientRect(),controls=[...document.querySelectorAll('.mvp57-column-drag-zone,.mvp57-table-grip')].map(x=>x.getBoundingClientRect());return{canvas:{top:canvas.top,left:canvas.left,right:canvas.right,bottom:canvas.bottom},controls:controls.map(x=>({top:x.top,left:x.left,right:x.right,bottom:x.bottom})),legacy:document.querySelectorAll('.mvp51-overlay,.mvp52-row-overlay,.mvp53-overlay').length,toolbar:document.querySelectorAll('#mvp44-toolbar:not([hidden])').length}});
  const layout=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,aside:document.querySelector('main>aside').getBoundingClientRect().width,oldPanels:[...document.querySelectorAll('#mvp51-panel,#mvp52-row,#mvp53-table')].filter(x=>getComputedStyle(x).display!=='none').length}));
  await page.screenshot({path:'/tmp/mysuit-unified-ux.png',fullPage:true});
  const controlsInside=geometry.controls.every(x=>x.top>=geometry.canvas.top&&x.left>=geometry.canvas.left&&x.right<=geometry.canvas.right+1);
  const success=before===0&&columnSelection.body.includes('target-logical-column')&&columnSelection.viewerId==='—'&&toolbarAfterColumn===0&&rowSelection.body.includes('target-logical-row')&&rowSelection.viewerId==='—'&&toolbarAfterRow===0&&controlsInside&&geometry.legacy===0&&geometry.toolbar===0&&!layout.overflow&&layout.oldPanels===0;
  const result={success,before,columnSelection,rowSelection,toolbarAfterColumn,toolbarAfterRow,geometry,layout,controlsInside};console.log(JSON.stringify(result,null,2));if(!success)process.exitCode=1;
}finally{await fetch(`${base}/api/structure-operations?${query}`,{method:'DELETE'}).catch(()=>{});await fetch(`${base}/api/render-patches?${query}`,{method:'DELETE'}).catch(()=>{});if(browser)await browser.close()}})().catch(error=>{console.error(error);process.exitCode=1});
