const fs=require('fs'),path=require('path'),crypto=require('crypto');const {chromium}=require('/home/tjd618/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const base='http://127.0.0.1:3100',draft='layout_sample_mvp51',query=`layoutDraftId=${draft}&projectName=sample&formName=sample`,root=path.resolve(__dirname,'../..'),logs=path.join(root,'logs'),shots=path.join(root,'screenshots'),project=path.resolve(root,'..');fs.mkdirSync(logs,{recursive:true});fs.mkdirSync(shots,{recursive:true});
const form=path.join(project,'apache-tomcat-8.5.78/webapps/MYSUIT/UFile/project/sample/sample/form.ubjf'),info=form.replace('form.ubjf','info.xml'),sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),candidateDirs=()=>fs.readdirSync(path.join(project,'apache-tomcat-8.5.78/webapps/MYSUIT/UFile/project')).filter(x=>/^sample_mvp4_/.test(x)).sort();
async function ready(page){await page.goto(`${base}/?layoutDraftId=${draft}`);await page.waitForFunction(()=>window.__mvp51?.columns?.every(x=>x.length===24)&&!document.querySelector('#viewer').classList.contains('viewer-loading'));return page.frames().find(f=>f.url().includes('/UView5/index.jsp'))}
async function clickSource(page,_frame,source){const headers=['UB5305348','UB5302287','UB5313710','UB5297739','UB5337756','UB5316883','UB5273553'];await page.evaluate(i=>__mvp51.select(i),headers.indexOf(source))}
async function layout(page){return page.evaluate(()=>({ops:__mvp51.operations.map(x=>({operation:x.operation,columnIndex:x.columnIndex,afterWidth:x.afterWidth})),state:__mvp51.state(),columns:__mvp51.columns.map(c=>({count:c.length,visible:c.filter(x=>x.object.visible!==false).length,widths:[...new Set(c.map(x=>x.object.width))],lefts:[...new Set(c.map(x=>Math.round(x.object.left)))].sort((a,b)=>a-b)}))}))}
async function setWidth(page,index,width){await page.evaluate(i=>__mvp51.select(i),index);await page.locator('#mvp51-width').fill(String(width));await page.click('#mvp51-save-width');await page.waitForFunction(({i,w})=>__mvp51.state().widths[i]===w,{i:index,w:width})}
(async()=>{let browser;const hashBefore={form:sha(form),info:sha(info)},dirsBefore=candidateDirs(),times={};try{await fetch(`${base}/api/structure-operations?${query}`,{method:'DELETE'});browser=await chromium.launch({executablePath:'/home/tjd618/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1680,height:1150}}),page=await context.newPage(),frame=await ready(page);await page.click('#review-toggle');
 let t=performance.now();await clickSource(page,frame,'UB5313710');await page.waitForFunction(()=>__mvp51.selection===2);times.selectionMs=performance.now()-t;const selection=await page.evaluate(()=>({index:__mvp51.selection,count:__mvp51.columns[2].length,roles:Object.fromEntries(['HEADER','GROUP_HEADER','DETAIL_TEMPLATE','SUMMARY'].map(r=>[r,__mvp51.columns[2].filter(x=>x.role===r).length])),otherIncluded:__mvp51.columns[2].filter(x=>x.columnIndex!==2).length,locked:__mvp51.columns[2].every(x=>x.object.lockMovementX&&x.object.lockMovementY)}));await page.screenshot({path:path.join(shots,'mvp51-column-selected.png'),fullPage:true});fs.writeFileSync(path.join(logs,'mvp51-column-selection.json'),JSON.stringify(selection,null,2)+'\n');
 const handle=frame.locator('.mvp51-handle');await handle.waitFor();const hb=await handle.boundingBox();t=performance.now();await page.mouse.move(hb.x+5,hb.y+30);await page.mouse.down();await page.mouse.move(hb.x+35,hb.y+30,{steps:8});await page.screenshot({path:path.join(shots,'mvp51-column-resizing.png'),fullPage:true});await page.mouse.up();await page.waitForFunction(()=>__mvp51.state().widths[2]===100);times.resizeMs=performance.now()-t;const resized=await layout(page);await page.screenshot({path:path.join(shots,'mvp51-column-resized.png'),fullPage:true});fs.writeFileSync(path.join(logs,'mvp51-column-resize.json'),JSON.stringify(resized,null,2)+'\n');
 await clickSource(page,frame,'UB5337756');await page.waitForFunction(()=>__mvp51.selection===4);const beforeHide=await layout(page);t=performance.now();await page.click('#mvp51-hide');await page.waitForFunction(()=>__mvp51.state().hidden[4]);times.hideMs=performance.now()-t;const hidden=await layout(page);await page.screenshot({path:path.join(shots,'mvp51-column-hidden.png'),fullPage:true});fs.writeFileSync(path.join(logs,'mvp51-column-hide.json'),JSON.stringify({before:beforeHide,after:hidden},null,2)+'\n');
 t=performance.now();await page.locator('#mvp51-ops .op').filter({hasText:'Column 4 숨김'}).getByRole('button',{name:'다시 표시'}).click();await page.waitForFunction(()=>!__mvp51.state().hidden[4]);times.restoreMs=performance.now()-t;const restored=await layout(page);await page.screenshot({path:path.join(shots,'mvp51-column-restored.png'),fullPage:true});fs.writeFileSync(path.join(logs,'mvp51-column-restore.json'),JSON.stringify(restored,null,2)+'\n');
 await setWidth(page,1,90);await setWidth(page,3,110);await page.evaluate(()=>__mvp51.select(5));await page.click('#mvp51-hide');await page.waitForFunction(()=>__mvp51.state().hidden[5]);const multiple=await layout(page);await page.screenshot({path:path.join(shots,'mvp51-multiple-operations.png'),fullPage:true});
 const samples=[];for(let i=0;i<5;i++){await page.reload();await readyAfter(page);samples.push({kind:'refresh',index:i+1,layout:await layout(page)})}for(let i=0;i<5;i++){const p=await context.newPage();await ready(p);samples.push({kind:'new-page',index:i+1,layout:await layout(p)});await p.close()}const expected=JSON.stringify(multiple),stable=samples.every(x=>JSON.stringify(x.layout)===expected);fs.writeFileSync(path.join(logs,'mvp51-structure-replay.json'),JSON.stringify({stable,expected:multiple,samples},null,2)+'\n');
 await page.click('#review-toggle');await page.evaluate(()=>__mvp51.select(1));const inlineFrame=page.frames().find(f=>f.url().includes('/UView5/index.jsp'));await inlineFrame.evaluate(()=>{const c=canvasModule.getCanvas(0),o=c.getObjects()[0],el=document.querySelector('canvas.upper-canvas'),r=el.getBoundingClientRect(),v=c.viewportTransform||[1,0,0,1,0,0];el.dispatchEvent(new MouseEvent('dblclick',{bubbles:true,cancelable:true,clientX:r.left+(o.left+10)*v[0]*r.width/el.width,clientY:r.top+(o.top+10)*v[3]*r.height/el.height}))});const inline=await inlineFrame.locator('#mvp44-inline').count();if(inline)await inlineFrame.locator('#mvp44-inline').press('Escape');const regression={inlineEditorOpened:inline===1,objectCount:await inlineFrame.evaluate(()=>canvasModule.getCanvas(0).getObjects().length),columnMembers:await page.evaluate(()=>__mvp51.columns.map(x=>x.length))};fs.writeFileSync(path.join(logs,'mvp51-regression.json'),JSON.stringify(regression,null,2)+'\n');
 const hashAfter={form:sha(form),info:sha(info)},integrity={hashBefore,hashAfter,unchanged:hashBefore.form===hashAfter.form&&hashBefore.info===hashAfter.info,candidateDirsBefore:dirsBefore,candidateDirsAfter:candidateDirs(),newCandidateDirs:candidateDirs().filter(x=>!dirsBefore.includes(x))};fs.writeFileSync(path.join(logs,'mvp51-integrity.json'),JSON.stringify(integrity,null,2)+'\n');fs.writeFileSync(path.join(logs,'mvp51-performance.json'),JSON.stringify(times,null,2)+'\n');fs.writeFileSync(path.join(logs,'mvp51-column-reorder.json'),JSON.stringify({implemented:false,status:'STOPPED_BY_SCOPE',reason:'source UBTable array/binding atomicity not yet verified'},null,2)+'\n');
 if(selection.count!==24||selection.roles.HEADER!==1||selection.roles.GROUP_HEADER!==3||selection.roles.DETAIL_TEMPLATE!==17||selection.roles.SUMMARY!==3||selection.otherIncluded||!selection.locked||resized.state.widths[2]!==100||hidden.columns[4].visible!==0||hidden.state.offsets[5]!==restored.state.offsets[5]-70||!stable||!regression.inlineEditorOpened||!integrity.unchanged||integrity.newCandidateDirs.length)throw new Error('MVP51 assertions failed');console.log(JSON.stringify({success:true,selection,resized:resized.state,hidden:hidden.state,restored:restored.state,multiple:multiple.state,stable,regression,integrity,times},null,2));
 }finally{await fetch(`${base}/api/structure-operations?${query}`,{method:'DELETE'}).catch(()=>{});if(browser)await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
async function readyAfter(page){await page.waitForFunction(()=>window.__mvp51?.columns?.every(x=>x.length===24)&&!document.querySelector('#viewer').classList.contains('viewer-loading'));}
