const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { chromium } = require('/home/tjd618/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const { removeCandidate } = require('../src/server/services/project-copy-service');
const historyService = require('../src/server/services/history-service');
const structureService = require('../src/server/services/structure-operation-service');
const renderService = require('../src/server/services/render-patch-service');
const changesService = require('../src/server/services/changeset-service');

const base='http://127.0.0.1:3100',projectName='import_mvp11_20260827_170551_e59e1d',formName='SampleReport_FreeForm';
const objectDraft='mvp12_object_e2e',structureDraft='mvp12_structure_e2e',work=path.resolve(__dirname,'../..'),logs=path.join(work,'logs'),shots=path.join(work,'screenshots'),output=path.join(work,'output');
fs.mkdirSync(logs,{recursive:true});fs.mkdirSync(shots,{recursive:true});fs.mkdirSync(output,{recursive:true});
const write=(name,value)=>fs.writeFileSync(path.join(logs,name),JSON.stringify(value,null,2)+'\n');
const scope=draft=>({layoutDraftId:draft,projectName,formName}),url=draft=>`${base}/?projectName=${projectName}&layoutDraftId=${draft}`;
const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
async function editor(page,draft){const errors=[];page.on('pageerror',e=>errors.push(e.message));const response=await page.goto(url(draft),{waitUntil:'domcontentloaded',timeout:30000});await page.waitForFunction(()=>!document.querySelector('#viewer').classList.contains('viewer-loading')&&window.__mvp12?.model?.cells?.length===12,null,{timeout:30000});return{status:response.status(),errors,objectCount:Number((await page.locator('#viewer-state').textContent()).match(/\d+/)?.[0])}}
async function pdf(page,file){const wait=page.waitForResponse(r=>r.request().method()==='POST'&&r.headers()['content-type']?.includes('application/pdf'));await page.evaluate(()=>{canvasModule.captureAll();mainModule.callService('savePDF')});const observed=await wait,replay=await page.context().request.post(observed.url(),{data:observed.request().postData()||'',headers:{'content-type':'application/x-www-form-urlencoded; charset=UTF-8'}});fs.writeFileSync(file,await replay.body());return{status:replay.status(),bytes:fs.statSync(file).size,sha256:sha(file)}}
function cleanupScope(s){try{structureService.clear(s)}catch(_){}try{renderService.clear(s)}catch(_){}try{historyService.clear(s)}catch(_){}const draft=changesService.findDraft(s);if(draft&&draft.status==='DRAFT')try{changesService.discard(draft.changeSetId)}catch(_){}}

(async()=>{const browser=await chromium.launch({headless:true});let objectCandidate,structureCandidate;cleanupScope(scope(objectDraft));cleanupScope(scope(structureDraft));try{
  const context=await browser.newContext({viewport:{width:1800,height:1200}}),page=await context.newPage(),attached=await editor(page,objectDraft);await page.click('#review-toggle');
  await page.frameLocator('#viewer').locator('canvas.upper-canvas').click({position:{x:397,y:76}});await page.waitForFunction(()=>document.querySelector('#source-id').textContent==='IMPLB0001');await page.screenshot({path:path.join(shots,'import-mvp12-object-selected.png'),fullPage:true});
  await page.evaluate(()=>mvpDirectBridge.property('text','AI 변환 실적 보고서'));await page.waitForFunction(()=>document.querySelector('#history-cursor').textContent.startsWith('1 / 1'));const edited=await page.frameLocator('#viewer').locator('body').evaluate(()=>canvasModule.getCanvas(0).getObjects().find(x=>x.id==='IMPLB0001').text);
  await page.click('#history-undo');await page.waitForFunction(()=>document.querySelector('#history-cursor').textContent.startsWith('0 / 1'));await page.click('#history-redo');await page.waitForFunction(()=>document.querySelector('#history-cursor').textContent.startsWith('1 / 1'));
  await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__mvp12?.model?.cells?.length===12&&!document.querySelector('#viewer').classList.contains('viewer-loading'));await page.click('#review-toggle');await page.waitForTimeout(300);const reloadText=await page.evaluate(()=>document.querySelector('#viewer').contentWindow.canvasModule.getCanvas(0).getObjects().find(x=>x.id==='IMPLB0001').text);
  const fresh=await browser.newContext({viewport:{width:1800,height:1200}}),freshPage=await fresh.newPage();await editor(freshPage,objectDraft);await freshPage.click('#review-toggle');await freshPage.waitForTimeout(300);const freshText=await freshPage.evaluate(()=>document.querySelector('#viewer').contentWindow.canvasModule.getCanvas(0).getObjects().find(x=>x.id==='IMPLB0001').text);
  const cs=changesService.findDraft(scope(objectDraft));objectCandidate=await freshPage.evaluate(async id=>fetch(`/api/change-sets/${id}/candidate`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'}).then(r=>r.json()),cs.changeSetId);await freshPage.goto(`${base}${objectCandidate.previewUrl}`);await freshPage.waitForFunction(()=>canvasModule?.getCanvas?.(0)?.getObjects?.().some(x=>x.id==='IMPLB0001'));const candidateText=await freshPage.evaluate(()=>canvasModule.getCanvas(0).getObjects().find(x=>x.id==='IMPLB0001').text),objectPdf=await pdf(freshPage,path.join(output,'import-mvp12-object-edited.pdf'));await fresh.close();await context.close();
  write('import-mvp12-object-edit.json',{attached,sourceId:'IMPLB0001',before:'월간 실적 보고서',after:edited,undo:true,redo:true,reloadText,freshText,candidateText,historyEvents:1,pass:[edited,reloadText,freshText,candidateText].every(x=>x==='AI 변환 실적 보고서')});

  const sc=await browser.newContext({viewport:{width:1800,height:1200}}),sp=await sc.newPage(),structureAttached=await editor(sp,structureDraft);await sp.click('#review-toggle');await sp.evaluate(()=>__mvp12.selectColumn(1));await sp.screenshot({path:path.join(shots,'import-mvp12-column-selected.png'),fullPage:true});const colSelection=await sp.evaluate(()=>__mvp12.selection);await sp.evaluate(()=>__mvp12.save('resizeColumn',{afterWidth:240}));
  await sp.evaluate(()=>__mvp12.selectRow(1));await sp.screenshot({path:path.join(shots,'import-mvp12-row-selected.png'),fullPage:true});const rowSelection=await sp.evaluate(()=>__mvp12.selection);await sp.evaluate(()=>__mvp12.save('resizeRow',{afterHeight:52}));
  await sp.evaluate(()=>__mvp12.selectTable());await sp.screenshot({path:path.join(shots,'import-mvp12-table-selected.png'),fullPage:true});const tableSelection=await sp.evaluate(()=>__mvp12.selection);await sp.evaluate(()=>__mvp12.save('moveTable',{before:{left:82,top:165},after:{left:102,top:185}}));await sp.screenshot({path:path.join(shots,'import-mvp12-after-edit.png'),fullPage:true});
  await sp.waitForFunction(()=>document.querySelector('#history-cursor').textContent.startsWith('3 / 3'));const geometry=()=>sp.evaluate(()=>['IMPCL0001','IMPCL0002','IMPCL0004'].map(id=>{const o=document.querySelector('#viewer').contentWindow.canvasModule.getCanvas(0).getObjects().find(x=>x.id===id);return{id,left:o.left,top:o.top,width:o.width,height:o.height}}));const after=await geometry();await sp.click('#history-undo');await sp.waitForFunction(()=>document.querySelector('#history-cursor').textContent.startsWith('2 / 3'));await sp.click('#history-redo');await sp.waitForFunction(()=>document.querySelector('#history-cursor').textContent.startsWith('3 / 3'));await sp.reload({waitUntil:'domcontentloaded'});await sp.waitForFunction(()=>window.__mvp12?.operations?.length===3);const reloaded=await geometry();
  const nc=await browser.newContext({viewport:{width:1800,height:1200}}),np=await nc.newPage();await editor(np,structureDraft);const newContextGeometry=await np.evaluate(()=>['IMPCL0001','IMPCL0002','IMPCL0004'].map(id=>{const o=document.querySelector('#viewer').contentWindow.canvasModule.getCanvas(0).getObjects().find(x=>x.id===id);return{id,left:o.left,top:o.top,width:o.width,height:o.height}}));await nc.close();
  structureCandidate=await sp.evaluate(async body=>{const r=await fetch('/api/static-table-candidate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return{status:r.status,body:await r.json()}},scope(structureDraft));if(structureCandidate.status!==201)throw new Error(JSON.stringify(structureCandidate));await sp.goto(`${base}${structureCandidate.body.previewUrl}`);await sp.waitForFunction(()=>canvasModule?.getCanvas?.(0)?.getObjects?.().some(x=>x.id==='IMPCL0012'));const structurePdf=await pdf(sp,path.join(output,'import-mvp12-edited.pdf'));await sc.close();
  write('import-mvp12-column-edit.json',{selectionCount:colSelection.members.length,sourceCellIds:colSelection.members.map(x=>x.id),beforeWidth:210,afterWidth:240,history:true,reload:true});write('import-mvp12-row-edit.json',{selectionCount:rowSelection.members.length,sourceCellIds:rowSelection.members.map(x=>x.id),beforeHeight:40,afterHeight:52,history:true,reload:true});write('import-mvp12-table-edit.json',{selectionCount:tableSelection.members.length,sourceCellIds:tableSelection.members.map(x=>x.id),move:{dx:20,dy:20},after,reloaded,newContextGeometry,undoRedo:true});write('import-mvp12-candidate.json',{objectCandidate:{name:objectCandidate.candidateProjectName,text:candidateText},structureCandidate:{name:structureCandidate.body.candidateProjectName,operations:3},mixedEdit:{status:'BLOCKED',code:'MIXED_CANONICAL_SERIALIZER_UNAVAILABLE'}});write('import-mvp12-pdf.json',{object:objectPdf,structure:structurePdf,structureFile:'output/import-mvp12-edited.pdf'});write('import-mvp12-history.json',{objectDraft:{events:1},structureDraft:{events:3,undoRedo:true,reload:true,newContext:true},isolated:true});
  if(!attached.status||attached.errors.length||colSelection.members.length!==4||rowSelection.members.length!==3||tableSelection.members.length!==12||JSON.stringify(after)!==JSON.stringify(reloaded)||JSON.stringify(after)!==JSON.stringify(newContextGeometry)||objectPdf.status!==200||structurePdf.status!==200)throw new Error('MVP12 E2E assertion failed');
}finally{if(objectCandidate?.candidateId){const all=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/candidates.json')));const record=all.find(x=>x.candidateId===objectCandidate.candidateId);if(record)try{removeCandidate(record.candidateProjectName)}catch(_){}}if(structureCandidate?.body?.candidateProjectName)try{removeCandidate(structureCandidate.body.candidateProjectName)}catch(_){}cleanupScope(scope(objectDraft));cleanupScope(scope(structureDraft));await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
