const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const registry=require('../src/server/services/operation-registry'),capability=require('../src/server/services/capability-service'),validator=require('../src/server/services/operation-validator');
const root=path.resolve(__dirname,'../..'),logs=path.join(root,'logs'),scope={draftId:'mvp59_snapshot',layoutDraftId:'mvp59_snapshot',projectName:'sample',formName:'sample'};
const write=(name,value)=>fs.writeFileSync(path.join(logs,name),JSON.stringify(value,null,2)+'\n');
test('writes reproducible registry, matrix, catalog, snapshot and performance evidence',()=>{
  fs.mkdirSync(logs,{recursive:true});
  const operations=registry.list(),targets=[['OBJECT',{viewerObjectId:'LB6417_UPHB2584_ROW0'}],['LOGICAL_COLUMN',{logicalColumnKey:'tbl:financial-7col|col:2'}],['LOGICAL_ROW',{logicalRowKey:'tbl:financial-7col|band:UDHB4114|rendered-row:0'}],['LOGICAL_ROW',{logicalRowKey:'tbl:financial-7col|band:grp_0_UDB3195|rendered-row:0'}],['COMPOSITE_TABLE',{compositeTableKey:'ctbl:main-report-table'}]],snapshots=targets.map(([type,target])=>capability.getCapabilities(scope,type,target)),matrix=snapshots.flatMap(s=>Object.entries(s.capabilities).map(([operation,c])=>({targetType:s.targetType,targetKey:s.targetKey,operation,allowed:c.allowed,reason:c.reason||null,maturity:c.constraints.maturity,support:c.constraints.support}))),catalog=['TABLE_WIDTH_OVERFLOW','DATA_REPEAT_ROW','ROWSPAN_DEPENDENCY','CROSS_BAND_REFLOW_UNVERIFIED','GROUP_BOUNDARY_MOVE_NOT_ALLOWED','FORMULA_DEPENDENCY','SUMMARY_DEPENDENCY','BINDING_DEPENDENCY','LAST_COLUMN_REMOVE_NOT_ALLOWED','HIDDEN_COLUMN_OPERATION_NOT_ALLOWED','UNSUPPORTED_TARGET_TYPE','UNSUPPORTED_OPERATION','TARGET_NOT_FOUND','AMBIGUOUS_TARGET','SOURCE_MAPPING_UNVERIFIED','RENDER_INSTANCE_ONLY','PDF_OUTPUT_UNSUPPORTED','EXCEL_OUTPUT_UNSUPPORTED','HISTORY_LIMIT_REACHED','INVALID_PAYLOAD','RUNTIME_UI_NOT_CONNECTED','CANONICAL_SERIALIZER_REQUIRED'];
  const started=performance.now();for(let i=0;i<100;i++)capability.getCapabilities(scope,'LOGICAL_COLUMN',{logicalColumnKey:`tbl:financial-7col|col:${i%7}`});const capabilityMs=performance.now()-started,validationStarted=performance.now();for(let i=0;i<100;i++)validator.validate({...scope,targetType:'LOGICAL_COLUMN',target:{logicalColumnKey:'tbl:financial-7col|col:2'},operation:'resizeColumn',payload:{width:71}});const validationMs=performance.now()-validationStarted;
  write('mvp59-operation-registry.json',{schemaVersion:1,operations});write('mvp59-capability-matrix.json',{schemaVersion:1,matrix});write('mvp59-validation-error-catalog.json',{schemaVersion:1,codes:catalog});write('mvp59-capability-snapshot.json',{schemaVersion:1,snapshots});write('mvp59-performance.json',{iterations:100,capabilityTotalMs:capabilityMs,capabilityAverageMs:capabilityMs/100,validationTotalMs:validationMs,validationAverageMs:validationMs/100});
  // 32 canonical operations + moveRows/moveColumns (Direct Edit Interaction 3.2 set moves).
  assert.equal(operations.length,34);assert.ok(matrix.some(x=>x.reason==='DATA_REPEAT_ROW'));assert.ok(capabilityMs/100<100);
  const form=path.join(root,'../apache-tomcat-8.5.78/webapps/MYSUIT/UFile/project/sample/sample/form.ubjf'),info=path.join(root,'../apache-tomcat-8.5.78/webapps/MYSUIT/UFile/project/sample/sample/info.xml'),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');write('mvp59-integrity.json',{formSha256:sha(form),infoSha256:sha(info),checkedAt:new Date().toISOString()});
});
