const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');
const service=require('../src/server/services/render-patch-service');
const file=path.join(__dirname,'../data/render-patches.json'),original=fs.readFileSync(file,'utf8');
const base={layoutDraftId:'layout_sample_default',projectName:'sample',formName:'sample',pageIndex:0,canvasIndex:0,renderIndex:0,renderInstanceKey:'p0|c0|src:LB6417|band:UPHB2584|row:0|idx:0',viewerObjectId:'LB6417_UPHB2584_ROW0',sourceObjectId:'LB6417',bandId:'UPHB2584',rowIndex:0,className:'UBLabel',originalFingerprint:{left:100,top:100,width:425,height:68},before:{left:100,top:100},after:{left:130,top:80}};
test.beforeEach(()=>fs.writeFileSync(file,'{"patches":[]}\n'));test.after(()=>fs.writeFileSync(file,original));
test('creates, updates while preserving first before, lists and deletes a position patch',()=>{const first=service.upsert(base);assert.match(first.patchId,/^rp_/);const updated=service.upsert({...base,before:{left:130,top:80},after:{left:140,top:70}});assert.equal(updated.patchId,first.patchId);assert.deepEqual(updated.before,{left:100,top:100});assert.deepEqual(updated.after,{left:140,top:70});assert.equal(service.list(base).length,1);assert.throws(()=>service.remove(first.patchId,{...base,layoutDraftId:'layout_other'}),/현재 Draft/);const removed=service.remove(first.patchId,base);assert.equal(removed.patchId,first.patchId);assert.equal(service.list(base).length,0)});
test('rejects invalid coordinates, viewer mapping and unsupported classes',()=>{assert.throws(()=>service.upsert({...base,after:{left:Infinity,top:0}}),/유한 숫자/);assert.throws(()=>service.upsert({...base,sourceObjectId:'WRONG'}),/매핑/);assert.throws(()=>service.upsert({...base,className:'UBImage'}),/UBLabel/)});
test('clears only the requested draft and rejects missing patches',()=>{service.upsert(base);service.upsert({...base,layoutDraftId:'layout_other'});const removed=service.clear(base);assert.equal(removed.length,1);assert.equal(service.list(base).length,0);assert.equal(service.list({...base,layoutDraftId:'layout_other'}).length,1);assert.throws(()=>service.remove('rp_missing',base),/찾을 수 없습니다/)});
test('stores duplicate viewer IDs independently by render instance key',()=>{const first=service.upsert(base),second=service.upsert({...base,renderIndex:1,renderInstanceKey:'p0|c0|src:LB6417|band:UPHB2584|row:0|idx:1',originalFingerprint:{left:200,top:100,width:425,height:68},before:{left:200,top:100},after:{left:210,top:100}});assert.notEqual(first.patchId,second.patchId);assert.equal(service.list(base).length,2)});
